# =============================================================================
# SSM Parameter Store — /footbag/{env}/...
# All application secrets live here. SecureString type with KMS encryption.
#
# TODO: After apply, set actual secret values via AWS Console or CLI:
#   aws ssm put-parameter --name "/footbag/production/app/secret_key" \
#     --value "$(openssl rand -hex 32)" --type SecureString \
#     --key-id alias/footbag-production --overwrite
# =============================================================================

resource "aws_ssm_parameter" "app_port" {
  name  = "${local.ssm_prefix}/app/port"
  type  = "String"
  value = "3000"
}

resource "aws_ssm_parameter" "app_log_level" {
  name  = "${local.ssm_prefix}/app/log_level"
  type  = "String"
  value = "warn" # production: suppress info logs
}

# Arming switches. Terraform is the writer (like app_log_level): arming is a
# tfvars flip + apply, and the next deploy syncs each value into
# /srv/footbag/env and derives the matching adapter on this host
# (armed -> live, dark -> stub). No ignore_changes: out-of-band put-parameter
# drift is reverted on the next apply, keeping tfvars, SSM, and the host in
# one line of custody, with SSM parameter history as the audit trail.
resource "aws_ssm_parameter" "app_payments_armed" {
  name  = "${local.ssm_prefix}/app/payments_armed"
  type  = "String"
  value = var.payments_armed
}

resource "aws_ssm_parameter" "app_email_send_armed" {
  name  = "${local.ssm_prefix}/app/email_send_armed"
  type  = "String"
  value = var.email_send_armed
}

# The two SES configuration sets the runtime names on a send, one per sending
# stream. Transactional and bulk mail keep separate reputations so a complaint
# spike on a broadcast cannot degrade delivery of a password reset, and the
# configuration set is where SES keeps those metrics apart. The value is read
# from the resource rather than repeated as a literal, so renaming a set moves
# the parameter with it and the host cannot end up naming a set that no longer
# exists. Plain String, not SecureString: a configuration set name is not a
# secret, and the deploy reads it without a decrypt.
resource "aws_ssm_parameter" "app_ses_configuration_set_transactional" {
  name  = "${local.ssm_prefix}/app/ses_configuration_set_transactional"
  type  = "String"
  value = aws_ses_configuration_set.transactional.name
}

resource "aws_ssm_parameter" "app_ses_configuration_set_bulk" {
  name  = "${local.ssm_prefix}/app/ses_configuration_set_bulk"
  type  = "String"
  value = aws_ses_configuration_set.bulk.name
}

# Production-live marker. Seeded "false" (pre-live): data-replacing deploys
# are permitted and a test-mode Stripe key is accepted. Flipping it to "true"
# is a named go-live runbook step performed with an operator put-parameter;
# from then on the full-refresh deploy is forbidden permanently and test-mode
# Stripe keys are refused. Every data-replacing path requires an exact "false"
# read and refuses on anything else (missing, unreadable, any other value),
# fail closed. ignore_changes because the flip is out-of-band and deliberately
# one-way: a later apply must never silently revert a live production to
# pre-live and re-arm the destructive deploy paths.
resource "aws_ssm_parameter" "app_production_live" {
  name  = "${local.ssm_prefix}/app/production_live"
  type  = "String"
  value = "false"
  lifecycle { ignore_changes = [value] }
}

# The site's own public address is deliberately not a parameter. It is set on the
# host env file, which the application reads at startup, and the deploy syncs an
# explicit list of keys from Parameter Store that does not include it. A parameter
# nothing reads is state that can silently disagree with the running value, and
# this one did: it was seeded with the bare apex while the canonical host is www.

resource "aws_ssm_parameter" "app_db_path" {
  name = "${local.ssm_prefix}/app/db_path"
  type = "String"
  # /srv/footbag/db/footbag.db matches the host bind mount declared in
  # docker/docker-compose.prod.yml. The earlier value (/srv/footbag/footbag.db)
  # predated the directory-mount migration and would cause the app to look
  # for the database outside the container's mounted directory on first
  # boot, crash-looping the stack. Staging carries the same corrected value
  # in terraform/staging/ssm.tf.
  value = "/srv/footbag/db/footbag.db"
  # Operators may switch the path on the host during a maintenance window;
  # terraform re-apply must not clobber that change without explicit intent.
  lifecycle { ignore_changes = [value] }
}

# Origin-bypass secret. CloudFront injects this as X-Origin-Verify; nginx
# rejects (444) any direct-to-origin request where the header is missing or
# wrong. The value is generated by random_id below (64 hex chars; matches the
# shape check in docker/nginx/40-render-nginx-conf.sh). Production value is
# distinct from staging because each environment generates its own random_id.
#
# Rotation: `terraform apply -replace=random_id.origin_verify_secret` regenerates
# the value, the SSM parameter updates, the next deploy fetches the new value
# from SSM and rewrites X_ORIGIN_VERIFY_SECRET in /srv/footbag/env on the host.
# CloudFront re-reads via the data-source on the same apply.
#
# No ignore_changes: Terraform owns the canonical value. Manual
# `aws ssm put-parameter --overwrite` would be reverted on the next apply.
resource "random_id" "origin_verify_secret" {
  byte_length = 32
}

resource "aws_ssm_parameter" "origin_verify_secret" {
  name   = "${local.ssm_prefix}/secrets/origin_verify_secret"
  type   = "SecureString"
  key_id = aws_kms_alias.main.name
  value  = random_id.origin_verify_secret.hex
}

data "aws_ssm_parameter" "origin_verify_secret" {
  name            = aws_ssm_parameter.origin_verify_secret.name
  with_decryption = true
}

# ── Safe Browsing v4 API key (operator-supplied) ─────────────────────────────
# SecureString + KMS-encrypted. Terraform owns the resource shell with a TODO
# placeholder; the real value is operator-supplied, under operator credentials —
# the app runtime role is deliberately read-only on SSM and cannot PutParameter:
#   aws ssm put-parameter \
#     --name "/footbag/production/secrets/safe_browsing_api_key" \
#     --value "file:///tmp/sb-key" --type SecureString \
#     --key-id alias/footbag-production --overwrite
# (file:// hygiene keeps the literal value out of shell history and process
# listings.)
# `lifecycle { ignore_changes = [value] }` because Terraform never owns the
# real value, only the resource existence + KMS reference. The runtime live
# SecretsAdapter reads it lazily on first SafeBrowsing lookup. The TODO
# placeholder string is rejected by the live adapter so a deploy without the
# put-parameter step fails loudly, not silently.
resource "aws_ssm_parameter" "safe_browsing_api_key" {
  name   = "${local.ssm_prefix}/secrets/safe_browsing_api_key"
  type   = "SecureString"
  key_id = aws_kms_alias.main.name
  value  = "TODO-set-via-cli-after-apply"
  lifecycle { ignore_changes = [value] }
}

# ── SESSION_SECRET (cookie-parser signing + env.ts boot-time check) ──────────
# Terraform owns the canonical value via random_id below (32 bytes → 64 hex
# chars, well past the env.ts ≥32 floor and never matches 'changeme'). The
# deploy script (scripts/internal/deploy-{rebuild,code}-remote.sh) fetches
# this parameter on every deploy and writes it into /srv/footbag/env, where
# systemd picks it up and Docker Compose forwards it into each container.
#
# Mirrors the origin_verify_secret pattern below for the same reasons:
# Terraform-as-single-source-of-truth, no operator put-parameter step
# required at first apply, rotation is `terraform apply -replace=
# random_id.session_secret` followed by any subsequent deploy. A manual
# `aws ssm put-parameter --overwrite` would be reverted on the next
# terraform apply; the value is not operator-overridable by design.
#
# No `ignore_changes`: Terraform IS the writer. Any out-of-band drift
# (operator put-parameter, console edit) is undone on next apply, which
# is the intended posture for this secret.
resource "random_id" "session_secret" {
  byte_length = 32
}

resource "aws_ssm_parameter" "app_session_secret" {
  name   = "${local.ssm_prefix}/secrets/session_secret"
  type   = "SecureString"
  key_id = aws_kms_alias.main.name
  value  = random_id.session_secret.hex
}

data "aws_ssm_parameter" "app_session_secret" {
  name            = aws_ssm_parameter.app_session_secret.name
  with_decryption = true
}

# ── Stripe secret API key (operator-supplied) ─────────────────────────────────
# Same shell-with-placeholder pattern as safe_browsing_api_key above: Terraform
# owns the resource existence + KMS reference, the operator supplies the real
# live-mode key via put-parameter, and the live payment adapter rejects the
# TODO placeholder so a deploy without the put-parameter step fails the first
# checkout loudly, not silently. Path is under /secrets/ because the runtime
# SecretsAdapter resolves "${local.ssm_prefix}/secrets/<key>".
resource "aws_ssm_parameter" "stripe_secret_key" {
  name   = "${local.ssm_prefix}/secrets/stripe_secret_key"
  type   = "SecureString"
  key_id = aws_kms_alias.main.name
  value  = "TODO-set-via-cli-after-apply"
  lifecycle { ignore_changes = [value] }
}

# ── Stripe webhook signing secret (operator-supplied) ────────────────────────
# Same shell-with-placeholder pattern. A real value here is authoritative: the
# deploy sync writes it into the host env on every run, so the secret is never
# hand-pasted onto a host and the running value always has a declared source.
# While the value is the TODO placeholder the sync leaves any existing host
# value untouched rather than clearing it, so a secret installed by the
# payments activation script survives deploys; clearing it would strip the only
# copy from a host and refuse the next live-payment boot. The _previous twin
# holds the outgoing secret during a Stripe secret roll (Stripe signs with both
# for the roll window) and returns to the placeholder when the roll completes.
resource "aws_ssm_parameter" "stripe_webhook_secret" {
  name   = "${local.ssm_prefix}/secrets/stripe_webhook_secret"
  type   = "SecureString"
  key_id = aws_kms_alias.main.name
  value  = "TODO-set-via-cli-after-apply"
  lifecycle { ignore_changes = [value] }
}

resource "aws_ssm_parameter" "stripe_webhook_secret_previous" {
  name   = "${local.ssm_prefix}/secrets/stripe_webhook_secret_previous"
  type   = "SecureString"
  key_id = aws_kms_alias.main.name
  value  = "TODO-set-via-cli-after-apply"
  lifecycle { ignore_changes = [value] }
}

# ── Cloudflare Turnstile secret key (operator-supplied) ──────────────────────
# Same shell-with-placeholder pattern. The production boot mandates the live
# CAPTCHA adapter, whose server-side verification needs this secret; the
# operator supplies the value from the Cloudflare dashboard via put-parameter.
resource "aws_ssm_parameter" "turnstile_secret_key" {
  name   = "${local.ssm_prefix}/secrets/turnstile_secret_key"
  type   = "SecureString"
  key_id = aws_kms_alias.main.name
  value  = "TODO-set-via-cli-after-apply"
  lifecycle { ignore_changes = [value] }
}

# ── SES (placeholder — email deferred) ───────────────────────────────────────
# resource "aws_ssm_parameter" "ses_sender" {
#   name   = "${local.ssm_prefix}/ses/sender_address"
#   type   = "SecureString"
#   key_id = aws_kms_key.main.arn
#   value  = "TODO-noreply@footbag.org"
#   lifecycle { ignore_changes = [value] }
# }
