import { describe, it, expect, beforeAll, afterAll, afterEach, beforeEach } from 'vitest';
import { expectLoggedError } from '../setup-env';
import request from '../fixtures/supertestWithOrigin';
import BetterSqlite3 from 'better-sqlite3';

import { setTestEnv, createTestDb, cleanupTestDb, importApp } from '../fixtures/testDb';
import { insertMember, createTestSessionJwt } from '../fixtures/factories';

const { dbPath } = setTestEnv('3130');

const ADMIN_ID    = 'wq_admin_001';
const ADMIN_SLUG  = 'wq_admin_one';
const MEMBER_ID   = 'wq_member_001';
const MEMBER_SLUG = 'wq_member_one';
const OTHER_ID    = 'wq_member_002';

let createApp: Awaited<ReturnType<typeof importApp>>;

function adminCookie(): string {
  return `footbag_session=${createTestSessionJwt({ memberId: ADMIN_ID, role: 'admin' })}`;
}
function memberCookie(): string {
  return `footbag_session=${createTestSessionJwt({ memberId: MEMBER_ID })}`;
}

beforeAll(async () => {
  const db = createTestDb(dbPath);
  insertMember(db, { id: ADMIN_ID,  slug: ADMIN_SLUG,  display_name: 'WQ Admin',    real_name: 'WQ Admin',    login_email: 'wq-admin@example.com',  is_admin: 1 });
  insertMember(db, { id: MEMBER_ID, slug: MEMBER_SLUG, display_name: 'WQ Member',   real_name: 'WQ Member',   login_email: 'wq-member@example.com' });
  insertMember(db, { id: OTHER_ID,  slug: 'wq_other',  display_name: 'WQ Other',    real_name: 'WQ Other',    login_email: 'wq-other@example.com' });
  db.close();
  createApp = await importApp();
});

afterAll(() => cleanupTestDb(dbPath));

beforeEach(() => {
  const db = new BetterSqlite3(dbPath);
  db.prepare(`DELETE FROM work_queue_items`).run();
  db.close();
});

function seedOpenContactRequest(memberId: string, message = 'please fix my name'): string {
  // Use the public POST surface so the row goes through the canonical service
  // path (validation, audit, etc.). The admin-resolve tests below then act
  // on the resulting work_queue_items row.
  return memberId; // placeholder; the actual id is generated by the service.
}

async function postOneOpenRequest(app: import('express').Express, memberId: string, memberSlug: string): Promise<string> {
  // Submit via the public form to get a real queue row + audit row.
  await request(app)
    .post(`/members/${memberSlug}/contact-admin`)
    .set('Cookie', `footbag_session=${createTestSessionJwt({ memberId })}`)
    .type('form')
    .send({ category: 'display_name_correction', message: 'please fix my name' });
  const db = new BetterSqlite3(dbPath);
  const row = db
    .prepare(`SELECT id FROM work_queue_items WHERE entity_id = ? AND status = 'open'`)
    .get(memberId) as { id: string } | undefined;
  db.close();
  return row!.id;
}

describe('GET /admin/work-queue', () => {
  it('unauthenticated → 302 to /login with returnTo', async () => {
    const app = createApp();
    const res = await request(app).get('/admin/work-queue');
    expect(res.status).toBe(302);
    expect(res.headers.location).toMatch(/^\/login/);
  });

  it('non-admin → 403', async () => {
    const app = createApp();
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', memberCookie());
    expect(res.status).toBe(403);
  });

  it('admin, no open items → 200 with empty-state message', async () => {
    const app = createApp();
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Admin Work Queue');
    expect(res.text).toContain('No open work-queue items');
  });

  it('admin, with one open contact request → 200 listing the item under Membership', async () => {
    const app = createApp();
    await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Membership');
    expect(res.text).toContain('Member contact request');
    expect(res.text).toContain('Display name correction');
    expect(res.text).toContain(`href="/members/${MEMBER_SLUG}"`);
  });
});

describe('POST /admin/work-queue/:id/resolve', () => {
  it('admin resolves → 303 + queue row resolved + audit + email enqueued via outbox', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'Fixed your display name.' });
    expect(res.status).toBe(303);
    expect(res.headers.location).toBe('/admin/work-queue');

    const db = new BetterSqlite3(dbPath);
    const row = db
      .prepare(`SELECT status, decision_label, reason_text, resolved_by_member_id FROM work_queue_items WHERE id = ?`)
      .get(queueId) as Record<string, unknown> | undefined;
    expect(row).toBeDefined();
    expect(row!.status).toBe('resolved');
    expect(row!.decision_label).toBe('corrected');
    expect(row!.resolved_by_member_id).toBe(ADMIN_ID);

    const audit = db
      .prepare(`SELECT action_type, actor_type FROM audit_entries WHERE action_type = 'support.contact_request_resolved' AND entity_id = ?`)
      .get(MEMBER_ID) as Record<string, unknown> | undefined;
    expect(audit).toBeDefined();
    expect(audit!.actor_type).toBe('admin');

    // Services enqueue notification emails via the outbox table; the SES
    // adapter is never called directly from a service or controller.
    const outboxRow = db
      .prepare(`SELECT recipient_email, subject, body_text, idempotency_key FROM outbox_emails WHERE recipient_member_id = ? AND idempotency_key LIKE 'contact-request-resolve:%' ORDER BY created_at DESC LIMIT 1`)
      .get(MEMBER_ID) as
        | { recipient_email: string; subject: string; body_text: string; idempotency_key: string }
        | undefined;
    expect(outboxRow).toBeDefined();
    expect(outboxRow!.recipient_email).toBe('wq-member@example.com');
    expect(outboxRow!.subject).toContain('Corrected');
    expect(outboxRow!.body_text).toContain('Fixed your display name.');
    expect(outboxRow!.idempotency_key).toBe(`contact-request-resolve:${queueId}`);
    db.close();
  });

  it('invalid decision_label → 422', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'bogus', resolution_note: 'note' });
    expect(res.status).toBe(422);
    expect(res.text).toContain('Invalid decision label');
  });

  it('empty resolution_note → 422', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'denied', resolution_note: '   ' });
    expect(res.status).toBe(422);
    expect(res.text).toContain('Resolution note is required');
  });

  it('unknown queue id → 404', async () => {
    const app = createApp();
    const res = await request(app)
      .post(`/admin/work-queue/wq_does_not_exist/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'ok' });
    expect(res.status).toBe(404);
  });

  it('non-admin POST → 403', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', memberCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'ok' });
    expect(res.status).toBe(403);
  });

  // Regression for B15: resolve-notification email was sent via the plain
  // enqueueEmail helper which silently swallows outbox write failures. After
  // R4-pattern migration to enqueueEmailOrFail, an outbox failure surfaces
  // as a truthful 503. The queue row stays resolved + the audit row stays
  // written (both committed inside the resolve transaction before the
  // enqueue runs, per B10 fix); the operator sees a 503 banner driven by
  // handleControllerError's ServiceUnavailableError → 503 mapping.
  describe('enqueueEmailOrFail failure on resolve', () => {
    // eslint-disable-next-line @typescript-eslint/consistent-type-imports
    let commsMod: typeof import('../../src/services/communicationService');

    beforeAll(async () => {
      commsMod = await import('../../src/services/communicationService');
    });

    afterEach(() => {
      commsMod.resetCommunicationServiceForTests();
    });

    it('enqueueEmailOrFail throws → 503 + queue resolved + audit row + notification_failed audit + no outbox row', async () => {
      expectLoggedError('audit: support.contact_request_resolve_notification_failed');
      const app = createApp();
      const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

      // Break enqueueEmailOrFail only; leave enqueueMailingListEmail / plain
      // enqueueEmail intact so the submit path that already ran isn't
      // implicated.
      const { ServiceUnavailableError } = await import('../../src/services/serviceErrors');
      commsMod.setCommunicationServiceForTests({
        enqueueEmail: () => undefined,
        enqueueEmailOrFail: () => {
          throw new ServiceUnavailableError(
            'synthetic enqueueEmailOrFail failure for contact-request-resolve',
          );
        },
        enqueueMailingListEmail: () => ({ enqueued: 0, duplicates: 0 }),
        processSendQueue: async () => ({
          claimed: 0, sent: 0, failed: 0, deadLettered: 0, paused: false,
        }),
      });

      const res = await request(app)
        .post(`/admin/work-queue/${queueId}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'Fixed your display name.' });
      expect(res.status).toBe(503);

      const db = new BetterSqlite3(dbPath);
      try {
        // Queue row resolved despite the enqueue failure (mutation committed
        // before the strict enqueue ran).
        const queueRow = db
          .prepare(`SELECT status, decision_label FROM work_queue_items WHERE id = ?`)
          .get(queueId) as { status: string; decision_label: string } | undefined;
        expect(queueRow).toBeDefined();
        expect(queueRow!.status).toBe('resolved');

        // Audit row written inside the same transaction as the resolve.
        const resolvedAudit = db
          .prepare(`SELECT id FROM audit_entries WHERE action_type = 'support.contact_request_resolved' AND entity_id = ?`)
          .get(MEMBER_ID) as { id: string } | undefined;
        expect(resolvedAudit).toBeDefined();

        // R4 operational-error audit row: persistent forensic record paired
        // with the logger.error marker so operators can triage outbox / SES
        // degradation.
        const failedAudit = db
          .prepare(`SELECT id FROM audit_entries WHERE action_type = 'support.contact_request_resolve_notification_failed' AND entity_id = ?`)
          .get(MEMBER_ID) as { id: string } | undefined;
        expect(failedAudit).toBeDefined();

        // No outbox row for the resolve-notification: the strict enqueue
        // threw before any outbox row could land.
        const outbox = db
          .prepare(`SELECT id FROM outbox_emails WHERE idempotency_key = ?`)
          .get(`contact-request-resolve:${queueId}`) as { id: string } | undefined;
        expect(outbox).toBeUndefined();
      } finally {
        db.close();
      }
    });

    it('member with no email address skips the enqueue entirely → 303 + no outbox row', async () => {
      // Defensive regression: if member.login_email is empty, resolve must
      // not attempt the enqueue (no synthetic 503 from a missing recipient).
      const db = new BetterSqlite3(dbPath);
      db.prepare(`UPDATE members SET login_email = '', login_email_normalized = '' WHERE id = ?`).run(MEMBER_ID);
      db.close();
      try {
        const app = createApp();
        const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

        // Pre-arm a faulty enqueueEmailOrFail; if resolve calls it, the test
        // fails because the enqueue would throw. The empty-email guard
        // skips the call entirely.
        const { ServiceUnavailableError } = await import('../../src/services/serviceErrors');
        commsMod.setCommunicationServiceForTests({
          enqueueEmail: () => undefined,
          enqueueEmailOrFail: () => {
            throw new ServiceUnavailableError('should not be called when member has no email');
          },
          enqueueMailingListEmail: () => ({ enqueued: 0, duplicates: 0 }),
          processSendQueue: async () => ({
            claimed: 0, sent: 0, failed: 0, deadLettered: 0, paused: false,
          }),
        });

        const res = await request(app)
          .post(`/admin/work-queue/${queueId}/resolve`)
          .set('Cookie', adminCookie())
          .type('form')
          .send({ decision_label: 'corrected', resolution_note: 'ok' });
        expect(res.status).toBe(303);
      } finally {
        // Restore the member's email for later tests in the file.
        const restore = new BetterSqlite3(dbPath);
        restore.prepare(`UPDATE members SET login_email = ?, login_email_normalized = ? WHERE id = ?`)
          .run('wq-member@example.com', 'wq-member@example.com', MEMBER_ID);
        restore.close();
      }
    });
  });

  // Regression for B18: work-queue resolve was unlimited per admin session.
  // A compromised admin could resolve many items rapidly before detection.
  // The limit applies to admins (compromised-admin is the threat model).
  it('admin exceeding work-queue-resolve rate-limit → 429 with Retry-After', async () => {
    const rlMod = await import('../../src/services/rateLimitService');
    rlMod.resetRateLimitForTests();
    const tuneDb = new BetterSqlite3(dbPath);
    tuneDb.prepare(`
      INSERT INTO system_config
        (id, created_at, config_key, value_json, effective_start_at, reason_text, changed_by_member_id)
      VALUES (?, ?, 'work_queue_resolve_rate_limit_per_hour', '2', ?, 'Test tunable', NULL)
    `).run('test-wq-resolve-rl', '2026-05-22T00:00:00.000Z', '2026-05-22T00:00:00.000Z');
    tuneDb.close();
    try {
      const app = createApp();
      const q1 = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
      // postOneOpenRequest may submit, but the resolve bucket is independent.
      // Reset after the open-request seeding to be safe.
      rlMod.resetRateLimitForTests();

      const r1 = await request(app)
        .post(`/admin/work-queue/${q1}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'ok 1' });
      expect(r1.status).toBe(303);

      // Need a fresh open queue row to resolve next; reuse fixture creator.
      const q2 = await postOneOpenRequest(app, OTHER_ID, 'wq_other');
      const r2 = await request(app)
        .post(`/admin/work-queue/${q2}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'ok 2' });
      expect(r2.status).toBe(303);

      // Third resolve attempt - any id, even bogus, should 429 before
      // reaching the service since the bucket is exhausted.
      const blocked = await request(app)
        .post(`/admin/work-queue/wq_anything/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'blocked' });
      expect(blocked.status).toBe(429);
      expect(blocked.headers['retry-after']).toBeDefined();
    } finally {
      rlMod.resetRateLimitForTests();
    }
  });
});
