import { describe, it, expect, beforeAll, afterAll, afterEach, beforeEach } from 'vitest';
import { expectLoggedError } from '../setup-env';
import request from '../fixtures/supertestWithOrigin';
import BetterSqlite3 from 'better-sqlite3';

import { setTestEnv, createTestDb, cleanupTestDb, importApp } from '../fixtures/testDb';
import { insertMember, createTestSessionJwt } from '../fixtures/factories';

const { dbPath } = setTestEnv('3130');

const ADMIN_ID    = 'wq_admin_001';
const ADMIN_SLUG  = 'wq_admin_one';
const ADMIN2_ID   = 'wq_admin_002';
const MEMBER_ID   = 'wq_member_001';
const MEMBER_SLUG = 'wq_member_one';
const OTHER_ID    = 'wq_member_002';

let createApp: Awaited<ReturnType<typeof importApp>>;

function adminCookie(): string {
  return `__Host-footbag_session=${createTestSessionJwt({ memberId: ADMIN_ID, role: 'admin' })}`;
}
function admin2Cookie(): string {
  return `__Host-footbag_session=${createTestSessionJwt({ memberId: ADMIN2_ID, role: 'admin' })}`;
}
function memberCookie(): string {
  return `__Host-footbag_session=${createTestSessionJwt({ memberId: MEMBER_ID })}`;
}

beforeAll(async () => {
  const db = createTestDb(dbPath);
  insertMember(db, { id: ADMIN_ID,  slug: ADMIN_SLUG,  display_name: 'WQ Admin',    real_name: 'WQ Admin',    login_email: 'wq-admin@example.com',  is_admin: 1 });
  insertMember(db, { id: ADMIN2_ID, slug: 'wq_admin_two', display_name: 'WQ Admin Two', real_name: 'WQ Admin Two', login_email: 'wq-admin2@example.com', is_admin: 1 });
  insertMember(db, { id: MEMBER_ID, slug: MEMBER_SLUG, display_name: 'WQ Member',   real_name: 'WQ Member',   login_email: 'wq-member@example.com' });
  insertMember(db, { id: OTHER_ID,  slug: 'wq_other',  display_name: 'WQ Other',    real_name: 'WQ Other',    login_email: 'wq-other@example.com' });
  db.close();
  createApp = await importApp();
});

afterAll(() => cleanupTestDb(dbPath));

beforeEach(() => {
  const db = new BetterSqlite3(dbPath);
  db.prepare(`DELETE FROM work_queue_items`).run();
  db.close();
});

function seedOpenContactRequest(memberId: string, message = 'please fix my name'): string {
  // Use the public POST surface so the row goes through the canonical service
  // path (validation, audit, etc.). The admin-resolve tests below then act
  // on the resulting work_queue_items row.
  return memberId; // placeholder; the actual id is generated by the service.
}

async function postOneOpenRequest(app: import('express').Express, memberId: string, memberSlug: string): Promise<string> {
  // Submit via the public form to get a real queue row + audit row.
  await request(app)
    .post(`/members/${memberSlug}/contact-admin`)
    .set('Cookie', `__Host-footbag_session=${createTestSessionJwt({ memberId })}`)
    .type('form')
    .send({ category: 'display_name_correction', message: 'please fix my name' });
  const db = new BetterSqlite3(dbPath);
  const row = db
    .prepare(`SELECT id FROM work_queue_items WHERE entity_id = ? AND status = 'open'`)
    .get(memberId) as { id: string } | undefined;
  db.close();
  return row!.id;
}

describe('GET /admin/work-queue', () => {
  it('unauthenticated → 302 to /login with returnTo', async () => {
    const app = createApp();
    const res = await request(app).get('/admin/work-queue');
    expect(res.status).toBe(302);
    expect(res.headers.location).toMatch(/^\/login/);
  });

  it('non-admin → 403', async () => {
    const app = createApp();
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', memberCookie());
    expect(res.status).toBe(403);
  });

  it('admin, no open items → 200 with empty-state message', async () => {
    const app = createApp();
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Admin Work Queue');
    expect(res.text).toContain('No open work-queue items');
  });

  it('admin, with one open contact request → 200 listing the item under Membership', async () => {
    const app = createApp();
    await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Membership');
    expect(res.text).toContain('Member contact request');
    expect(res.text).toContain('Display name correction');
    expect(res.text).toContain(`href="/members/${MEMBER_SLUG}"`);
  });

  it('shows the full member message body, untruncated', async () => {
    const app = createApp();
    const longMsg = 'C'.repeat(450);
    await request(app)
      .post(`/members/${MEMBER_SLUG}/contact-admin`)
      .set('Cookie', memberCookie())
      .type('form')
      .send({ category: 'display_name_correction', message: longMsg });
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain(longMsg);
  });
});

describe('POST /admin/work-queue/:id/claim', () => {
  it('an unclaimed item shows a Claim button; claiming it → 303 and the page shows "Claimed by you"', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

    const before = await request(app).get('/admin/work-queue').set('Cookie', adminCookie());
    expect(before.text).toContain(`/admin/work-queue/${queueId}/claim`);

    const claim = await request(app)
      .post(`/admin/work-queue/${queueId}/claim`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({});
    expect(claim.status).toBe(303);
    expect(claim.headers.location).toBe('/admin/work-queue');

    const db = new BetterSqlite3(dbPath);
    const row = db.prepare(`SELECT claimed_by_member_id FROM work_queue_items WHERE id = ?`).get(queueId) as Record<string, unknown>;
    db.close();
    expect(row.claimed_by_member_id).toBe(ADMIN_ID);

    const after = await request(app).get('/admin/work-queue').set('Cookie', adminCookie());
    expect(after.text).toContain('Claimed by you.');
    // The claim control is gone once the item is claimed.
    expect(after.text).not.toContain(`/admin/work-queue/${queueId}/claim`);
  });

  it('another admin sees the claim by name and cannot steal it (no-op claim)', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    await request(app).post(`/admin/work-queue/${queueId}/claim`).set('Cookie', adminCookie()).type('form').send({});

    // A second admin's queue view names the claimer rather than offering a Claim button.
    const view = await request(app).get('/admin/work-queue').set('Cookie', admin2Cookie());
    expect(view.text).toContain('Claimed by WQ Admin.');

    // A second claim is a harmless no-op; the original claimer is unchanged.
    const steal = await request(app).post(`/admin/work-queue/${queueId}/claim`).set('Cookie', admin2Cookie()).type('form').send({});
    expect(steal.status).toBe(303);
    const db = new BetterSqlite3(dbPath);
    const row = db.prepare(`SELECT claimed_by_member_id FROM work_queue_items WHERE id = ?`).get(queueId) as Record<string, unknown>;
    db.close();
    expect(row.claimed_by_member_id).toBe(ADMIN_ID);
  });

  it('non-admin POST → 403', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app).post(`/admin/work-queue/${queueId}/claim`).set('Cookie', memberCookie()).type('form').send({});
    expect(res.status).toBe(403);
  });

  // An administrator can disable any template from the template editor. The send
  // then reports suppression instead of throwing, and telling the administrator
  // the member was notified sends them away believing the request is closed on
  // both sides when nothing was ever enqueued.
  it('says the item was resolved, not that the member was told, when the reply template is disabled', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const db = new BetterSqlite3(dbPath);
    db.prepare(`UPDATE email_templates SET is_enabled = 0 WHERE template_key = 'contact_request_resolution'`).run();
    db.close();

    const resolve = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'Handled out of band.' });
    expect(resolve.status).toBe(303);

    const flashCookie = ((resolve.headers['set-cookie'] as unknown as string[]) ?? [])
      .map((c) => c.split(';')[0])
      .join('; ');
    const page = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', [adminCookie(), flashCookie].filter(Boolean).join('; '));
    expect(page.text).toContain('Item resolved.');
    expect(page.text).not.toContain('email reply dispatched');

    const check = new BetterSqlite3(dbPath);
    check.prepare(`UPDATE email_templates SET is_enabled = 1 WHERE template_key = 'contact_request_resolution'`).run();
    check.close();
  });

  it('claiming an unknown id is a harmless no-op → 303', async () => {
    const app = createApp();
    const res = await request(app).post(`/admin/work-queue/wq_no_such_item/claim`).set('Cookie', adminCookie()).type('form').send({});
    expect(res.status).toBe(303);
  });
});

describe('POST /admin/work-queue/:id/resolve', () => {
  it('admin resolves → 303 + queue row resolved + audit + email enqueued via outbox', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'Fixed your display name.' });
    expect(res.status).toBe(303);
    expect(res.headers.location).toBe('/admin/work-queue');

    const db = new BetterSqlite3(dbPath);
    const row = db
      .prepare(`SELECT status, decision_label, reason_text, resolved_by_member_id FROM work_queue_items WHERE id = ?`)
      .get(queueId) as Record<string, unknown> | undefined;
    expect(row).toBeDefined();
    expect(row!.status).toBe('resolved');
    expect(row!.decision_label).toBe('corrected');
    expect(row!.resolved_by_member_id).toBe(ADMIN_ID);

    const audit = db
      .prepare(`SELECT action_type, actor_type, metadata_json FROM audit_entries WHERE action_type = 'support.contact_request_resolved' AND entity_id = ?`)
      .get(MEMBER_ID) as Record<string, unknown> | undefined;
    expect(audit).toBeDefined();
    expect(audit!.actor_type).toBe('admin');
    // The append-only ledger is exempt from PII purge, so the member's
    // free-text message must never be copied into resolution metadata.
    expect(String(audit!.metadata_json)).not.toContain('please fix my name');
    // Nor the administrator's note. It is free text written about a member and
    // is held in the purgeable work-queue row, which erasure can reach; a copy
    // in the ledger would outlive that erasure. The decision survives instead.
    expect(String(audit!.metadata_json)).not.toContain('Fixed your display name.');
    expect(String(audit!.metadata_json)).toContain('corrected');
    // The operational copy is still there for an administrator to read.
    expect(row!.reason_text).toBeDefined();

    // Services enqueue notification emails via the outbox table; the SES
    // adapter is never called directly from a service or controller.
    const outboxRow = db
      .prepare(`SELECT recipient_email, subject, body_text, idempotency_key FROM outbox_emails WHERE recipient_member_id = ? AND idempotency_key LIKE 'contact-request-resolve:%' ORDER BY created_at DESC LIMIT 1`)
      .get(MEMBER_ID) as
        | { recipient_email: string; subject: string; body_text: string; idempotency_key: string }
        | undefined;
    expect(outboxRow).toBeDefined();
    expect(outboxRow!.recipient_email).toBe('wq-member@example.com');
    expect(outboxRow!.subject).toContain('Corrected');
    expect(outboxRow!.body_text).toContain('Fixed your display name.');
    // Best practice: the templated resolution email does not echo the member's
    // own message back; their free text stays in the operational store only.
    expect(outboxRow!.body_text).not.toContain('please fix my name');
    expect(outboxRow!.idempotency_key).toBe(`contact-request-resolve:${queueId}`);
    db.close();
  });

  it('invalid decision_label → 422', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'bogus', resolution_note: 'note' });
    expect(res.status).toBe(422);
    expect(res.text).toContain('Invalid decision label');
  });

  it('empty resolution_note → 422', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'denied', resolution_note: '   ' });
    expect(res.status).toBe(422);
    expect(res.text).toContain('Resolution note is required');
  });

  it('resolution_note longer than 500 chars → 422', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'denied', resolution_note: 'a'.repeat(501) });
    expect(res.status).toBe(422);
  });

  it('unknown queue id → 404', async () => {
    const app = createApp();
    const res = await request(app)
      .post(`/admin/work-queue/wq_does_not_exist/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'ok' });
    expect(res.status).toBe(404);
  });

  // Anti-enumeration: resolving an already-resolved item returns 404, the same
  // status (and body) an unknown id returns, so a caller cannot tell "already
  // handled" apart from "never existed". The service guard requires
  // status === 'open' (adminWorkQueueService), mapping non-open rows to
  // NotFoundError → 404.
  it('already-resolved id → 404, indistinguishable from an unknown id', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

    const first = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'Fixed it.' });
    expect(first.status).toBe(303);

    const second = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'again' });
    expect(second.status).toBe(404);

    const unknown = await request(app)
      .post(`/admin/work-queue/wq_never_existed_zz/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'again' });
    expect(unknown.status).toBe(404);

    // Same not-found body for both: no existence leak.
    expect(second.text).toBe(unknown.text);
  });

  it('non-admin POST → 403', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', memberCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'ok' });
    expect(res.status).toBe(403);
  });

  // Resolve-notification email was sent via the plain
  // enqueueEmail helper which silently swallows outbox write failures. After
  // R4-pattern migration to enqueueEmailOrFail, an outbox failure surfaces
  // as a truthful 503. The queue row stays resolved + the audit row stays
  // written (both committed inside the resolve transaction before the
  // enqueue runs); the operator sees a 503 banner driven by
  // handleControllerError's ServiceUnavailableError → 503 mapping.
  describe('enqueueEmailOrFail failure on resolve', () => {
    // eslint-disable-next-line @typescript-eslint/consistent-type-imports
    let commsMod: typeof import('../../src/services/communicationService');

    beforeAll(async () => {
      commsMod = await import('../../src/services/communicationService');
    });

    afterEach(() => {
      commsMod.resetCommunicationServiceForTests();
    });

    it('enqueueEmailOrFail throws → 503 + queue resolved + audit row + notification_failed audit + no outbox row', async () => {
      expectLoggedError('audit: support.contact_request_resolve_notification_failed');
      const app = createApp();
      const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

      // Break enqueueEmailOrFail only; leave enqueueMailingListEmail / plain
      // enqueueEmail intact so the submit path that already ran isn't
      // implicated.
      const { ServiceUnavailableError } = await import('../../src/services/serviceErrors');
      commsMod.setCommunicationServiceForTests({
        enqueueEmail: () => undefined,
        enqueueEmailOrFail: () => {
          throw new ServiceUnavailableError(
            'synthetic enqueueEmailOrFail failure for contact-request-resolve',
          );
        },
        enqueueMailingListEmail: () => ({ enqueued: 0, duplicates: 0 }),
        processSendQueue: async () => ({
          claimed: 0, sent: 0, failed: 0, deadLettered: 0, paused: false,
        }),
      });

      const res = await request(app)
        .post(`/admin/work-queue/${queueId}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'Fixed your display name.' });
      expect(res.status).toBe(503);

      const db = new BetterSqlite3(dbPath);
      try {
        // Queue row resolved despite the enqueue failure (mutation committed
        // before the strict enqueue ran).
        const queueRow = db
          .prepare(`SELECT status, decision_label FROM work_queue_items WHERE id = ?`)
          .get(queueId) as { status: string; decision_label: string } | undefined;
        expect(queueRow).toBeDefined();
        expect(queueRow!.status).toBe('resolved');

        // Audit row written inside the same transaction as the resolve.
        const resolvedAudit = db
          .prepare(`SELECT id FROM audit_entries WHERE action_type = 'support.contact_request_resolved' AND entity_id = ?`)
          .get(MEMBER_ID) as { id: string } | undefined;
        expect(resolvedAudit).toBeDefined();

        // R4 operational-error audit row: persistent forensic record paired
        // with the logger.error marker so operators can triage outbox / SES
        // degradation.
        const failedAudit = db
          .prepare(`SELECT id FROM audit_entries WHERE action_type = 'support.contact_request_resolve_notification_failed' AND entity_id = ?`)
          .get(MEMBER_ID) as { id: string } | undefined;
        expect(failedAudit).toBeDefined();

        // No outbox row for the resolve-notification: the strict enqueue
        // threw before any outbox row could land.
        const outbox = db
          .prepare(`SELECT id FROM outbox_emails WHERE idempotency_key = ?`)
          .get(`contact-request-resolve:${queueId}`) as { id: string } | undefined;
        expect(outbox).toBeUndefined();
      } finally {
        db.close();
      }
    });

    it('member with no email address skips the enqueue entirely → 303 + no outbox row', async () => {
      // Defensive regression: if member.login_email is empty, resolve must
      // not attempt the enqueue (no synthetic 503 from a missing recipient).
      const db = new BetterSqlite3(dbPath);
      db.prepare(`UPDATE members SET login_email = '', login_email_normalized = '' WHERE id = ?`).run(MEMBER_ID);
      db.close();
      try {
        const app = createApp();
        const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

        // Pre-arm a faulty enqueueEmailOrFail; if resolve calls it, the test
        // fails because the enqueue would throw. The empty-email guard
        // skips the call entirely.
        const { ServiceUnavailableError } = await import('../../src/services/serviceErrors');
        commsMod.setCommunicationServiceForTests({
          enqueueEmail: () => undefined,
          enqueueEmailOrFail: () => {
            throw new ServiceUnavailableError('should not be called when member has no email');
          },
          enqueueMailingListEmail: () => ({ enqueued: 0, duplicates: 0 }),
          processSendQueue: async () => ({
            claimed: 0, sent: 0, failed: 0, deadLettered: 0, paused: false,
          }),
        });

        const res = await request(app)
          .post(`/admin/work-queue/${queueId}/resolve`)
          .set('Cookie', adminCookie())
          .type('form')
          .send({ decision_label: 'corrected', resolution_note: 'ok' });
        expect(res.status).toBe(303);
      } finally {
        // Restore the member's email for later tests in the file.
        const restore = new BetterSqlite3(dbPath);
        restore.prepare(`UPDATE members SET login_email = ?, login_email_normalized = ? WHERE id = ?`)
          .run('wq-member@example.com', 'wq-member@example.com', MEMBER_ID);
        restore.close();
      }
    });
  });

  // Work-queue resolve was unlimited per admin session.
  // A compromised admin could resolve many items rapidly before detection.
  // The limit applies to admins (compromised-admin is the threat model).
  it('admin exceeding work-queue-resolve rate-limit → 429 with Retry-After', async () => {
    const rlMod = await import('../../src/services/rateLimitService');
    rlMod.resetRateLimitForTests();
    const tuneDb = new BetterSqlite3(dbPath);
    tuneDb.prepare(`
      INSERT INTO system_config
        (id, created_at, config_key, value_json, effective_start_at, reason_text, changed_by_member_id)
      VALUES (?, ?, 'work_queue_resolve_rate_limit_per_hour', '2', ?, 'Test tunable', NULL)
    `).run('test-wq-resolve-rl', '2026-05-22T00:00:00.000Z', '2026-05-22T00:00:00.000Z');
    tuneDb.close();
    try {
      const app = createApp();
      const q1 = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
      // postOneOpenRequest may submit, but the resolve bucket is independent.
      // Reset after the open-request seeding to be safe.
      rlMod.resetRateLimitForTests();

      const r1 = await request(app)
        .post(`/admin/work-queue/${q1}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'ok 1' });
      expect(r1.status).toBe(303);

      // Need a fresh open queue row to resolve next; reuse fixture creator.
      const q2 = await postOneOpenRequest(app, OTHER_ID, 'wq_other');
      const r2 = await request(app)
        .post(`/admin/work-queue/${q2}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'ok 2' });
      expect(r2.status).toBe(303);

      // Third resolve attempt - any id, even bogus, should 429 before
      // reaching the service since the bucket is exhausted.
      const blocked = await request(app)
        .post(`/admin/work-queue/wq_anything/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'corrected', resolution_note: 'blocked' });
      expect(blocked.status).toBe(429);
      expect(blocked.headers['retry-after']).toBeDefined();
    } finally {
      rlMod.resetRateLimitForTests();
    }
  });
});

// The system-raised payments tasks reach the queue with no member to reply to;
// an administrator closes each one with a decision and an internal note, and no
// email goes out. These share the generic resolve endpoint with contact
// requests but carry their own decision vocabulary.
describe('POST /admin/work-queue/:id/resolve — payments tasks', () => {
  // Earlier suites in this file tune and leave the resolve rate-limit config in
  // the shared DB. system_config is append-only and effective-dated, so the
  // latest effective row wins: raise the ceiling with a later-dated row so these
  // tests run under a high limit, and empty the per-admin bucket before each so
  // counts do not carry over.
  beforeAll(() => {
    const db = new BetterSqlite3(dbPath);
    db.prepare(`
      INSERT INTO system_config
        (id, created_at, config_key, value_json, effective_start_at, reason_text, changed_by_member_id)
      VALUES (?, ?, 'work_queue_resolve_rate_limit_per_hour', '120', ?, 'Test ceiling', NULL)
    `).run('test-pay-resolve-ceiling', '2026-06-01T00:00:00.000Z', '2026-06-01T00:00:00.000Z');
    db.close();
  });
  beforeEach(async () => {
    const rlMod = await import('../../src/services/rateLimitService');
    rlMod.resetRateLimitForTests();
  });

  const PAYMENTS_TASKS: Array<{ taskType: string; entityType: string; entityId: string }> = [
    { taskType: 'unattributed_refund',                entityType: 'stripe_payment_intent',           entityId: 'pi_unattributed' },
    { taskType: 'partial_refund_review',              entityType: 'payment',                          entityId: 'pay_partial' },
    { taskType: 'charge_dispute_review',              entityType: 'stripe_dispute',                   entityId: 'di_dispute' },
    { taskType: 'payout_failed',                      entityType: 'stripe_payout',                    entityId: 'po_failed' },
    { taskType: 'recurring_donation_charge_declined', entityType: 'recurring_donation_subscription',  entityId: 'rds_declined' },
    { taskType: 'recurring_donation_paused',          entityType: 'recurring_donation_subscription',  entityId: 'rds_paused' },
  ];

  async function seedPaymentsTask(
    taskType: string,
    entityType: string,
    entityId: string,
    detailText: string | null = null,
  ): Promise<string> {
    const { workQueueService } = await import('../../src/services/workQueueService');
    const { id } = workQueueService.enqueue({
      actorId: 'system',
      queueCategory: 'payments',
      taskType,
      entityType,
      entityId,
      priority: 0,
      reasonText: 'seeded payments task',
      detailText,
    });
    return id;
  }

  function outboxCount(): number {
    const db = new BetterSqlite3(dbPath);
    try {
      return (db.prepare('SELECT COUNT(*) AS c FROM outbox_emails').get() as { c: number }).c;
    } finally {
      db.close();
    }
  }

  for (const task of PAYMENTS_TASKS) {
    it(`${task.taskType} is resolvable once, recording who, when, the decision, and the note`, async () => {
      const app = createApp();
      const queueId = await seedPaymentsTask(task.taskType, task.entityType, task.entityId);

      const res = await request(app)
        .post(`/admin/work-queue/${queueId}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'handled_in_stripe', resolution_note: 'Refunded in the Stripe dashboard.' });
      expect(res.status).toBe(303);
      expect(res.headers.location).toBe('/admin/work-queue');

      const db = new BetterSqlite3(dbPath);
      try {
        const row = db
          .prepare('SELECT status, decision_label, reason_text, resolved_by_member_id, resolved_at FROM work_queue_items WHERE id = ?')
          .get(queueId) as Record<string, unknown>;
        expect(row.status).toBe('resolved');
        expect(row.decision_label).toBe('handled_in_stripe');
        expect(row.reason_text).toBe('Refunded in the Stripe dashboard.');
        expect(row.resolved_by_member_id).toBe(ADMIN_ID);
        expect(row.resolved_at).toBeTruthy();

        const audit = db
          .prepare("SELECT actor_type, metadata_json FROM audit_entries WHERE action_type = 'payment.queue_item_resolved' AND entity_id = ?")
          .get(task.entityId) as { actor_type: string; metadata_json: string } | undefined;
        expect(audit).toBeDefined();
        expect(audit!.actor_type).toBe('admin');
        const meta = JSON.parse(audit!.metadata_json) as Record<string, unknown>;
        expect(meta.queue_item_id).toBe(queueId);
        expect(meta.decision_label).toBe('handled_in_stripe');
        // The note stays out of the append-only ledger: it is free text written
        // about a member, and the ledger is exempt from PII purge, so a copy
        // here would outlive the erasure that clears the work-queue row above.
        // The decision label is what the ledger keeps.
        expect(meta.resolution_note).toBeUndefined();
      } finally {
        db.close();
      }
    });
  }

  it('sends no member email on a payments resolution', async () => {
    const app = createApp();
    const queueId = await seedPaymentsTask('charge_dispute_review', 'stripe_dispute', 'di_no_email');
    const before = outboxCount();
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'no_action_needed', resolution_note: 'Represented; awaiting the bank.' });
    expect(res.status).toBe(303);
    expect(outboxCount()).toBe(before);
  });

  it('resolving twice returns 404 the second time, indistinguishable from an unknown id', async () => {
    const app = createApp();
    const queueId = await seedPaymentsTask('payout_failed', 'stripe_payout', 'po_twice');

    const first = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'follow_up_complete', resolution_note: 'Bank details corrected.' });
    expect(first.status).toBe(303);

    const second = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'follow_up_complete', resolution_note: 'again' });
    expect(second.status).toBe(404);

    const unknown = await request(app)
      .post('/admin/work-queue/wq_never_existed_pay/resolve')
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'follow_up_complete', resolution_note: 'again' });
    expect(unknown.status).toBe(404);
    expect(second.text).toBe(unknown.text);
  });

  it('a contact-request decision label is rejected on a payments task', async () => {
    const app = createApp();
    const queueId = await seedPaymentsTask('unattributed_refund', 'stripe_charge', 'ch_wronglabel');
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'note' });
    expect(res.status).toBe(422);
  });

  it('a payments decision label is rejected on a contact request', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'handled_in_stripe', resolution_note: 'note' });
    expect(res.status).toBe(422);
  });

  it('empty and oversized notes are rejected on a payments task', async () => {
    const app = createApp();
    const queueId = await seedPaymentsTask('partial_refund_review', 'payment', 'pay_note');
    const empty = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'no_action_needed', resolution_note: '   ' });
    expect(empty.status).toBe(422);

    const tooLong = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'no_action_needed', resolution_note: 'a'.repeat(501) });
    expect(tooLong.status).toBe(422);
  });

  it('a reconciliation-discrepancy item cannot be resolved here and stays open', async () => {
    const app = createApp();
    const queueId = await seedPaymentsTask('reconciliation_discrepancy', 'reconciliation_issue', 'rec_open');
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'no_action_needed', resolution_note: 'should not resolve here' });
    expect(res.status).toBe(404);

    const db = new BetterSqlite3(dbPath);
    try {
      const row = db.prepare('SELECT status FROM work_queue_items WHERE id = ?').get(queueId) as { status: string };
      expect(row.status).toBe('open');
    } finally {
      db.close();
    }
  });

  it('a payments resolve shares the per-admin rate-limit bucket', async () => {
    const rlMod = await import('../../src/services/rateLimitService');
    rlMod.resetRateLimitForTests();
    const tuneDb = new BetterSqlite3(dbPath);
    // A later effective date than the ceiling row makes this the current value.
    tuneDb.prepare(`
      INSERT INTO system_config
        (id, created_at, config_key, value_json, effective_start_at, reason_text, changed_by_member_id)
      VALUES (?, ?, 'work_queue_resolve_rate_limit_per_hour', '1', ?, 'Test tunable', NULL)
    `).run('test-pay-resolve-rl', '2026-06-02T00:00:00.000Z', '2026-06-02T00:00:00.000Z');
    tuneDb.close();
    try {
      const app = createApp();
      const q1 = await seedPaymentsTask('charge_dispute_review', 'stripe_dispute', 'di_rl_1');
      rlMod.resetRateLimitForTests();

      const r1 = await request(app)
        .post(`/admin/work-queue/${q1}/resolve`)
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'handled_in_stripe', resolution_note: 'one' });
      expect(r1.status).toBe(303);

      const blocked = await request(app)
        .post('/admin/work-queue/wq_anything_pay/resolve')
        .set('Cookie', adminCookie())
        .type('form')
        .send({ decision_label: 'handled_in_stripe', resolution_note: 'blocked' });
      expect(blocked.status).toBe(429);
      expect(blocked.headers['retry-after']).toBeDefined();
    } finally {
      rlMod.resetRateLimitForTests();
      // Append-only config: restore the high ceiling with a still-later row
      // rather than deleting, so any later test runs unthrottled.
      const restore = new BetterSqlite3(dbPath);
      restore.prepare(`
        INSERT INTO system_config
          (id, created_at, config_key, value_json, effective_start_at, reason_text, changed_by_member_id)
        VALUES (?, ?, 'work_queue_resolve_rate_limit_per_hour', '120', ?, 'Test restore', NULL)
      `).run('test-pay-resolve-restore', '2026-06-03T00:00:00.000Z', '2026-06-03T00:00:00.000Z');
      restore.close();
    }
  });

  it('confirms a payments resolve without claiming an email went out', async () => {
    const app = createApp();
    const queueId = await seedPaymentsTask('recurring_donation_paused', 'recurring_donation_subscription', 'rds_banner');
    const resolve = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'no_action_needed', resolution_note: 'Expected seasonal pause.' });
    expect(resolve.status).toBe(303);

    const flashCookie = ((resolve.headers['set-cookie'] as unknown as string[]) ?? [])
      .map((c) => c.split(';')[0])
      .join('; ');
    const page = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', [adminCookie(), flashCookie].filter(Boolean).join('; '));
    expect(page.text).toContain('Item resolved.');
    expect(page.text).not.toContain('email reply dispatched');
  });

  it('renders the entity reference, the detail line, and the payments decisions on a payments card', async () => {
    const app = createApp();
    await seedPaymentsTask('charge_dispute_review', 'stripe_dispute', 'di_render', 'Dispute di_render; amount 2500 USD');
    const reconId = await seedPaymentsTask('reconciliation_discrepancy', 'reconciliation_issue', 'rec_render');

    const res = await request(app).get('/admin/work-queue').set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Stripe dispute di_render');
    expect(res.text).toContain('Dispute di_render; amount 2500 USD');
    expect(res.text).toContain('Handled in Stripe');
    // The reconciliation twin points at its own page and offers no resolve form.
    expect(res.text).toContain('Review on the Reconciliation Page');
    expect(res.text).not.toContain(`action="/admin/work-queue/${reconId}/resolve"`);
  });
});

// A claim says an administrator is handling an item: it drops the item from
// every other administrator's digest and out of the escalation sweep. That
// makes it a coordination signal with a shelf life, not a lock. A claim that
// outlives the administrator's attention must lapse, or one person claiming an
// item and never returning silences it for everyone permanently.
describe('work-queue claims lapse', () => {
  async function seedClaimedItem(claimedAtIso: string, claimerId: string): Promise<string> {
    const { workQueueService } = await import('../../src/services/workQueueService');
    const { id } = workQueueService.enqueue({
      actorId: 'system',
      queueCategory: 'membership',
      taskType: 'auto_link_match',
      entityType: 'member',
      entityId: MEMBER_ID,
      priority: 5,
      reasonText: 'seeded for claim expiry',
      detailText: null,
    });
    const db = new BetterSqlite3(dbPath);
    db.prepare(
      `UPDATE work_queue_items SET claimed_by_member_id = ?, claimed_at = ? WHERE id = ?`,
    ).run(claimerId, claimedAtIso, id);
    db.close();
    return id;
  }

  const LONG_AGO = '2020-01-01T00:00:00.000Z';

  it('a fresh claim by another admin holds the item and offers no Claim control', async () => {
    const app = createApp();
    const id = await seedClaimedItem(new Date().toISOString(), ADMIN2_ID);
    const res = await request(app).get('/admin/work-queue').set('Cookie', adminCookie());
    expect(res.text).toContain('Claimed by WQ Admin Two');
    expect(res.text).not.toContain(`action="/admin/work-queue/${id}/claim"`);
  });

  it('a lapsed claim frees the item, names who had it, and offers Claim again', async () => {
    const app = createApp();
    const id = await seedClaimedItem(LONG_AGO, ADMIN2_ID);
    const res = await request(app).get('/admin/work-queue').set('Cookie', adminCookie());
    expect(res.text).toContain('claimed this earlier and has not closed it');
    expect(res.text).toContain(`action="/admin/work-queue/${id}/claim"`);
  });

  it('another administrator can take over an item whose claim has lapsed', async () => {
    const app = createApp();
    const id = await seedClaimedItem(LONG_AGO, ADMIN2_ID);
    const res = await request(app)
      .post(`/admin/work-queue/${id}/claim`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({});
    expect(res.status).toBe(303);

    const db = new BetterSqlite3(dbPath);
    const row = db
      .prepare('SELECT claimed_by_member_id FROM work_queue_items WHERE id = ?')
      .get(id) as { claimed_by_member_id: string };
    db.close();
    expect(row.claimed_by_member_id).toBe(ADMIN_ID);
  });

  it('a live claim by another administrator still cannot be stolen', async () => {
    const app = createApp();
    const id = await seedClaimedItem(new Date().toISOString(), ADMIN2_ID);
    await request(app)
      .post(`/admin/work-queue/${id}/claim`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({});

    const db = new BetterSqlite3(dbPath);
    const row = db
      .prepare('SELECT claimed_by_member_id FROM work_queue_items WHERE id = ?')
      .get(id) as { claimed_by_member_id: string };
    db.close();
    expect(row.claimed_by_member_id).toBe(ADMIN2_ID);
  });

  it('an item under a lapsed claim becomes eligible for stale escalation again', async () => {
    await seedClaimedItem(LONG_AGO, ADMIN2_ID);
    const { workQueue } = await import('../../src/db/db');
    const rows = workQueue.listStaleForEscalation.all(
      new Date().toISOString(),
      new Date().toISOString(),
    ) as Array<{ id: string }>;
    expect(rows.length).toBeGreaterThan(0);
  });
});

// A low-confidence auto-link classification reaches the queue for an
// administrator to settle by hand. It is an internal review with no member
// reply, so it closes with a dismissal rather than a resolution, and it names
// its own audit event: the ledger is append-only, so filing one review type's
// dismissal under another's could never be corrected. Every enqueued task type
// owes the administrator a way to close it: an item with no control can never
// leave the queue.
describe('POST /admin/work-queue/:id/dismiss — low-confidence auto-link match', () => {
  async function seedAutoLinkMatch(memberId: string): Promise<string> {
    const { workQueueService } = await import('../../src/services/workQueueService');
    const { id } = workQueueService.enqueue({
      actorId: 'system',
      queueCategory: 'membership',
      taskType: 'auto_link_match',
      entityType: 'member',
      entityId: memberId,
      priority: 5,
      reasonText: 'Batch auto-link match (low)',
      detailText: null,
    });
    return id;
  }

  function auditCount(actionType: string, entityId: string): number {
    const db = new BetterSqlite3(dbPath);
    try {
      return (db
        .prepare('SELECT COUNT(*) AS c FROM audit_entries WHERE action_type = ? AND entity_id = ?')
        .get(actionType, entityId) as { c: number }).c;
    } finally {
      db.close();
    }
  }

  it('renders a dismissal control the administrator can act on', async () => {
    const app = createApp();
    const queueId = await seedAutoLinkMatch(MEMBER_ID);
    const res = await request(app).get('/admin/work-queue').set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Auto-link match');
    expect(res.text).toContain(`action="/admin/work-queue/${queueId}/dismiss"`);
  });

  it('dismissal resolves the row and records an auto-link review, not a birth-date one', async () => {
    const app = createApp();
    const queueId = await seedAutoLinkMatch(MEMBER_ID);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/dismiss`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ note: 'no plausible legacy account for this member' });
    expect(res.status).toBe(303);

    const db = new BetterSqlite3(dbPath);
    const row = db
      .prepare('SELECT status, resolved_by_member_id FROM work_queue_items WHERE id = ?')
      .get(queueId) as { status: string; resolved_by_member_id: string } | undefined;
    db.close();
    // A dismissal is not a resolution: nothing was acted on, and the two
    // outcomes stay distinguishable on the row after the fact.
    expect(row?.status).toBe('dismissed');
    expect(row?.resolved_by_member_id).toBe(ADMIN_ID);

    expect(auditCount('legacy.auto_link_match_reviewed', MEMBER_ID)).toBe(1);
    // Each review type names its own dismissal event, so one type's dismissal
    // can never be filed under another's in a ledger that cannot be corrected.
    expect(auditCount('admin.loss_alert_dismissed', MEMBER_ID)).toBe(0);
  });

  // The note is free text an administrator writes about a member, so it belongs
  // in the work-queue row that erasure scrubs, not in the append-only ledger the
  // purge cannot reach.
  it('the dismissal note is kept on the queue row and stays out of the audit ledger', async () => {
    const app = createApp();
    const queueId = await seedAutoLinkMatch(MEMBER_ID);
    const note = 'Spoke to them; the 1998 account belongs to their brother.';
    await request(app)
      .post(`/admin/work-queue/${queueId}/dismiss`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ note });

    const db = new BetterSqlite3(dbPath);
    const row = db
      .prepare('SELECT reason_text FROM work_queue_items WHERE id = ?')
      .get(queueId) as { reason_text: string | null } | undefined;
    const ledger = db
      .prepare(`SELECT metadata_json, reason_text FROM audit_entries
                WHERE action_type = 'legacy.auto_link_match_reviewed'
                  AND metadata_json LIKE '%' || ? || '%'`)
      .all(queueId) as Array<Record<string, unknown>>;
    db.close();

    expect(row?.reason_text).toBe(note);
    expect(ledger).toHaveLength(1);
    expect(`${String(ledger[0].metadata_json)} ${String(ledger[0].reason_text ?? '')}`)
      .not.toContain(note);
  });

  it('its hint does not offer to undo a link, because none was applied', async () => {
    const app = createApp();
    await seedAutoLinkMatch(OTHER_ID);
    const res = await request(app).get('/admin/work-queue').set('Cookie', adminCookie());
    expect(res.text).toContain('No link was applied');
    expect(res.text).not.toContain('Linking is not reverted here');
  });

  it('no member email is sent when a review item is dismissed', async () => {
    const app = createApp();
    const db0 = new BetterSqlite3(dbPath);
    const before = (db0.prepare('SELECT COUNT(*) AS c FROM outbox_emails').get() as { c: number }).c;
    db0.close();

    const queueId = await seedAutoLinkMatch(MEMBER_ID);
    await request(app)
      .post(`/admin/work-queue/${queueId}/dismiss`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ note: 'reviewed' });

    const db1 = new BetterSqlite3(dbPath);
    const after = (db1.prepare('SELECT COUNT(*) AS c FROM outbox_emails').get() as { c: number }).c;
    db1.close();
    expect(after).toBe(before);
  });
});
