import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import request from '../fixtures/supertestWithOrigin';
import BetterSqlite3 from 'better-sqlite3';

import { setTestEnv, createTestDb, cleanupTestDb, importApp } from '../fixtures/testDb';
import { insertMember, createTestSessionJwt } from '../fixtures/factories';

const { dbPath } = setTestEnv('3130');

const ADMIN_ID    = 'wq_admin_001';
const ADMIN_SLUG  = 'wq_admin_one';
const MEMBER_ID   = 'wq_member_001';
const MEMBER_SLUG = 'wq_member_one';
const OTHER_ID    = 'wq_member_002';

let createApp: Awaited<ReturnType<typeof importApp>>;

function adminCookie(): string {
  return `footbag_session=${createTestSessionJwt({ memberId: ADMIN_ID, role: 'admin' })}`;
}
function memberCookie(): string {
  return `footbag_session=${createTestSessionJwt({ memberId: MEMBER_ID })}`;
}

beforeAll(async () => {
  const db = createTestDb(dbPath);
  insertMember(db, { id: ADMIN_ID,  slug: ADMIN_SLUG,  display_name: 'WQ Admin',    real_name: 'WQ Admin',    login_email: 'wq-admin@example.com',  is_admin: 1 });
  insertMember(db, { id: MEMBER_ID, slug: MEMBER_SLUG, display_name: 'WQ Member',   real_name: 'WQ Member',   login_email: 'wq-member@example.com' });
  insertMember(db, { id: OTHER_ID,  slug: 'wq_other',  display_name: 'WQ Other',    real_name: 'WQ Other',    login_email: 'wq-other@example.com' });
  db.close();
  createApp = await importApp();
});

afterAll(() => cleanupTestDb(dbPath));

beforeEach(() => {
  const db = new BetterSqlite3(dbPath);
  db.prepare(`DELETE FROM work_queue_items`).run();
  db.close();
});

function seedOpenContactRequest(memberId: string, message = 'please fix my name'): string {
  // Use the public POST surface so the row goes through the canonical service
  // path (validation, audit, etc.). The admin-resolve tests below then act
  // on the resulting work_queue_items row.
  return memberId; // placeholder; the actual id is generated by the service.
}

async function postOneOpenRequest(app: import('express').Express, memberId: string, memberSlug: string): Promise<string> {
  // Submit via the public form to get a real queue row + audit row.
  await request(app)
    .post(`/members/${memberSlug}/contact-admin`)
    .set('Cookie', `footbag_session=${createTestSessionJwt({ memberId })}`)
    .type('form')
    .send({ category: 'display_name_correction', message: 'please fix my name' });
  const db = new BetterSqlite3(dbPath);
  const row = db
    .prepare(`SELECT id FROM work_queue_items WHERE entity_id = ? AND status = 'open'`)
    .get(memberId) as { id: string } | undefined;
  db.close();
  return row!.id;
}

describe('GET /admin/work-queue', () => {
  it('unauthenticated → 302 to /login with returnTo', async () => {
    const app = createApp();
    const res = await request(app).get('/admin/work-queue');
    expect(res.status).toBe(302);
    expect(res.headers.location).toMatch(/^\/login/);
  });

  it('non-admin → 403', async () => {
    const app = createApp();
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', memberCookie());
    expect(res.status).toBe(403);
  });

  it('admin, no open items → 200 with empty-state message', async () => {
    const app = createApp();
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Admin Work Queue');
    expect(res.text).toContain('No open work-queue items');
  });

  it('admin, with one open contact request → 200 listing the item under Membership', async () => {
    const app = createApp();
    await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .get('/admin/work-queue')
      .set('Cookie', adminCookie());
    expect(res.status).toBe(200);
    expect(res.text).toContain('Membership');
    expect(res.text).toContain('Member contact request');
    expect(res.text).toContain('Display name correction');
    expect(res.text).toContain(`href="/members/${MEMBER_SLUG}"`);
  });
});

describe('POST /admin/work-queue/:id/resolve', () => {
  it('admin resolves → 303 + queue row resolved + audit + email enqueued via outbox', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);

    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'Fixed your display name.' });
    expect(res.status).toBe(303);
    expect(res.headers.location).toBe('/admin/work-queue');

    const db = new BetterSqlite3(dbPath);
    const row = db
      .prepare(`SELECT status, decision_label, reason_text, resolved_by_member_id FROM work_queue_items WHERE id = ?`)
      .get(queueId) as Record<string, unknown> | undefined;
    expect(row).toBeDefined();
    expect(row!.status).toBe('resolved');
    expect(row!.decision_label).toBe('corrected');
    expect(row!.resolved_by_member_id).toBe(ADMIN_ID);

    const audit = db
      .prepare(`SELECT action_type, actor_type FROM audit_entries WHERE action_type = 'support.contact_request_resolved' AND entity_id = ?`)
      .get(MEMBER_ID) as Record<string, unknown> | undefined;
    expect(audit).toBeDefined();
    expect(audit!.actor_type).toBe('admin');

    // Services enqueue notification emails via the outbox table; the SES
    // adapter is never called directly from a service or controller.
    const outboxRow = db
      .prepare(`SELECT recipient_email, subject, body_text, idempotency_key FROM outbox_emails WHERE recipient_member_id = ? AND idempotency_key LIKE 'contact-request-resolve:%' ORDER BY created_at DESC LIMIT 1`)
      .get(MEMBER_ID) as
        | { recipient_email: string; subject: string; body_text: string; idempotency_key: string }
        | undefined;
    expect(outboxRow).toBeDefined();
    expect(outboxRow!.recipient_email).toBe('wq-member@example.com');
    expect(outboxRow!.subject).toContain('Corrected');
    expect(outboxRow!.body_text).toContain('Fixed your display name.');
    expect(outboxRow!.idempotency_key).toBe(`contact-request-resolve:${queueId}`);
    db.close();
  });

  it('invalid decision_label → 422', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'bogus', resolution_note: 'note' });
    expect(res.status).toBe(422);
    expect(res.text).toContain('Invalid decision label');
  });

  it('empty resolution_note → 422', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'denied', resolution_note: '   ' });
    expect(res.status).toBe(422);
    expect(res.text).toContain('Resolution note is required');
  });

  it('unknown queue id → 404', async () => {
    const app = createApp();
    const res = await request(app)
      .post(`/admin/work-queue/wq_does_not_exist/resolve`)
      .set('Cookie', adminCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'ok' });
    expect(res.status).toBe(404);
  });

  it('non-admin POST → 403', async () => {
    const app = createApp();
    const queueId = await postOneOpenRequest(app, MEMBER_ID, MEMBER_SLUG);
    const res = await request(app)
      .post(`/admin/work-queue/${queueId}/resolve`)
      .set('Cookie', memberCookie())
      .type('form')
      .send({ decision_label: 'corrected', resolution_note: 'ok' });
    expect(res.status).toBe(403);
  });
});
