/**
 * Freestyle editorial content.
 *
 * Authored and curated by James (pipeline-side analytical work) and
 * incorporated here as static, non-DB-backed content for the freestyle
 * Insights page (`/freestyle/insights`): analytical snapshots of the
 * freestyle competition dataset.
 *
 * Why this module exists separately from `src/services/freestyleService.ts`:
 * the data here is CONTENT, not service logic. Putting it in a service file
 * violates the "services own use-case logic, not editorial data" boundary;
 * roughly 200 lines of hardcoded editorial arrays previously lived in
 * `freestyleService.ts` and were extracted here.
 *
 * What is in here:
 *   1. Type interfaces describing each content shape (consumed by
 *      freestyleService when building its page view-models).
 *   2. The actual content constants: hand-curated tables of trick usage,
 *      transitions, sequences, player diversity, difficulty eras, and
 *      narrative paragraphs.
 *
 * What is NOT in here:
 *   - Live DB-derived data (records, leaderboards). Those live in
 *     `freestyleService` and query the `freestyle_records` table.
 *   - View-model types that compose editorial + live data (e.g.,
 *     `FreestyleInsightsContent`). Those stay in `freestyleService` because
 *     they are the service's contract with the controller.
 *
 * Maintenance model:
 *   - This file is the canonical home for the editorial text. Edits land
 *     here via code review, not through an admin UI. There is no DB
 *     round-trip; changes deploy with the codebase.
 *   - Source material (the original CSV and Markdown report) is a curated
 *     pipeline output. If that source is regenerated by a future pipeline
 *     run, this module must be updated by hand to match. No
 *     auto-regeneration is wired.
 *
 * Source provenance:
 *   - INSIGHTS_* tables: derived from a frozen analytical output of the
 *     freestyle competition dataset.
 *   - INSIGHTS_NARRATIVES: editorial prose from a curated analytical report
 *     derived from 774 documented competitive events (1980–2026).
 *
 * Consumers:
 *   - `src/services/freestyleService.ts` imports the interfaces and
 *     constants; packages them into the `FreestyleInsightsContent` page
 *     view-model.
 *   - No other file should import from here. If a second surface needs
 *     this data, it's probably a sign the data should be DB-backed;
 *     revisit the editorial-vs-scaffolding decision before adding a
 *     second consumer.
 */

// ─── Insights type interfaces ────────────────────────────────────────────────
//
// Each `INSIGHTS_*` constant below is typed by one of these interfaces. The
// interfaces are exported so `freestyleService` can use them when declaring
// its `FreestyleInsightsContent` view-model shape.

export interface InsightsTrick {
  rank: number;
  name: string;
  adds: string;
  value: number;
  label: string;    // e.g. "150 mentions" or "99 connections"
}

export interface InsightsTransition {
  rank: number;
  from: string;
  to: string;
  count: number;
  players: number;
}

export interface InsightsSequence {
  rank: number;
  player: string;
  year: number;
  adds: number;
  length: number;
  sequence: string;
}

export interface InsightsDiversePlayer {
  rank: number;
  player: string;
  uniqueTricks: number;
  yearsActive: string;
}

export interface InsightsDifficultyEra {
  era: string;
  chains: number;
  avgAdd: number;
}

// ─── Insights data: frozen analytical tables ─────────────────────────────────
//
// The six tables below are snapshots of the freestyle-competition analytical
// output. They were computed once by the pipeline (from 774 documented
// events 1980–2026) and pinned here as stable, curated content. They do not
// regenerate on their own; if the underlying dataset is rerun and the
// analysis changes, update these arrays by hand.
//
// Each table renders as a ranked list on `/freestyle/insights`.

export const INSIGHTS_MOST_USED: InsightsTrick[] = [
  { rank: 1,  name: 'whirl',             adds: '3',        value: 150, label: '150 mentions, 86 players' },
  { rank: 2,  name: 'pixie',             adds: 'modifier', value: 121, label: '121 mentions, 75 players' },
  { rank: 3,  name: 'swirl',             adds: '3',        value: 96,  label: '96 mentions, 44 players' },
  { rank: 4,  name: 'blurry whirl',      adds: '5',        value: 89,  label: '89 mentions, 53 players' },
  { rank: 5,  name: 'torque',            adds: '4',        value: 78,  label: '78 mentions, 49 players' },
  { rank: 6,  name: 'ducking',           adds: 'modifier', value: 59,  label: '59 mentions, 43 players' },
  { rank: 7,  name: 'ripwalk',           adds: '4',        value: 58,  label: '58 mentions, 45 players' },
  { rank: 8,  name: 'butterfly',         adds: '3',        value: 56,  label: '56 mentions, 48 players' },
  { rank: 9,  name: 'spinning',          adds: 'modifier', value: 55,  label: '55 mentions, 31 players' },
  { rank: 10, name: 'legover',           adds: '2',        value: 51,  label: '51 mentions, 31 players' },
  { rank: 11, name: 'mirage',            adds: '2',        value: 48,  label: '48 mentions, 39 players' },
  { rank: 12, name: 'dimwalk',           adds: '4',        value: 45,  label: '45 mentions, 38 players' },
  { rank: 13, name: 'symposium',         adds: 'modifier', value: 38,  label: '38 mentions, 27 players' },
  { rank: 14, name: 'blender',           adds: '4',        value: 36,  label: '36 mentions, 22 players' },
  { rank: 15, name: 'eggbeater',         adds: '3',        value: 33,  label: '33 mentions, 23 players' },
];

export const INSIGHTS_CONNECTORS: InsightsTrick[] = [
  { rank: 1,  name: 'whirl',             adds: '3',  value: 99, label: '99 connections, 86 players' },
  { rank: 2,  name: 'blurry whirl',      adds: '5',  value: 70, label: '70 connections, 53 players' },
  { rank: 3,  name: 'ripwalk',           adds: '4',  value: 61, label: '61 connections, 45 players' },
  { rank: 4,  name: 'butterfly',         adds: '3',  value: 44, label: '44 connections, 48 players' },
  { rank: 5,  name: 'torque',            adds: '4',  value: 39, label: '39 connections, 49 players' },
  { rank: 6,  name: 'dimwalk',           adds: '4',  value: 38, label: '38 connections, 38 players' },
  { rank: 7,  name: 'swirl',             adds: '3',  value: 34, label: '34 connections, 44 players' },
  { rank: 8,  name: 'mirage',            adds: '2',  value: 30, label: '30 connections, 39 players' },
  { rank: 9,  name: 'ducking butterfly', adds: '4',  value: 29, label: '29 connections, 26 players' },
  { rank: 10, name: 'legover',           adds: '2',  value: 27, label: '27 connections, 31 players' },
];

export const INSIGHTS_TRANSITIONS: InsightsTransition[] = [
  { rank: 1,  from: 'blurry whirl',      to: 'whirl',              count: 17, players: 15 },
  { rank: 2,  from: 'ripwalk',           to: 'whirl',              count: 11, players: 10 },
  { rank: 3,  from: 'whirl',             to: 'whirl',              count: 10, players: 9  },
  { rank: 4,  from: 'smear',             to: 'dimwalk',            count: 7,  players: 7  },
  { rank: 5,  from: 'dimwalk',           to: 'ripwalk',            count: 6,  players: 6  },
  { rank: 6,  from: 'blurry whirl',      to: 'ripwalk',            count: 6,  players: 5  },
  { rank: 7,  from: 'dimwalk',           to: 'whirl',              count: 5,  players: 5  },
  { rank: 8,  from: 'blurry whirl',      to: 'paradox torque',     count: 5,  players: 5  },
  { rank: 9,  from: 'fusion',            to: 'eggbeater',          count: 5,  players: 4  },
  { rank: 10, from: 'torque',            to: 'whirl',              count: 4,  players: 3  },
];

export const INSIGHTS_SEQUENCES: InsightsSequence[] = [
  { rank: 1,  player: 'Greg Solis',         year: 2008, adds: 22, length: 7, sequence: 'butterfly > whirl > osis > dimwalk > osis > butterfly > swirl' },
  { rank: 2,  player: 'Stefan Siegert',     year: 2005, adds: 18, length: 5, sequence: 'blurry whirl > ripwalk > whirl > pixie > paradox whirl' },
  { rank: 3,  player: 'Cody Rushing',       year: 2008, adds: 18, length: 5, sequence: 'blur > dimwalk > swirl > smear > dimwalk' },
  { rank: 4,  player: 'Daniel Cadavid',     year: 2021, adds: 18, length: 5, sequence: 'dimwalk > osis > dimwalk > spinning osis > whirl' },
  { rank: 5,  player: 'Kyle Hewitt',        year: 2007, adds: 16, length: 4, sequence: 'ripwalk > blurry whirl > smear > dimwalk' },
  { rank: 6,  player: 'Brad Nelson',        year: 2002, adds: 15, length: 3, sequence: 'blurry whirl > paradox torque > paradox blender' },
  { rank: 7,  player: 'Jake Wren',          year: 2007, adds: 15, length: 3, sequence: 'blurriest > spinning whirl > blurry whirl' },
  { rank: 8,  player: 'Byrin Wylie',        year: 2007, adds: 15, length: 3, sequence: 'blurry whirl > blurry whirl > blurriest' },
  { rank: 9,  player: 'Marcin Bujko',       year: 2010, adds: 15, length: 3, sequence: 'spinning osis > food processor > mobius' },
  { rank: 10, player: 'Chris Dean',         year: 2013, adds: 15, length: 3, sequence: 'ducking butterfly > food processor > mobius' },
];

export const INSIGHTS_DIVERSE_PLAYERS: InsightsDiversePlayer[] = [
  { rank: 1,  player: 'Mariusz Wilk',            uniqueTricks: 30, yearsActive: '2008–2019' },
  { rank: 2,  player: 'Honza Weber',              uniqueTricks: 22, yearsActive: '2004–2021' },
  { rank: 3,  player: 'Julien Appolonio',         uniqueTricks: 20, yearsActive: '2007' },
  { rank: 4,  player: 'Stefan Siegert',           uniqueTricks: 19, yearsActive: '2005–2012' },
  { rank: 5,  player: 'Jim Penske',               uniqueTricks: 18, yearsActive: '2006–2015' },
  { rank: 6,  player: 'Byrin Wylie',              uniqueTricks: 16, yearsActive: '2005–2007' },
  { rank: 7,  player: 'Matthias Lino Schmidt',    uniqueTricks: 16, yearsActive: '2012–2013' },
  { rank: 8,  player: 'Damian Gielnicki',         uniqueTricks: 14, yearsActive: '2006–2022' },
  { rank: 9,  player: 'Milan Benda',              uniqueTricks: 12, yearsActive: '2007–2014' },
  { rank: 10, player: 'Nick Landes',              uniqueTricks: 11, yearsActive: '2004–2009' },
];

export const INSIGHTS_DIFFICULTY_ERAS: InsightsDifficultyEra[] = [
  { era: '2001–2003', chains: 29,  avgAdd: 3.52 },
  { era: '2004–2006', chains: 93,  avgAdd: 3.46 },
  { era: '2007–2009', chains: 118, avgAdd: 3.30 },
  { era: '2010–2015', chains: 53,  avgAdd: 3.26 },
  { era: '2016–2025', chains: 82,  avgAdd: 3.12 },
];

export const INSIGHTS_NARRATIVES: string[] = [
  'From a network perspective, freestyle sequences exhibit a clear directional structure. ' +
  'Blurry whirl functions as the primary launch node, initiating high-difficulty sequences, ' +
  'while whirl serves as the dominant attractor, acting as the most common resolution point. ' +
  'This creates a highly asymmetric flow pattern: sequences tend to begin with high-complexity ' +
  'rotational entries and resolve into more stable, clipper-based terminations.',

  'The plateau in average ADD after 2007 suggests that freestyle did not continue to increase ' +
  'in raw technical difficulty after the mid-2000s. Instead, progress shifted toward consistency, ' +
  'execution quality, and the number of players capable of reaching the established ceiling, ' +
  'a transition from technical expansion to competitive depth.',

  'While ADD values above 6 may be theoretically possible, the dataset shows no sustained ' +
  'increase in single-trick difficulty beyond 6 ADD. This suggests a practical ceiling imposed ' +
  'by human biomechanics: finite airtime, constraints on rotational speed, increasing coordination ' +
  'complexity with stacked modifiers, and the requirement for controlled stall completion.',

  'The concentration of both podium finishes and high-difficulty sequence data among European ' +
  'players indicates that the competitive center of freestyle shifted geographically during this ' +
  'period. While early innovation was driven largely by North American players, the post-2005 era ' +
  'is characterized by European dominance in both performance and participation density.',

  'Freestyle footbag evolved through two distinct phases: an early period of rapid innovation in ' +
  'which the core vocabulary was established, followed by a mature phase in which that vocabulary ' +
  'was fully exploited. Progress is now defined not by new elements, but by the refinement and ' +
  'recombination of existing ones.',
];

// ─── Insights narratives: editorial prose analysis ───────────────────────────
//
// Five paragraphs of analytical commentary rendered as the narrative section
// of `/freestyle/insights`. Authored as editorial text; edits land here
// via code review, not live rebuilds.

