// freestyleTrackedNames.ts
// ============================
// GENERATED FILE — do not hand-edit.
// Regenerate: python3 legacy_data/scripts/build_tracked_names_content.py
//
// Documented freestyle trick names tracked in the project vocabulary
// corpus that are NOT yet canonically published, grouped by
// documenting source. A name documented in more than one source is
// listed once, under its primary source.
//
// Grouped by SOURCE, not ADD: the /freestyle/observational page
// contract forbids grouping by external ADD claim (a claimed ADD is
// often a relative modifier delta, not a canonical difficulty class).
//
// Source: the 2026-05-21 cross-source vocabulary reconciliation audit
// (exploration/vocabulary-reconciliation-audit-2026-05-21/).
// Reversible content module per [[feedback_reversible_content_governance]].

export interface TrackedNameGroup {
  /** Documenting-source display label, e.g. "FootbagMoves". */
  readonly sourceLabel: string;
  /** Trick names primarily documented by this source, alphabetical. */
  readonly names: readonly string[];
}

/** Total tracked-but-unpublished names across all sources. */
export const TRACKED_UNPUBLISHED_TOTAL = 558;

export const TRACKED_UNPUBLISHED_NAMES: readonly TrackedNameGroup[] = [
  { sourceLabel: 'FootbagMoves', names: [
    '69', '84', 'Aeon Flux', 'Alex Zerbe is the greatest',
    'Alpine Big Apple', 'Amadeus', 'Anoxia', 'Apocalypse',
    'Arachnophobia', 'Arch Nemesis', 'Arcwalk', 'Atom Bomb',
    'Atomic DLO', 'Atomic Drifter', 'Atomic Illusion', 'Atomic Legover (same side)',
    'Atomic Osis', 'Atomic Pickup (same side)', 'Atomic ss Osis', 'Atomotion',
    'Avalanche', 'Barfry', 'Barroque', 'Bedwetter',
    'Big Apple Sauce', 'Big Papa Smurf', 'Bill & Ted`s Bogus Journey', 'Bill & Ted`s Excellent Adventure',
    'Blacula', 'Bladerunner', 'Blaze', 'Bling Blang',
    'Blister', 'Blizzard', 'Blue Widow', 'Blurrage',
    'Blurrier', 'Blurry Chainsaw Massacre', 'Blurry Drifter', 'Boulderbeater',
    'Bubba Beater', 'Butterfly Swirl', 'Buttersole', 'Carousel',
    'Cascade', 'Casket', 'Cataclysm', 'Catacomb',
    'Chainsaw Massacre', 'Clown Face', 'Cold Fusion', 'Colossus',
    'Compound Fracture', 'Conniption City', 'Cristal', 'Croissant',
    'Croxton', 'Cyborg', 'Cyclone', 'Dark Avenue',
    'Darkwalk', 'Dellusion', 'Desien', 'Diving Butterfly',
    'Diving Osis', 'Dolomite', 'Dominatrix', 'Dorshanatrix',
    'Dorshatrix', 'Double Helix', 'Double Over Down', 'Double Spinning Clipper',
    'Double Spinning Osis', 'Double Spinning Rake', 'Double Switchover (far)', 'Down Diver',
    'Down Double Down', 'Downward Spiral', 'Dragonstein', 'Dragster',
    'Ducking Illusion', 'Ducking Legover', 'Ducking Pdx Illusion', 'Ducking Pdx Mirage',
    'Ducking Pickup', 'Ducking PS Illusion', 'Ducking PS Mirage', 'Dwirl',
    'E-Walk', 'Eggplant', 'Ego', 'Enterrage',
    'Fairy Beater', 'Fairy Ducking Butterfly', 'Fairy Ducking Legover', 'Fairy Ducking Pickup',
    'Fairy Eggbeater', 'Fairy Illusion (same side)', 'Fairy Legover', 'Fairy Mirage (same side)',
    'Fairy Pickup', 'Fairy ss Osis', 'Fairy Symposium Mirage', 'Fairy Tale',
    'Fairy Torque (same side)', 'Fairy Whirl', 'Far Dyno', 'Far Reverse Whirl',
    'Fear', 'Fender', 'Fender Bender', 'Feral',
    'Ferocious', 'Firefly', 'Firewalk', 'Fission',
    'Flaming Homer', 'Flaming Tard', 'Flipwalk', 'Floatation',
    'Flog', 'Flurricane', 'Flux', 'Flying Fish',
    'Forque', 'Forquelift', 'Fracture', 'Frankenstein',
    'Freak', 'Frenzy', 'Fudge', 'Fume',
    'Furnace', 'G.Y.B.A.S.', 'Gangsta Party', 'Gary Coleman',
    'Genesis', 'Genuphobia', 'Gilan', 'Glaucoma',
    'Godzilla', 'Golden Shower', 'Goliath', 'Grifter',
    'Guillotine', 'Gyro Barfly', 'Gyro Blender', 'Gyro Butterfly',
    'Gyro Clipper', 'Gyro DLO', 'Gyro Illusion', 'Gyro Mirage',
    'Gyro Osis', 'Gyro Whirl', 'Heart', 'Hurl',
    'Icarus', 'Icon', 'Ill Frenzy', 'Inspinning Butterfly',
    'Inspinning Clipper', 'Inspinning Osis', 'Irish Cream', 'Irish Spring',
    'Jacknife', 'Janiwalker', 'Joan', 'Johny Quest',
    'Johny Vodka', 'Juggernaut', 'Juno Reactor', 'Kill Frenzy',
    'Kiss Of The Scorpion', 'Kiwi', 'Kyttyrä', 'Lawnmoir',
    'Leaning Jowler', 'Legbreaker', 'Legfreezer', 'Leviathan',
    'Liquifier', 'Little Apple', 'Locomotion', 'Lotus',
    'Macon Bacon', 'Maelstrom', 'Majello', 'Margaritaville',
    'Massacre', 'Maverick', 'Merlin', 'Moby Dick',
    'Mofly', 'Moirius', 'Morpheus', 'Motion',
    'Motion Sickness', 'Muerto', 'MXZYPTLK', 'Nallegam',
    'Nebula', 'Nemesis Swirl', 'Neutron Smasher', 'Nobius',
    'Nuclear Illusion', 'Nuclear Legover', 'Nuclear Pickup', 'Nullwalk',
    'Ocean', 'Odula', 'Oh Wheely', 'Omelette Du Fromage',
    'Original Barroque', 'Orpheus', 'Osmosis', 'Overlord',
    'Pandemonium', 'Pandora`s Box', 'Paradox Symposium Whirling Rake', 'Paradox Whirling Rake',
    'Parallax', 'Paratoxic', 'Park Avenue', 'Pdx Dada Curve',
    'Pdx DLO', 'Pdx Illusion', 'Pdx Whirling Swirl', 'Phase',
    'Philibuster', 'Phobia', 'Pixie Ducking Legover', 'Pixie Ducking Mirage',
    'Pixie Ducking Pickup', 'Pixie Eggbeater', 'Pixie Legover', 'Pixie Osis',
    'Pixie Pickup', 'Pixie Quantum Butterfly', 'Pixie Symposium Illusion', 'Pixie Symposium Mirage',
    'Pixie Torque', 'Pixie Whirl', 'POD', 'Porque',
    'Predator', 'PS Illusion', 'PS Mirage', 'Pteradon',
    'Puck', 'Quagmire', 'Quantanamera', 'Quantum Butterfly (same side)',
    'Quantum Illusion', 'Quantum Legover', 'Quantum Mirage', 'Quantum Osis',
    'Quantum Pickup (same side)', 'Quark', 'Rage', 'Rail Warrior',
    'Raildown', 'Railplant', 'Railwalk', 'Rasmus',
    'Reactor', 'Red Ribbon', 'Redwetter', 'Reverse Swirling Osis',
    'Reverse Whirling Rake', 'Revstein', 'Ricochet', 'Ripcurl',
    'Ripped Warrior', 'Riptide', 'Ropaduleo', 'Royall Assassin',
    'S&M Smasher', 'Sabotage', 'Saildown', 'Sasquatch',
    'Scorpion\'s Tail', 'Scorpions Toe Nail', 'Shaft', 'Shmoe',
    'Singularity', 'Slap', 'Slapdown', 'Slapstick',
    'Smashwalk', 'Smile', 'Snapdragon', 'Snowflake',
    'Spanish Fly', 'Spikehammer', 'Spinning Butterfly Swirl', 'Spinning Ducking Butterfly',
    'Spinning Ducking Clipper', 'Spinning Ducking Osis', 'Spinning Ducking Pdx Mirage', 'Spinning Pdx DLO',
    'Spinning Pdx Illusion', 'Spinning Pdx Mirage', 'Spinning Pdx Whirl', 'Spitfire',
    'Spyro Gyro', 'Stampede', 'Stepping Blender (same side)', 'Stepping Clipper (same side)',
    'Stepping Ducking Butterfly (same side)', 'Stepping Ducking DLO', 'Stepping Ducking Far Double Pickup', 'Stepping Ducking PS Whirl',
    'Stepping Eggbeater', 'Stepping far Clipper', 'Stepping Illusion (same side)', 'Stepping Legover (same side)',
    'Stepping Mirage (same side)', 'Stepping Pdx Torque', 'Stepping Pickup', 'Sumo Thong',
    'Sunilwalker', 'Super Ego', 'Superdeeduperfly', 'Superduperfly',
    'Supernova', 'Surging Ducking Paradox Torque', 'Swifter', 'Swirlwind',
    'Swivel', 'Syberian Express', 'Symp Illusion', 'Symp Mirage',
    'Symp Whirl', 'Symple Butterfly', 'Symple Reverse Swirl (far)', 'Symple Swirl (far)',
    'Symposium Down Double Down', 'Symposium Eggbeater', 'Tap Dance', 'Tapwater',
    'Terminator', 'Timberwulff', 'Tobius', 'Tofu',
    'Torch-r Rack', 'Tornado', 'Torquescrew', 'Torus',
    'Tremor', 'Triadon', 'Triage', 'Trifly',
    'Triple ATW in-out', 'Triple ATW out-in', 'Trixie', 'Trochus',
    'Tunguska', 'Tutifruti', 'Twirl', 'Vertigo',
    'Voodoo', 'Wahnsinn', 'Warp', 'Weaving Butterfly',
    'Weaving Clipper', 'Weaving Legover', 'Weaving Osis', 'Weaving Pickup',
    'Weaving Whirl', 'Wentletrappe', 'Whale Tail', 'What!?',
    'Whirling far Butterfly', 'Whirling pdx Mirage', 'Whirling Rake', 'Whirlwalk',
    'Whirlygig', 'Whirr', 'Whisk', 'Wookie',
    'Yoda', 'Your Mom', 'Your Sister', 'Zig Zag',
    'Zipwalk', 'Zulu Le Loup', 'Zulu Legover', 'Zulu Osis',
    'Zulu Pickup', 'Zulu Whirl',
  ] },
  { sourceLabel: 'footbag.org', names: [
    'Around the World Kick', 'Atomic Eclipse', 'Backside Symposium Smear', 'Backside Symposium Toe Blizzard',
    'Backside Symposium Toe Blur', 'Barfly Swirl', 'Blistering Whirl', 'Blurry Symposium Whirl',
    'Blurry Whirling Swirl', 'Bubba', 'Butterfly Kick', 'Clipper Kick',
    'Da Da Curve', 'Double Around the World Heel', 'Double Blender', 'Double Pickup',
    'Double Switch-Over', 'Double-Over Down', 'Double-Over Down Swirl', 'Down Double-Down',
    'Dragon', 'Ducking Barfly', 'Fairy Butterfly', 'Fairy Clipper',
    'Fairy Drifter', 'Fairy Leg Over', 'Fairy Merkon', 'Fairy Same Side Mirage',
    'Fairy Same Side Whirl', 'Fairy Spyro Mirage', 'Frigidosis', 'Hop Over Swirl',
    'Inspinning Paradox Illusion', 'Inspinning Paradox Mirage', 'Inspinning Same Side Butterfly', 'Inspinning Same Side Illusion',
    'Inspinning Same Side Mirage', 'Leg-Over Flapper Stall', 'Miraging Eclipse', 'Miraging Pincher',
    'Nuclear Whirl', 'Pandora', 'Paradon Swirl', 'Paradox Barrage',
    'Paradox Blizzard', 'Paradox Blur', 'Paradox Blurry Whirl', 'Paradox Da Da Curve',
    'Paradox Double Leg Over', 'Paradox High Plains Drifter', 'Paradox Illusion', 'Paradox Ripwalk',
    'Paradox Symposium Mirage', 'Paradox Whirling Swirl', 'Paralax', 'Pixie Double Over Down',
    'Pixie Eclipse', 'Pixie Leg Over', 'Pixie Opposite Clipper', 'Pixie Paradon',
    'Pixie Same Clipper', 'Pixie Same Side Illusion', 'Pixie Swirl', 'Pogo Barfly',
    'Pogo Butterfly', 'Pogo Paradox Barrage', 'Pogo Paradox Blender', 'Pogo Paradox Da Da Curve',
    'Pogo Paradox Drifter', 'Pogo Paradox Eggbeater', 'Pogo Paradox Mirage', 'Pogo Paradox Torque',
    'Pogo Paradox Whirl', 'Pogo Paradox Whirling Swirl', 'Pogo Pickup', 'Pogo Voodoo',
    'Probe', 'Quantum Drifter', 'Quantum Whirl', 'Reverse Magellan',
    'Shooting Butterfly', 'Shooting Mirage', 'Shooting Star', 'Shooting Torque',
    'Spike Hammer', 'Spinning Butterfly Kick', 'Spinning Paradox Blender', 'Spinning Paradox Illusion',
    'Spinning Paradox Mirage', 'Spinning Paradox Whirl', 'Spinning Symposium Down Double Down', 'Spyro Illusion',
    'Spyro Mirage', 'Spyro Whirl', 'Stepping Ducking Mirage', 'Stepping Ducking Paradox Blender',
    'Stepping Opposite Reaper', 'Stepping Opposite Side Reverse Whirl', 'Stepping P.S. Whirling x-body Rake', 'Stepping Whirling Swirl',
    'Symposium Blizzard', 'Symposium Blur', 'Symposium Double Leg Over', 'Symposium Pixie',
    'Symposium Reverse Whirl', 'Symposium Tomahawk', 'Symposium Torque', 'Symposium Whirling Swirl',
    'Tapping Illusion', 'Terraging Opposite Clipper', 'Terraging Same Clipper', 'Toe Blizzard',
    'Toe Clipper', 'Toe Double Drifter', 'Toe Ripwalk', 'Toe Whirr',
    'Triple Around The World', 'Triple Spin', 'Wrap',
  ] },
  { sourceLabel: 'PassBack', names: [
    'Alpine Blurry Whirl', 'Alpine Magellan', 'Alpine Paste', 'Alpine Pigbeater',
    'Alpine PLO', 'Alpine Smog', 'Alpine Smudge', 'Blazing Butterfly',
    'Blink', 'BS Magellan', 'BS Paste', 'DDD',
    'Diving Clipper', 'Diving Mirage', 'Diving Smudge', 'Double Dyno',
    'Double Fairy', 'Double Orbit', 'Double Spinning Butterfly', 'Double Whip',
    'DSO', 'Ducking Pdx Torque', 'Fairy DLO (ss)', 'Frantic Legover',
    'Gyro Symp Swirl', 'Gyro Toe', 'Gyro Whirling Swirl', 'Infinity',
    'Infinity Swirl', 'Pixie Double Pickup (ss)', 'Pixie DSO', 'PLO',
    'Solestice', 'Spanishfly', 'Spinning Symp Swirl', 'Stepping Ducking Osis',
    'Symp Eggbeater', 'Symp Swirl (op)', 'Symp Whirling Swirl', 'Tapping Legover',
    'Tapping Pickup', 'Toe Ducking Legover', 'Toe Gyro Mirage', 'Toe Spinning Toe',
    'Triple Orbit', 'Void', 'Weaving Magellan', 'Weaving Pigbeater',
    'Zulu Clipper',
  ] },
];
