// freestyleTrackedNames.ts
// ============================
// GENERATED FILE — do not hand-edit.
// Regenerate: python3 legacy_data/scripts/build_tracked_names_content.py
//
// Documented freestyle trick names tracked in the project vocabulary
// corpus that are NOT yet canonically published, grouped by
// documenting source. Where the reconciliation master already records
// a symbolic / operational notation, it is carried verbatim — no
// formula is invented or derived, and no ADD claim is made.
//
// Grouped by SOURCE, not ADD: the /freestyle/observational page
// contract forbids grouping by external ADD claim.
//
// Source: the 2026-05-21 cross-source vocabulary reconciliation audit
// + SYMBOLIC_GRAMMAR_MASTER.csv (symbolic_notation_raw).
// Reversible content module per [[feedback_reversible_content_governance]].

export interface TrackedName {
  /** Trick name as documented by the source. */
  readonly displayName: string;
  /** Symbolic / operational notation, verbatim from the reconciliation
   *  master where one is already recorded. Absent when none exists. */
  readonly operationalNotation?: string;
  /** Corpus the notation was recorded in. */
  readonly formulaProvenance?: string;
  /** Parser confidence in the notation, where recorded. */
  readonly formulaConfidence?: string;
}

export interface TrackedNameGroup {
  /** Documenting-source display label, e.g. "FootbagMoves". */
  readonly sourceLabel: string;
  /** Trick names primarily documented by this source, alphabetical. */
  readonly names: readonly TrackedName[];
}

/** Total tracked-but-unpublished names across all sources. */
export const TRACKED_UNPUBLISHED_TOTAL = 558;

export const TRACKED_UNPUBLISHED_NAMES: readonly TrackedNameGroup[] = [
  { sourceLabel: 'FootbagMoves', names: [
    { displayName: '69', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Op In (DEX)(XDEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: '84', operationalNotation: 'Toe > Same In (DEX) > Same Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Aeon Flux', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Alex Zerbe is the greatest', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Alpine Big Apple' },
    { displayName: 'Amadeus', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same In (DEX) > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Anoxia', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> (no plant while) Op In (DEX)(PDX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Apocalypse', operationalNotation: 'Toe > Same In (DEX) >> Op In (DEX) > (no plant while) Op In (DEX)(XDEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Arachnophobia', operationalNotation: 'Clip > Op In (DEX) >> Dive (BOD) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Arch Nemesis', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Arcwalk', operationalNotation: 'Frigidosis > Same In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Atom Bomb', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Atomic DLO' },
    { displayName: 'Atomic Drifter' },
    { displayName: 'Atomic Illusion' },
    { displayName: 'Atomic Legover (same side)' },
    { displayName: 'Atomic Osis' },
    { displayName: 'Atomic Pickup (same side)' },
    { displayName: 'Atomic ss Osis' },
    { displayName: 'Atomotion', operationalNotation: 'Toe > Op Out (DEX) >> Op Out (DEX)(XDEX) > Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Avalanche', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Barfry', operationalNotation: 'Clip > Same Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Barroque', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bedwetter', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Big Apple Sauce', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op In (DEX)(PDX) > (no plant while) Op In (DEX)(XDEX)(BOD) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Big Papa Smurf', operationalNotation: 'Toe > Same Out (DEX) > (no plant while) Op Back Swirl (DEX)(BOD) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bill & Ted`s Bogus Journey', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same In (DEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bill & Ted`s Excellent Adventure', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same Out (DEX)(XDEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blacula', operationalNotation: 'Toe >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bladerunner', operationalNotation: 'Toe > Op Out (DEX) >> Op Out (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blaze', operationalNotation: 'Clip > Op Front Whirl (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bling Blang', operationalNotation: 'Clip > Op Front Whirl (DEX) >> Same Back Swirl (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blister', operationalNotation: 'Clip > Op Front Whirl (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blizzard', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blue Widow', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> (no plant while) Same Front Whirl (DEX)(PDX)(BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurrage', operationalNotation: 'Clip > Op In (DEX) >> Op In (DEX)(PDX) > Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurrier', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurry Chainsaw Massacre', operationalNotation: 'Clip >> Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(PDX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurry Drifter' },
    { displayName: 'Boulderbeater', operationalNotation: 'Toe > Op In (DEX) >> Op Out (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bubba Beater', operationalNotation: 'Clip >> Op Out (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Butterfly Swirl' },
    { displayName: 'Buttersole', operationalNotation: 'Set >> Op Out (DEX) > Op Flapper (XBD)(UNS)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Carousel' },
    { displayName: 'Cascade', operationalNotation: 'Toe >> Duck (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Casket', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cataclysm', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Catacomb', operationalNotation: 'Toe > Same In (DEX) >> Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Chainsaw Massacre', operationalNotation: 'Clip >> Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(PDX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Clown Face', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Out (DEX)(XDEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cold Fusion', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Op Out (DEX)(XDEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Colossus', operationalNotation: 'Clip >> (back) Spin (BOD) > Dive (BOD) >> (no plant while) Same Front Whirl (DEX)(BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Compound Fracture', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Conniption City', operationalNotation: 'Toe > Op In (DEX) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cristal', operationalNotation: 'Toe > Op In (DEX) >> Duck (BOD) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Croissant', operationalNotation: 'Toe > Same In (DEX) >> (no plant while) Op Front Whirl (DEX)(BOD) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Croxton', operationalNotation: 'Clip > (no plant while) Op Front Whirl (DEX)(BOD) > Op Back Swirl (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cyborg', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cyclone', operationalNotation: 'Clip > Op In (DEX) > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dark Avenue', operationalNotation: 'Toe > Same Out (DEX) >> Dive (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Darkwalk', operationalNotation: 'Toe > Same In (DEX) >> Dive (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dellusion', operationalNotation: 'Toe >> Op Out (DEX) > Same Out (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Desien', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Diving Butterfly' },
    { displayName: 'Diving Osis' },
    { displayName: 'Dolomite', operationalNotation: 'Toe >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dominatrix', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dorshanatrix', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dorshatrix', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Double Helix', operationalNotation: 'Clip >> (no plant while) Op Back Whirl (DEX)(BOD) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Double Over Down' },
    { displayName: 'Double Spinning Clipper' },
    { displayName: 'Double Spinning Osis' },
    { displayName: 'Double Spinning Rake' },
    { displayName: 'Double Switchover (far)' },
    { displayName: 'Down Diver', operationalNotation: 'Clip >> Dive (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Down Double Down', operationalNotation: 'Clip >> Op Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Downward Spiral', operationalNotation: 'Toe > Same Out (DEX) > Op Back Swirl (DEX) >> Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dragonstein', operationalNotation: 'Clip >> Same Back Swirl (BOD) >> Same Back Swirl (BOD) > Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Dragster', operationalNotation: 'Clip >> Op In (DEX) > Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Ducking Illusion' },
    { displayName: 'Ducking Legover' },
    { displayName: 'Ducking Pdx Illusion' },
    { displayName: 'Ducking Pdx Mirage' },
    { displayName: 'Ducking Pickup' },
    { displayName: 'Ducking PS Illusion' },
    { displayName: 'Ducking PS Mirage' },
    { displayName: 'Dwirl', operationalNotation: 'Clip >> Same Front Swirl (DEX) > Same Front Swirl (DEX)(XDEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'E-Walk', operationalNotation: 'Toe > Same In (DEX) > Op In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Eggplant', operationalNotation: 'Toe > Op Out (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ego', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Enterrage', operationalNotation: 'Toe > Same In (DEX) > Same In (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Beater', operationalNotation: 'Toe > Same Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Ducking Butterfly' },
    { displayName: 'Fairy Ducking Legover' },
    { displayName: 'Fairy Ducking Pickup' },
    { displayName: 'Fairy Eggbeater' },
    { displayName: 'Fairy Illusion (same side)' },
    { displayName: 'Fairy Legover' },
    { displayName: 'Fairy Mirage (same side)' },
    { displayName: 'Fairy Pickup' },
    { displayName: 'Fairy ss Osis', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Symposium Mirage' },
    { displayName: 'Fairy Tale', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Torque (same side)' },
    { displayName: 'Fairy Whirl', operationalNotation: 'TOE > SAME OUT [DEX] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Far Dyno' },
    { displayName: 'Far Reverse Whirl' },
    { displayName: 'Fear', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fender', operationalNotation: 'Toe > Same Out (DEX) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fender Bender', operationalNotation: 'Toe > Same Out (DEX) >> Duck (BOD) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Feral', operationalNotation: 'Toe > Same Out (DEX) >> Op Front Whirl (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ferocious', operationalNotation: 'Toe > Same Out (DEX) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Firefly', operationalNotation: 'Set >> Op Out (DEX) > Op Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Firewalk', operationalNotation: 'Clip > (no plant while) Op Front Whirl (DEX)(BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fission', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Out (DEX)(XDEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flaming Homer', operationalNotation: 'Toe > Same Out (DEX) >> Same Out (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flaming Tard', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flipwalk', operationalNotation: 'Dragon > Op In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Floatation', operationalNotation: 'Toe > (no plant while) Op In (DEX)(BOD) > Op In (DEX)(XDEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flog', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flurricane', operationalNotation: 'Clip >> (back) Spin (BOD > Same In (DEX) > Same In (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Flux', operationalNotation: 'Set >> Op Out (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flying Fish', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Forque', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Forquelift', operationalNotation: 'Toe > Same Out (DEX) >> Duck (BOD) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fracture', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Frankenstein', operationalNotation: 'Toe > Same Out (DEX) > Op Back Swirl (DEX) >> Same Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Freak', operationalNotation: 'Toe > Same Out (DEX) >> Same Crossbody Rake (XBD)(DEL)(DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Frenzy', operationalNotation: 'Toe > Same In (DEX) > Op In (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fudge', operationalNotation: 'Toe > Same Out (DEX) >> Op Out (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fume', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Furnace', operationalNotation: 'Inside > Jump (BOD >> Same Back Swirl (DEX) > Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'low' },
    { displayName: 'G.Y.B.A.S.', operationalNotation: 'Clip > Op In (DEX) >> Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gangsta Party', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> Op Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gary Coleman', operationalNotation: 'Toe > Op Out (DEX) >> (no plant while) Op Front Whirl (DEX)(XDEX)(BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Genesis', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Front Whirl (DEX)(XDEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Genuphobia', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> (no plant while) Op In (DEX)(BOD) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gilan', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Glaucoma', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Godzilla', operationalNotation: 'Clip > Same Out (DEX) >> Same Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Golden Shower', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Goliath', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Grifter', operationalNotation: 'Clip >> Op Out (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Guillotine', operationalNotation: 'Toe > Same Out (DEX) >> Duck (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gyro Barfly' },
    { displayName: 'Gyro Blender' },
    { displayName: 'Gyro Butterfly' },
    { displayName: 'Gyro Clipper' },
    { displayName: 'Gyro DLO' },
    { displayName: 'Gyro Illusion' },
    { displayName: 'Gyro Mirage' },
    { displayName: 'Gyro Osis' },
    { displayName: 'Gyro Whirl' },
    { displayName: 'Heart' },
    { displayName: 'Hurl', operationalNotation: 'Clip > Same Out (DEX) >> Same Front Whirl (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Icarus', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Icon', operationalNotation: 'Clip >> (front) Spin (BOD) >> Same Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ill Frenzy', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op Out (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Inspinning Butterfly' },
    { displayName: 'Inspinning Clipper' },
    { displayName: 'Inspinning Osis' },
    { displayName: 'Irish Cream', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Irish Spring', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Jacknife', operationalNotation: 'Clip > Op In (DEX) >> Dive (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Janiwalker', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Joan', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Johny Quest', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Johny Vodka', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Juggernaut', operationalNotation: 'Toe > Same Out (DEX) >> (no plant while) Op Out (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Juno Reactor', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kill Frenzy', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kiss Of The Scorpion', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kiwi', operationalNotation: 'Toe > Op Out (DEX) >> Same Out (DEX)(XDEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kyttyrä' },
    { displayName: 'Lawnmoir', operationalNotation: 'Clip > (back) Spin (BOD) > Front Swirl (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Leaning Jowler', operationalNotation: 'Clip > Op In (DEX) >> (front) Spin (BOD) >> Same In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Legbreaker', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Legfreezer', operationalNotation: 'Frigidosis > Op Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Leviathan', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Liquifier', operationalNotation: 'Clip > (back) Spin (BOD) > (no plant while) Front Swirl (DEX)(BOD) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Little Apple', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Locomotion', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX) > Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Lotus', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op In (DEX)(PDX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Macon Bacon', operationalNotation: 'Clip > Op In (DEX) >> (front) Spin (BOD) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Maelstrom', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> Op Front Whirl (DEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Majello', operationalNotation: 'Toe > Same In (DEX) >> Same Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Margaritaville', operationalNotation: 'Clip > (back) Spin (BOD) > Same In (DEX) >> Op Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Massacre', operationalNotation: 'Clip >> Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(BOD)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Maverick', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Merlin', operationalNotation: 'Toe >> Op In (DEX) > (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Moby Dick', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same In (DEX) > Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Mofly', operationalNotation: 'Clip >> Op In (DEX) > (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Moirius', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX)(BOD) > Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Morpheus', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> Op In (DEX)(PDX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Motion', operationalNotation: 'Toe >> Same Out (DEX) >> Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Motion Sickness', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op Out (DEX) > Same Out (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Muerto', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'MXZYPTLK' },
    { displayName: 'Nallegam', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nebula', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op In (DEX)(XDEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nemesis Swirl' },
    { displayName: 'Neutron Smasher', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nobius', operationalNotation: 'Clip > (back) Spin (BOD) > Same In (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nuclear Illusion' },
    { displayName: 'Nuclear Legover' },
    { displayName: 'Nuclear Pickup' },
    { displayName: 'Nullwalk', operationalNotation: 'Clip > Op In (DEX) > Same Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ocean', operationalNotation: 'Toe >> Op Out (DEX) > Same Out (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Odula', operationalNotation: 'Clip > Op In (DEX) >> Dive (BOD) >> Op Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Oh Wheely', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Omelette Du Fromage', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op Out (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Original Barroque', operationalNotation: 'Clip >> Op In (DEX) > Same In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Orpheus', operationalNotation: 'Toe >> Same Out (DEX) > Same Out (DEX)(XDEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Osmosis', operationalNotation: 'Toe > Op In (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Overlord', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Same Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pandemonium', operationalNotation: 'Toe > Same In (DEX) >> (no plant while) Op Out (DEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pandora`s Box', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same In (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Paradox Symposium Whirling Rake' },
    { displayName: 'Paradox Whirling Rake' },
    { displayName: 'Parallax', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Paratoxic', operationalNotation: 'Clip >> Same In (DEX) > (no plant while) Op Front Whirl (DEX)(XDEX)(BOD)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Park Avenue', operationalNotation: 'Toe > Same Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pdx Dada Curve' },
    { displayName: 'Pdx DLO' },
    { displayName: 'Pdx Illusion' },
    { displayName: 'Pdx Whirling Swirl' },
    { displayName: 'Phase', operationalNotation: 'Toe > Same Out (DEX) > Op Back Swirl (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Philibuster', operationalNotation: 'Toe > Same Out (DEX) > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Phobia', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pixie Ducking Legover' },
    { displayName: 'Pixie Ducking Mirage' },
    { displayName: 'Pixie Ducking Pickup' },
    { displayName: 'Pixie Eggbeater' },
    { displayName: 'Pixie Legover' },
    { displayName: 'Pixie Osis', operationalNotation: 'Toe > Same In (DEX) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pixie Pickup' },
    { displayName: 'Pixie Quantum Butterfly' },
    { displayName: 'Pixie Symposium Illusion' },
    { displayName: 'Pixie Symposium Mirage' },
    { displayName: 'Pixie Torque' },
    { displayName: 'Pixie Whirl' },
    { displayName: 'POD', operationalNotation: 'Toe > Same In (DEX) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Porque', operationalNotation: 'Toe > Same In (DEX) >> Op In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Predator', operationalNotation: 'Toe > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'PS Illusion' },
    { displayName: 'PS Mirage' },
    { displayName: 'Pteradon', operationalNotation: 'Toe >> Op Out (DEX) >> Same Out (DEX) >> Op Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Puck', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Quagmire', operationalNotation: 'Toe > Op In (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Quantanamera', operationalNotation: 'Toe > Op In (DEX) >> Duck (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Quantum Butterfly (same side)' },
    { displayName: 'Quantum Illusion' },
    { displayName: 'Quantum Legover' },
    { displayName: 'Quantum Mirage' },
    { displayName: 'Quantum Osis' },
    { displayName: 'Quantum Pickup (same side)' },
    { displayName: 'Quark', operationalNotation: 'Toe > Op In (DEX) >> Op In (DEX)(XDEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Rage', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> (no plant while) Op In (DEX)(XDEX)(BOD)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Rail Warrior', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Duck (BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Raildown', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Railplant', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Railwalk', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Rasmus', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Reactor', operationalNotation: 'Toe > Op Out (DEX) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Red Ribbon', operationalNotation: 'Clip >> Dive (BOD) >> Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Redwetter', operationalNotation: 'Clip > Op In (DEX) > Op Out (DEX)(PDX) >> Op Out (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Reverse Swirling Osis' },
    { displayName: 'Reverse Whirling Rake' },
    { displayName: 'Revstein', operationalNotation: 'Clip >> Same Front Swirl (DEX) >> Same Fornt Swirl (DEX)(XDEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Ricochet', operationalNotation: 'Toe >> Op Out (DEX) >> Same Out (DEX) > Op Flapper (XBD)(UNS)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ripcurl', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ripped Warrior', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Riptide', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ropaduleo', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Royall Assassin', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> (no plant while) Op In (DEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'S&M Smasher', operationalNotation: 'Toe > Op Out (DEX) >> Op In (DEX)(XDEX) > Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Sabotage', operationalNotation: 'Toe >> Op In (DEX) > Same In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Saildown', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Sasquatch', operationalNotation: 'Clip > Op In (DEX) >> (no plant while) Op Front Whirl (DEX)(BOD)(PDX) > Op XBD Rake (XBD)(DEL)(DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Scorpion\'s Tail', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Scorpions Toe Nail' },
    { displayName: 'Shaft', operationalNotation: 'Clip >> (no plant while) Op Out (DEX)(BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Shmoe', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Singularity', operationalNotation: 'Clip >> (no plant while) Op Front Whirl (DEX)(BOD) >> Op Flapper (XBD)(UNS)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Slap', operationalNotation: 'Toe > Op In (DEX) >> Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Slapdown', operationalNotation: 'Toe > Op In (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Slapstick', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Same Front Whirl (DEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Smashwalk', operationalNotation: 'Toe > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Smile', operationalNotation: 'Clip > Same Back Swirl (DEX) > Op In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Snapdragon', operationalNotation: 'Clip >> Same Front Swirl (DEX) >> Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Snowflake', operationalNotation: 'Clip >> Same In (DEX)(PDX) > Same XBD Rake (XBD)(DEL)DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Spanish Fly', operationalNotation: 'Clip >> Duck (BOD) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Spikehammer', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) > Op In (DEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Spinning Butterfly Swirl' },
    { displayName: 'Spinning Ducking Butterfly' },
    { displayName: 'Spinning Ducking Clipper' },
    { displayName: 'Spinning Ducking Osis' },
    { displayName: 'Spinning Ducking Pdx Mirage' },
    { displayName: 'Spinning Pdx DLO' },
    { displayName: 'Spinning Pdx Illusion' },
    { displayName: 'Spinning Pdx Mirage' },
    { displayName: 'Spinning Pdx Whirl' },
    { displayName: 'Spitfire', operationalNotation: 'Clip >> (same) Back Swirl (DEX) >> Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'low' },
    { displayName: 'Spyro Gyro', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Stampede', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same In (DEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Stepping Blender (same side)' },
    { displayName: 'Stepping Clipper (same side)' },
    { displayName: 'Stepping Ducking Butterfly (same side)' },
    { displayName: 'Stepping Ducking DLO' },
    { displayName: 'Stepping Ducking Far Double Pickup' },
    { displayName: 'Stepping Ducking PS Whirl', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Stepping Eggbeater', operationalNotation: 'CLIP > OP IN [DEX] (plant) > SAME OUT [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping far Clipper' },
    { displayName: 'Stepping Illusion (same side)' },
    { displayName: 'Stepping Legover (same side)' },
    { displayName: 'Stepping Mirage (same side)' },
    { displayName: 'Stepping Pdx Torque' },
    { displayName: 'Stepping Pickup' },
    { displayName: 'Sumo Thong', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Sunilwalker', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Super Ego', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op Front Whirl (DEX)(XDEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Superdeeduperfly', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Superduperfly', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Op Out (DEX)(BOD) > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Supernova', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Surging Ducking Paradox Torque' },
    { displayName: 'Swifter', operationalNotation: 'Clip >> Same In (DEX)(PDX) > Same Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Swirlwind', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Op Front Whirl (DEX)(BOD)(PDX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Swivel', operationalNotation: 'Clip >> (no plant while) Same Front Swirl (DEX)(BOD) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Syberian Express', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Symp Illusion' },
    { displayName: 'Symp Mirage', operationalNotation: 'SET > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Symp Whirl' },
    { displayName: 'Symple Butterfly' },
    { displayName: 'Symple Reverse Swirl (far)' },
    { displayName: 'Symple Swirl (far)' },
    { displayName: 'Symposium Down Double Down' },
    { displayName: 'Symposium Eggbeater' },
    { displayName: 'Tap Dance', operationalNotation: 'Toe > Same In (DEX) >> Same Out (DEX) > Same In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tapwater', operationalNotation: 'Toe > Op Out (DEX) >> Op Front Swirl (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Terminator', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Op In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Timberwulff', operationalNotation: 'Clip > Op In (DEX) >> (front) Spin (BOD) >> Same In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tobius', operationalNotation: 'Toe >> (back) Spin (BOD) >> Op In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tofu', operationalNotation: 'Toe > Op In (DEX) >> Op Front Whirl (DEX)(XDEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Torch-r Rack', operationalNotation: 'Clip > Op In (DEX) >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tornado', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Torquescrew', operationalNotation: 'Clip >> Op In (DEX) > Op Back Whirl (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Torus', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tremor', operationalNotation: 'Toe > Op Out (DEX) >> Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Triadon', operationalNotation: 'Toe >> Op Out (DEX) > Same Out (DEX)(XDEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Triage', operationalNotation: 'Toe >> Op In (DEX) > Same In (DEX)(XDEX) >> Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Trifly', operationalNotation: 'Clip >> Same Out (DEX) >> Same Out (DEX)(XDEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Triple ATW in-out' },
    { displayName: 'Triple ATW out-in' },
    { displayName: 'Trixie', operationalNotation: 'Toe > Same In (DEX) >> Same In (DEX) >> Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Trochus', operationalNotation: 'Toe > Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tunguska', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tutifruti', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Twirl', operationalNotation: 'Clip >> Same Front Swirl (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Vertigo', operationalNotation: 'Clip >> Duck (BOD) >> Same In (DEX)(PDX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Voodoo', operationalNotation: 'Clip >> Same In (DEX)(PDX) > (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Wahnsinn', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> (front) Spin (BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Warp', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) > Op Out (DEX)(XDEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Weaving Butterfly' },
    { displayName: 'Weaving Clipper' },
    { displayName: 'Weaving Legover' },
    { displayName: 'Weaving Osis' },
    { displayName: 'Weaving Pickup' },
    { displayName: 'Weaving Whirl' },
    { displayName: 'Wentletrappe', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whale Tail', operationalNotation: 'Clip > (back) Spin (BOD) > Same In (DEX) >> Op Out (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'What!?' },
    { displayName: 'Whirling far Butterfly' },
    { displayName: 'Whirling pdx Mirage' },
    { displayName: 'Whirling Rake' },
    { displayName: 'Whirlwalk', operationalNotation: 'Clip > Front Whirl (DEX) >> Op Front Whirl (DEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whirlygig', operationalNotation: 'Clip > Op In (DEX) >> (no plant while) Op Front Whirl (DEX)(BOD)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whirr', operationalNotation: 'Clip >> Op Front Whirl (DEX) >> Same Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whisk', operationalNotation: 'Clip >> (no plant while) Same Out (DEX)(BOD)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Wookie', operationalNotation: 'Toe > Same In (DEX) > (no plant while) Op In (DEX)(BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Yoda', operationalNotation: 'Toe > Same In (DEX) >> Op In (DEX) > Plant > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Your Mom', operationalNotation: 'Toe > Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Your Sister', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same Out (DEX)(XDEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Zig Zag', operationalNotation: 'Clip > Same Back Swirl (DEX) >> Same Front Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Zipwalk', operationalNotation: 'XBD Toe > Op In (DEX) >> Op Out (DEX) > Op XBD Toe (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'low' },
    { displayName: 'Zulu Le Loup', operationalNotation: 'Clip >> Dive (BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)[/quote]', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Zulu Legover' },
    { displayName: 'Zulu Osis' },
    { displayName: 'Zulu Pickup' },
    { displayName: 'Zulu Whirl' },
  ] },
  { sourceLabel: 'footbag.org', names: [
    { displayName: 'Around the World Kick' },
    { displayName: 'Atomic Eclipse', operationalNotation: 'TOE > OP OUT [DEX] > (JUMP) [BOD] > OP INSIDE [DEL] > OP OUT [DEX] > (LAND)', formulaProvenance: 'footbag.org' },
    { displayName: 'Backside Symposium Smear', operationalNotation: 'TOE > SAME IN [DEX] > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Backside Symposium Toe Blizzard', operationalNotation: 'TOE > OP IN [DEX] > (no plant while) OP OUT [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Backside Symposium Toe Blur', operationalNotation: 'TOE > OP IN [DEX] > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Barfly Swirl', operationalNotation: 'CLIP > SAME OUT [DEX] > SAME OUT [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Blistering Whirl', operationalNotation: 'CLIP > OP IN [DEX] > (back) SPIN [BOD] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Blurry Symposium Whirl', operationalNotation: 'CLIP > OP IN [DEX] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Blurry Whirling Swirl', operationalNotation: 'CLIP > OP IN [DEX] > OP IN [PDX] [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Bubba', operationalNotation: 'CLIP > OP OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Butterfly Kick', operationalNotation: 'SET > JUMP [BOD] > SAME or OP OUT [DEX] > OP CLIP [XBD]', formulaProvenance: 'footbag.org' },
    { displayName: 'Clipper Kick', operationalNotation: 'CLIP [XBD]', formulaProvenance: 'footbag.org' },
    { displayName: 'Da Da Curve', operationalNotation: 'CLIP > OP IN [DEX] > (NO PLANT WHILE) OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double Around the World Heel', operationalNotation: 'TOE > SAME IN/OUT [DEX] > SAME IN/OUT [DEX] > SAME HEEL [UNS] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double Blender', operationalNotation: 'SET > OP IN [DEX] > OP IN [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double Pickup', operationalNotation: 'CLIP > OP IN [DEX] > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double Switch-Over', operationalNotation: 'SET > OP OUT [DEX] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double-Over Down', operationalNotation: 'TOE > SAME OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double-Over Down Swirl', operationalNotation: 'TOE > SAME OUT [DEX] > SAME OUT [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Down Double-Down', operationalNotation: 'CLIP > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Dragon' },
    { displayName: 'Ducking Barfly', operationalNotation: 'CLIP > DUCK [BOD] > SAME OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Butterfly', operationalNotation: 'TOE > SAME OUT [DEX] > OP OUT [DEX] > OP CLIP [XBD] [DEL].', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Clipper', operationalNotation: 'TOE > SAME OUT [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Drifter', operationalNotation: 'TOE > SAME OUT [DEX] > OP IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Leg Over', operationalNotation: 'TOE > SAME OUT [DEX] > OP OUT [DEX] > SAME TOE [DEL].', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Merkon', operationalNotation: 'TOE > SAME OUT [DEX] > (back) SPIN [BOD] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Same Side Mirage', operationalNotation: 'TOE > SAME OUT [DEX] (plant) > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Same Side Whirl', operationalNotation: 'TOE > SAME OUT [DEX] (plant) > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Spyro Mirage', operationalNotation: 'TOE > SAME OUT [DEX] > (back) SPIN [BOD] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Frigidosis' },
    { displayName: 'Hop Over Swirl', operationalNotation: 'INSIDE > (JUMP) [BOD] > OP SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Paradox Illusion', operationalNotation: 'CLIP > (front) SPIN [BOD] > SAME OUT [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Paradox Mirage', operationalNotation: 'CLIP > (front) SPIN [BOD] > SAME IN [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Same Side Butterfly', operationalNotation: 'CLIP > (front) SPIN [BOD] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Same Side Illusion', operationalNotation: 'CLIP > (front) SPIN [BOD] > OP OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Same Side Mirage', operationalNotation: 'CLIP > (front) SPIN [BOD] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Leg-Over Flapper Stall', operationalNotation: 'TOE > OP OUT [DEX] > OP SOLE [XBD] [UNS] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Miraging Eclipse', operationalNotation: 'SET > OP IN [DEX] > (JUMP) [BOD] > OP INSIDE [DEL] > OP OUT [DEX] > (LAND)', formulaProvenance: 'footbag.org' },
    { displayName: 'Miraging Pincher', operationalNotation: 'CLIP > OP IN [DEX] > OP PINCHER [UNS] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Nuclear Whirl', operationalNotation: 'CLIP > SAME OUT [PDX] [DEX] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pandora', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradon Swirl', operationalNotation: 'TOE > OP OUT [DEX] > SAME OUT [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Barrage', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Blizzard', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP OUT [DEX] > OP TOE [DEL].', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Blur', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Blurry Whirl', operationalNotation: 'CLIP > SAME IN [DEX] [BOD] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Da Da Curve', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > (NO PLANT WHILE) OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Double Leg Over', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox High Plains Drifter', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > SAME IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Illusion', operationalNotation: 'CLIP > SAME OUT [PDX[DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Ripwalk', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] (plant) > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Symposium Mirage', operationalNotation: 'CLIP (plant) > (no plant while) SAME IN [PDX] [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Whirling Swirl', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paralax', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Double Over Down', operationalNotation: 'TOE > SAME IN [DEX] (plant) > SAME OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Eclipse', operationalNotation: 'TOE > SAME IN [DEX] (JUMP) [BOD] > SAME INSIDE [DEL] > OP OUT [DEX] > (LAND)', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Leg Over', operationalNotation: 'TOE > SAME IN [DEX] > OP IN/OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Opposite Clipper', operationalNotation: 'TOE > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Paradon', operationalNotation: 'TOE > SAME IN [DEX] > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Same Clipper', operationalNotation: 'TOE > SAME IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Same Side Illusion', operationalNotation: 'TOE > SAME IN [DEX] (plant) > SAME OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Swirl', operationalNotation: 'TOE > SAME IN [DEX] > SAME/OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Barfly', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Butterfly', operationalNotation: 'CLIP > (NO PLANT WHILE) OP IN [DEX] [BOD] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Barrage', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Blender', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Da Da Curve', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (no plant while) OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Drifter', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Eggbeater', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP OUT [PDX] [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Mirage', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [DEX] [BOD] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Torque', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (back) SPIN [BOD] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Whirl', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Whirling Swirl', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Pickup', operationalNotation: 'CLIP > (NO PLANT WHILE) OP IN [DEX] > OP IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Voodoo', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Probe' },
    { displayName: 'Quantum Drifter', operationalNotation: 'TOE > OP IN [DEX] > OP IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Quantum Whirl', operationalNotation: 'TOE > OP IN [DEX] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Reverse Magellan', operationalNotation: 'TOE > SAME OUT [DEX] (plant) > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Butterfly', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Mirage', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Star', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Torque', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP IN [DEX] > (back) SPIN [BOD] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spike Hammer', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > OP IN [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Butterfly Kick', operationalNotation: 'CLIP > (back) SPIN [BOD] > JUMP [BOD] > OP OUT [DEX] > OP CLIP [XBD]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Blender', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP IN [PDX] [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Illusion', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP OUT [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Mirage', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP IN [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Whirl', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP IN [PDX] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Symposium Down Double Down', operationalNotation: 'CLIP > (back) SPIN [BOD] > (no plant while) > OP OUT [BOD] [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spyro Illusion', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spyro Mirage', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spyro Whirl', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Ducking Mirage', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Ducking Paradox Blender', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > OP IN [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Opposite Reaper', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [DEX] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Opposite Side Reverse Whirl', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping P.S. Whirling x-body Rake', operationalNotation: 'CLIP > OP IN [DEX] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP X-BODY RAKE [XBD] [DEL] [DEX]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Whirling Swirl', operationalNotation: 'CLIP > OP IN [DEX] (plant) > SAME IN [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Blizzard', operationalNotation: 'CLIP > OP IN [DEX] > (NO PLANT WHILE) OP OUT [BOD] [DEX] [BOD] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Blur', operationalNotation: 'CLIP > OP IN [DEX] > (NO PLANT WHILE) OP IN/OUT [DEX] [BOD] [BOD] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Double Leg Over', operationalNotation: 'SET > (no plant while) OP IN [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Pixie', operationalNotation: 'TOE (plant) > (no plant while) SAME IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Reverse Whirl', operationalNotation: 'SET > (no plant while) OP OUT [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Tomahawk', operationalNotation: 'CLIP > DUCK [BOD] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Torque', operationalNotation: 'SET > (NO PLANT WHILE) OP IN [DEX] [BOD] > (BACK) SPIN [BOD] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Whirling Swirl', operationalNotation: 'CLIP > (NO PLANT WHILE) OP IN [DEX] [BOD] > OP IN SWIRL [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Tapping Illusion', operationalNotation: 'TOE > OP OUT [DEX] (plant) > SAME OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Terraging Opposite Clipper', operationalNotation: 'TOE > SAME IN [DEX] > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Terraging Same Clipper', operationalNotation: 'TOE > SAME IN [DEX] > SAME IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Blizzard', operationalNotation: 'TOE > OP IN [DEX] > OP OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Clipper' },
    { displayName: 'Toe Double Drifter', operationalNotation: 'TOE > OP IN [DEX] > SAME IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Ripwalk', operationalNotation: 'TOE > OP IN [DEX] (plant) > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Whirr', operationalNotation: 'TOE > OP IN [DEX] > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Triple Around The World', operationalNotation: 'TOE > SAME IN/OUT [DEX] > SAME IN/OUT [DEX] > SAME IN/OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Triple Spin', operationalNotation: '[BOD] [BOD] [BOD]', formulaProvenance: 'footbag.org' },
    { displayName: 'Wrap' },
  ] },
  { sourceLabel: 'PassBack', names: [
    { displayName: 'Alpine Blurry Whirl' },
    { displayName: 'Alpine Magellan' },
    { displayName: 'Alpine Paste' },
    { displayName: 'Alpine Pigbeater' },
    { displayName: 'Alpine PLO' },
    { displayName: 'Alpine Smog' },
    { displayName: 'Alpine Smudge' },
    { displayName: 'Blazing Butterfly' },
    { displayName: 'Blink' },
    { displayName: 'BS Magellan' },
    { displayName: 'BS Paste' },
    { displayName: 'DDD' },
    { displayName: 'Diving Clipper' },
    { displayName: 'Diving Mirage' },
    { displayName: 'Diving Smudge' },
    { displayName: 'Double Dyno' },
    { displayName: 'Double Fairy' },
    { displayName: 'Double Orbit' },
    { displayName: 'Double Spinning Butterfly' },
    { displayName: 'Double Whip' },
    { displayName: 'DSO' },
    { displayName: 'Ducking Pdx Torque' },
    { displayName: 'Fairy DLO (ss)' },
    { displayName: 'Frantic Legover' },
    { displayName: 'Gyro Symp Swirl' },
    { displayName: 'Gyro Toe' },
    { displayName: 'Gyro Whirling Swirl' },
    { displayName: 'Infinity' },
    { displayName: 'Infinity Swirl' },
    { displayName: 'Pixie Double Pickup (ss)' },
    { displayName: 'Pixie DSO' },
    { displayName: 'PLO' },
    { displayName: 'Solestice' },
    { displayName: 'Spanishfly' },
    { displayName: 'Spinning Symp Swirl' },
    { displayName: 'Stepping Ducking Osis' },
    { displayName: 'Symp Eggbeater' },
    { displayName: 'Symp Swirl (op)' },
    { displayName: 'Symp Whirling Swirl' },
    { displayName: 'Tapping Legover' },
    { displayName: 'Tapping Pickup' },
    { displayName: 'Toe Ducking Legover' },
    { displayName: 'Toe Gyro Mirage' },
    { displayName: 'Toe Spinning Toe' },
    { displayName: 'Triple Orbit' },
    { displayName: 'Void' },
    { displayName: 'Weaving Magellan' },
    { displayName: 'Weaving Pigbeater' },
    { displayName: 'Zulu Clipper' },
  ] },
];
