/**
 * Freestyle editorial content.
 *
 * Authored and curated by James (pipeline-side analytical work) and
 * incorporated here as static, non-DB-backed content for the freestyle
 * Insights page (`/freestyle/insights`): analytical snapshots of the
 * freestyle competition dataset.
 *
 * Why this module exists separately from `src/services/freestyleService.ts`:
 * the data here is CONTENT, not service logic. Putting it in a service file
 * violates the "services own use-case logic, not editorial data" boundary;
 * roughly 200 lines of hardcoded editorial arrays previously lived in
 * `freestyleService.ts` and were extracted here.
 *
 * What is in here:
 *   1. Type interfaces describing each content shape (consumed by
 *      freestyleService when building its page view-models).
 *   2. The actual content constants: hand-curated tables of trick usage,
 *      transitions, sequences, player diversity, difficulty eras, and
 *      narrative paragraphs.
 *
 * What is NOT in here:
 *   - Live DB-derived data (records, leaderboards). Those live in
 *     `freestyleService` and query the `freestyle_records` table.
 *   - View-model types that compose editorial + live data (e.g.,
 *     `FreestyleInsightsContent`). Those stay in `freestyleService` because
 *     they are the service's contract with the controller.
 *
 * Maintenance model:
 *   - This file is the canonical home for the editorial text. Edits land
 *     here via code review, not through an admin UI. There is no DB
 *     round-trip; changes deploy with the codebase.
 *   - Source material (the original CSV and Markdown report) is a curated
 *     pipeline output. If that source is regenerated by a future pipeline
 *     run, this module must be updated by hand to match. No
 *     auto-regeneration is wired.
 *
 * Source provenance:
 *   - INSIGHTS_* tables: illustrative content. Trick names carry their current
 *     canonical ADD; example chains carry the exact sum of current canonical ADD
 *     values. The exact corpus-derived counts and rankings they once held were
 *     removed because that sequence corpus is not reproducible from committed
 *     sources.
 *   - INSIGHTS_NARRATIVES: editorial prose (not rendered on the public page).
 *
 * Consumers:
 *   - `src/services/freestyleService.ts` imports the interfaces and
 *     constants; packages them into the `FreestyleInsightsContent` page
 *     view-model.
 *   - No other file should import from here. If a second surface needs
 *     this data, it's probably a sign the data should be DB-backed;
 *     revisit the editorial-vs-scaffolding decision before adding a
 *     second consumer.
 */

// ─── Insights type interfaces ────────────────────────────────────────────────
//
// Each `INSIGHTS_*` constant below is typed by one of these interfaces. The
// interfaces are exported so `freestyleService` can use them when declaring
// its `FreestyleInsightsContent` view-model shape.

export interface InsightsTrick {
  name: string;
  adds: string;      // current canonical ADD value (reproducible from the dictionary)
}

export interface InsightsTransition {
  from: string;
  to: string;        // an illustrative transition pair (an example, not a measured count)
}

export interface InsightsSequence {
  sequence: string;
  adds: number;      // sum of current canonical ADD values for the chain
  length: number;    // number of tricks in the chain
}

export interface InsightsDifficultyEra {
  era: string;
  chains: number;
  avgAdd: number;
}

// ─── Insights data: illustrative tables ──────────────────────────────────────
//
// These tables originally carried exact figures (mention counts, connection
// counts, transition counts, chain scores, per-player diversity counts) from a
// sequence analysis whose corpus is not reproducible from any committed source.
// Those unsupported numbers have been removed. What remains is reproducible or
// explicitly illustrative: trick names with their current canonical ADD, example
// transition pairs, and example chains whose ADD is the exact sum of the current
// canonical ADD values of their tricks (verified against the dictionary), shown
// as canonical arithmetic rather than recovered historical scores.
//
// The modifier-usage table is computed live from the dictionary in the service
// and is not stored here.

// Tricks that recur across the documented record, with their current canonical
// ADD. An illustrative selection, not an exact frequency ranking (the occurrence
// counts came from a sequence corpus that is not reproducible from committed
// sources, so they are not shown).
export const INSIGHTS_MOST_USED: InsightsTrick[] = [
  { name: 'whirl',        adds: '3' },
  { name: 'pixie',        adds: 'modifier' },
  { name: 'swirl',        adds: '3' },
  { name: 'blurry whirl', adds: '5' },
  { name: 'torque',       adds: '4' },
  { name: 'ducking',      adds: 'modifier' },
  { name: 'ripwalk',      adds: '4' },
  { name: 'butterfly',    adds: '3' },
  { name: 'spinning',     adds: 'modifier' },
  { name: 'legover',      adds: '2' },
  { name: 'mirage',       adds: '2' },
  { name: 'dimwalk',      adds: '4' },
  { name: 'symposium',    adds: 'modifier' },
  { name: 'blender',      adds: '4' },
  { name: 'eggbeater',    adds: '3' },
];

// Tricks that commonly act as connectors between others in a sequence, with their
// current canonical ADD. Illustrative, not a graph-score ranking (the connection
// counts came from the same non-reproducible corpus and are not shown).
export const INSIGHTS_CONNECTORS: InsightsTrick[] = [
  { name: 'whirl',             adds: '3' },
  { name: 'blurry whirl',      adds: '5' },
  { name: 'ripwalk',           adds: '4' },
  { name: 'butterfly',         adds: '3' },
  { name: 'torque',            adds: '4' },
  { name: 'dimwalk',           adds: '4' },
  { name: 'swirl',             adds: '3' },
  { name: 'mirage',            adds: '2' },
  { name: 'ducking butterfly', adds: '4' },
  { name: 'legover',           adds: '2' },
];

// Illustrative transitions: example from->to pairs, not measured occurrence
// counts. They show the structural pattern (a high-difficulty rotational opener
// resolving to a stable closer; walking tricks connecting mid-chain), not a
// frequency ranking from the non-reproducible corpus.
export const INSIGHTS_TRANSITIONS: InsightsTransition[] = [
  { from: 'blurry whirl', to: 'whirl' },
  { from: 'ripwalk',      to: 'whirl' },
  { from: 'whirl',        to: 'whirl' },
  { from: 'smear',        to: 'dimwalk' },
  { from: 'dimwalk',      to: 'ripwalk' },
  { from: 'torque',       to: 'whirl' },
];

// Example high-ADD chains. Each `adds` is the sum of the CURRENT canonical ADD
// values of the tricks in the chain (verified against the dictionary), presented
// as canonical arithmetic, not a recovered historical competition score. The
// player/year attributions from the original corpus are omitted because that
// provenance is not independently available; only chains whose tricks all resolve
// canonically and whose totals are exact canonical sums are kept.
export const INSIGHTS_SEQUENCES: InsightsSequence[] = [
  { sequence: 'butterfly > whirl > osis > dimwalk > osis > butterfly > swirl', adds: 22, length: 7 },
  { sequence: 'blurry whirl > ripwalk > whirl > pixie > paradox whirl',        adds: 18, length: 5 },
  { sequence: 'ripwalk > blurry whirl > smear > dimwalk',                      adds: 16, length: 4 },
  { sequence: 'blurry whirl > paradox torque > paradox blender',              adds: 15, length: 3 },
  { sequence: 'ducking butterfly > food processor > mobius',                  adds: 15, length: 3 },
];

export const INSIGHTS_DIFFICULTY_ERAS: InsightsDifficultyEra[] = [
  { era: '2001–2003', chains: 29,  avgAdd: 3.52 },
  { era: '2004–2006', chains: 93,  avgAdd: 3.46 },
  { era: '2007–2009', chains: 118, avgAdd: 3.30 },
  { era: '2010–2015', chains: 53,  avgAdd: 3.26 },
  { era: '2016–2025', chains: 82,  avgAdd: 3.12 },
];

export const INSIGHTS_NARRATIVES: string[] = [
  'From a network perspective, freestyle sequences exhibit a clear directional structure. ' +
  'Blurry whirl functions as the primary launch node, initiating high-difficulty sequences, ' +
  'while whirl serves as the dominant attractor, acting as the most common resolution point. ' +
  'This creates a highly asymmetric flow pattern: sequences tend to begin with high-complexity ' +
  'rotational entries and resolve into more stable, clipper-based terminations.',

  'The plateau in average ADD after 2007 suggests that freestyle did not continue to increase ' +
  'in raw technical difficulty after the mid-2000s. Instead, progress shifted toward consistency, ' +
  'execution quality, and the number of players capable of reaching the established ceiling, ' +
  'a transition from technical expansion to competitive depth.',

  'The dataset shows no sustained increase in single-trick difficulty beyond 6 ADD: that is where ' +
  'routine competitive difficulty concentrates, while the rarer landings above it stay exceptional ' +
  'rather than routine (8 ADD is the highest currently video-corroborated landing). This sustained ' +
  'plateau suggests a practical limit imposed by human biomechanics: finite airtime, constraints on ' +
  'rotational speed, increasing coordination complexity with stacked modifiers, and the requirement ' +
  'for controlled stall completion.',

  'The concentration of both podium finishes and high-difficulty sequence data among European ' +
  'players indicates that the competitive center of freestyle shifted geographically during this ' +
  'period. While early innovation was driven largely by North American players, the post-2005 era ' +
  'is characterized by European dominance in both performance and participation density.',

  'Freestyle footbag evolved through two distinct phases: an early period of rapid innovation in ' +
  'which the core vocabulary was established, followed by a mature phase in which that vocabulary ' +
  'was fully exploited. Progress is now defined not by new elements, but by the refinement and ' +
  'recombination of existing ones.',
];

// ─── Insights narratives: editorial prose analysis ───────────────────────────
//
// Five paragraphs of analytical commentary rendered as the narrative section
// of `/freestyle/insights`. Authored as editorial text; edits land here
// via code review, not live rebuilds.

