// freestyleTrackedNames.ts
// ============================
// GENERATED FILE — do not hand-edit.
// Regenerate: python3 legacy_data/scripts/build_tracked_names_content.py
//
// Documented freestyle trick names tracked in the project vocabulary
// corpus that are NOT yet canonically published, grouped by
// documenting source. Where the reconciliation master already records
// a symbolic / operational notation, it is carried verbatim — no
// formula is invented or derived, and no ADD claim is made.
//
// Grouped by SOURCE, not ADD: the /freestyle/observational page
// contract forbids grouping by external ADD claim.
//
// Source: the 2026-05-21 cross-source vocabulary reconciliation audit
// + SYMBOLIC_GRAMMAR_MASTER.csv (symbolic_notation_raw).
// Reversible content module per [[feedback_reversible_content_governance]].

export interface TrackedName {
  /** Trick name as documented by the source. */
  readonly displayName: string;
  /** Stable slug — the tag-like identity, shown as a #slug tracked tag. */
  readonly slug: string;
  /** Symbolic / operational notation, verbatim from the reconciliation
   *  master where one is already recorded. Absent when none exists. */
  readonly operationalNotation?: string;
  /** Corpus the notation was recorded in. */
  readonly formulaProvenance?: string;
  /** Parser confidence in the notation, where recorded. */
  readonly formulaConfidence?: string;
}

export interface TrackedNameGroup {
  /** Documenting-source display label, e.g. "FootbagMoves". */
  readonly sourceLabel: string;
  /** Trick names primarily documented by this source, alphabetical. */
  readonly names: readonly TrackedName[];
}

/** Total tracked-but-unpublished names across all sources. */
export const TRACKED_UNPUBLISHED_TOTAL = 551;

export const TRACKED_UNPUBLISHED_NAMES: readonly TrackedNameGroup[] = [
  { sourceLabel: 'FootbagMoves', names: [
    { displayName: '69', slug: '69', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Op In (DEX)(XDEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: '84', slug: '84', operationalNotation: 'Toe > Same In (DEX) > Same Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Aeon Flux', slug: 'aeon-flux', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Alex Zerbe is the greatest', slug: 'alex-zerbe-is-the-greatest', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Alpine Big Apple', slug: 'alpine-big-apple' },
    { displayName: 'Amadeus', slug: 'amadeus', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same In (DEX) > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Anoxia', slug: 'anoxia', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> (no plant while) Op In (DEX)(PDX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Apocalypse', slug: 'apocalypse', operationalNotation: 'Toe > Same In (DEX) >> Op In (DEX) > (no plant while) Op In (DEX)(XDEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Arachnophobia', slug: 'arachnophobia', operationalNotation: 'Clip > Op In (DEX) >> Dive (BOD) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Arch Nemesis', slug: 'arch-nemesis', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Arcwalk', slug: 'arcwalk', operationalNotation: 'Frigidosis > Same In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Atom Bomb', slug: 'atom-bomb', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Atomic DLO', slug: 'atomic-dlo' },
    { displayName: 'Atomic Drifter', slug: 'atomic-drifter' },
    { displayName: 'Atomic Illusion', slug: 'atomic-illusion' },
    { displayName: 'Atomic Legover (same side)', slug: 'atomic-legover' },
    { displayName: 'Atomic Osis', slug: 'atomic-osis' },
    { displayName: 'Atomic Pickup (same side)', slug: 'atomic-pickup' },
    { displayName: 'Atomic ss Osis', slug: 'atomic-ss-osis' },
    { displayName: 'Atomotion', slug: 'atomotion', operationalNotation: 'Toe > Op Out (DEX) >> Op Out (DEX)(XDEX) > Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Avalanche', slug: 'avalanche', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Barfry', slug: 'barfry', operationalNotation: 'Clip > Same Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Barroque', slug: 'barroque', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bedwetter', slug: 'bedwetter', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Big Apple Sauce', slug: 'big-apple-sauce', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op In (DEX)(PDX) > (no plant while) Op In (DEX)(XDEX)(BOD) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Big Papa Smurf', slug: 'big-papa-smurf', operationalNotation: 'Toe > Same Out (DEX) > (no plant while) Op Back Swirl (DEX)(BOD) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bill & Ted`s Bogus Journey', slug: 'bill-&-ted`s-bogus-journey', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same In (DEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bill & Ted`s Excellent Adventure', slug: 'bill-&-ted`s-excellent-adventure', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same Out (DEX)(XDEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blacula', slug: 'blacula', operationalNotation: 'Toe >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bladerunner', slug: 'bladerunner', operationalNotation: 'Toe > Op Out (DEX) >> Op Out (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blaze', slug: 'blaze', operationalNotation: 'Clip > Op Front Whirl (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bling Blang', slug: 'bling-blang', operationalNotation: 'Clip > Op Front Whirl (DEX) >> Same Back Swirl (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blister', slug: 'blister', operationalNotation: 'Clip > Op Front Whirl (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blizzard', slug: 'blizzard', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blue Widow', slug: 'blue-widow', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> (no plant while) Same Front Whirl (DEX)(PDX)(BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurrage', slug: 'blurrage', operationalNotation: 'Clip > Op In (DEX) >> Op In (DEX)(PDX) > Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurrier', slug: 'blurrier', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurry Chainsaw Massacre', slug: 'blurry-chainsaw-massacre', operationalNotation: 'Clip >> Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(PDX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Blurry Drifter', slug: 'blurry-drifter' },
    { displayName: 'Boulderbeater', slug: 'boulderbeater', operationalNotation: 'Toe > Op In (DEX) >> Op Out (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Bubba Beater', slug: 'bubba-beater', operationalNotation: 'Clip >> Op Out (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Butterfly Swirl', slug: 'butterfly-swirl' },
    { displayName: 'Buttersole', slug: 'buttersole', operationalNotation: 'Set >> Op Out (DEX) > Op Flapper (XBD)(UNS)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Carousel', slug: 'carousel' },
    { displayName: 'Cascade', slug: 'cascade', operationalNotation: 'Toe >> Duck (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Casket', slug: 'casket', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cataclysm', slug: 'cataclysm', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Catacomb', slug: 'catacomb', operationalNotation: 'Toe > Same In (DEX) >> Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Chainsaw Massacre', slug: 'chainsaw-massacre', operationalNotation: 'Clip >> Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(PDX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Clown Face', slug: 'clown-face', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Out (DEX)(XDEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cold Fusion', slug: 'cold-fusion', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Op Out (DEX)(XDEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Colossus', slug: 'colossus', operationalNotation: 'Clip >> (back) Spin (BOD) > Dive (BOD) >> (no plant while) Same Front Whirl (DEX)(BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Compound Fracture', slug: 'compound-fracture', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Conniption City', slug: 'conniption-city', operationalNotation: 'Toe > Op In (DEX) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cristal', slug: 'cristal', operationalNotation: 'Toe > Op In (DEX) >> Duck (BOD) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Croissant', slug: 'croissant', operationalNotation: 'Toe > Same In (DEX) >> (no plant while) Op Front Whirl (DEX)(BOD) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Croxton', slug: 'croxton', operationalNotation: 'Clip > (no plant while) Op Front Whirl (DEX)(BOD) > Op Back Swirl (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cyborg', slug: 'cyborg', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Cyclone', slug: 'cyclone', operationalNotation: 'Clip > Op In (DEX) > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dark Avenue', slug: 'dark-avenue', operationalNotation: 'Toe > Same Out (DEX) >> Dive (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Darkwalk', slug: 'darkwalk', operationalNotation: 'Toe > Same In (DEX) >> Dive (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dellusion', slug: 'dellusion', operationalNotation: 'Toe >> Op Out (DEX) > Same Out (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Desien', slug: 'desien', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Diving Butterfly', slug: 'diving-butterfly' },
    { displayName: 'Diving Osis', slug: 'diving-osis' },
    { displayName: 'Dolomite', slug: 'dolomite', operationalNotation: 'Toe >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dominatrix', slug: 'dominatrix', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dorshanatrix', slug: 'dorshanatrix', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dorshatrix', slug: 'dorshatrix', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Double Helix', slug: 'double-helix', operationalNotation: 'Clip >> (no plant while) Op Back Whirl (DEX)(BOD) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Double Over Down', slug: 'double-over-down' },
    { displayName: 'Double Spinning Clipper', slug: 'double-spinning-clipper' },
    { displayName: 'Double Spinning Osis', slug: 'double-spinning-osis' },
    { displayName: 'Double Spinning Rake', slug: 'double-spinning-rake' },
    { displayName: 'Double Switchover (far)', slug: 'double-switchover' },
    { displayName: 'Down Diver', slug: 'down-diver', operationalNotation: 'Clip >> Dive (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Down Double Down', slug: 'down-double-down', operationalNotation: 'Clip >> Op Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Downward Spiral', slug: 'downward-spiral', operationalNotation: 'Toe > Same Out (DEX) > Op Back Swirl (DEX) >> Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Dragonstein', slug: 'dragonstein', operationalNotation: 'Clip >> Same Back Swirl (BOD) >> Same Back Swirl (BOD) > Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Dragster', slug: 'dragster', operationalNotation: 'Clip >> Op In (DEX) > Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Ducking Illusion', slug: 'ducking-illusion' },
    { displayName: 'Ducking Legover', slug: 'ducking-legover' },
    { displayName: 'Ducking Pdx Illusion', slug: 'ducking-pdx-illusion' },
    { displayName: 'Ducking Pdx Mirage', slug: 'ducking-pdx-mirage' },
    { displayName: 'Ducking Pickup', slug: 'ducking-pickup' },
    { displayName: 'Ducking PS Illusion', slug: 'ducking-ps-illusion' },
    { displayName: 'Ducking PS Mirage', slug: 'ducking-ps-mirage' },
    { displayName: 'Dwirl', slug: 'dwirl', operationalNotation: 'Clip >> Same Front Swirl (DEX) > Same Front Swirl (DEX)(XDEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'E-Walk', slug: 'e-walk', operationalNotation: 'Toe > Same In (DEX) > Op In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Eggplant', slug: 'eggplant', operationalNotation: 'Toe > Op Out (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ego', slug: 'ego', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Enterrage', slug: 'enterrage', operationalNotation: 'Toe > Same In (DEX) > Same In (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Beater', slug: 'fairy-beater', operationalNotation: 'Toe > Same Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Ducking Butterfly', slug: 'fairy-ducking-butterfly' },
    { displayName: 'Fairy Ducking Legover', slug: 'fairy-ducking-legover' },
    { displayName: 'Fairy Ducking Pickup', slug: 'fairy-ducking-pickup' },
    { displayName: 'Fairy Eggbeater', slug: 'fairy-eggbeater' },
    { displayName: 'Fairy Illusion (same side)', slug: 'fairy-illusion' },
    { displayName: 'Fairy Legover', slug: 'fairy-legover' },
    { displayName: 'Fairy Mirage (same side)', slug: 'fairy-mirage' },
    { displayName: 'Fairy Pickup', slug: 'fairy-pickup' },
    { displayName: 'Fairy ss Osis', slug: 'fairy-ss-osis', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Symposium Mirage', slug: 'fairy-symposium-mirage' },
    { displayName: 'Fairy Tale', slug: 'fairy-tale', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fairy Torque (same side)', slug: 'fairy-torque' },
    { displayName: 'Fairy Whirl', slug: 'fairy-whirl', operationalNotation: 'TOE > SAME OUT [DEX] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Far Dyno', slug: 'far-dyno' },
    { displayName: 'Far Reverse Whirl', slug: 'far-reverse-whirl' },
    { displayName: 'Fear', slug: 'fear', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fender', slug: 'fender', operationalNotation: 'Toe > Same Out (DEX) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fender Bender', slug: 'fender-bender', operationalNotation: 'Toe > Same Out (DEX) >> Duck (BOD) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Feral', slug: 'feral', operationalNotation: 'Toe > Same Out (DEX) >> Op Front Whirl (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ferocious', slug: 'ferocious', operationalNotation: 'Toe > Same Out (DEX) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Firefly', slug: 'firefly', operationalNotation: 'Set >> Op Out (DEX) > Op Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Firewalk', slug: 'firewalk', operationalNotation: 'Clip > (no plant while) Op Front Whirl (DEX)(BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fission', slug: 'fission', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Out (DEX)(XDEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flaming Homer', slug: 'flaming-homer', operationalNotation: 'Toe > Same Out (DEX) >> Same Out (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flaming Tard', slug: 'flaming-tard', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flipwalk', slug: 'flipwalk', operationalNotation: 'Dragon > Op In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Floatation', slug: 'floatation', operationalNotation: 'Toe > (no plant while) Op In (DEX)(BOD) > Op In (DEX)(XDEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flog', slug: 'flog', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flurricane', slug: 'flurricane', operationalNotation: 'Clip >> (back) Spin (BOD > Same In (DEX) > Same In (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Flux', slug: 'flux', operationalNotation: 'Set >> Op Out (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Flying Fish', slug: 'flying-fish', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Forque', slug: 'forque', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Forquelift', slug: 'forquelift', operationalNotation: 'Toe > Same Out (DEX) >> Duck (BOD) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fracture', slug: 'fracture', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Frankenstein', slug: 'frankenstein', operationalNotation: 'Toe > Same Out (DEX) > Op Back Swirl (DEX) >> Same Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Freak', slug: 'freak', operationalNotation: 'Toe > Same Out (DEX) >> Same Crossbody Rake (XBD)(DEL)(DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Frenzy', slug: 'frenzy', operationalNotation: 'Toe > Same In (DEX) > Op In (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fudge', slug: 'fudge', operationalNotation: 'Toe > Same Out (DEX) >> Op Out (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Fume', slug: 'fume', operationalNotation: 'Toe > Same Out (DEX) >> Op In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Furnace', slug: 'furnace', operationalNotation: 'Inside > Jump (BOD >> Same Back Swirl (DEX) > Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'low' },
    { displayName: 'G.Y.B.A.S.', slug: 'gybas', operationalNotation: 'Clip > Op In (DEX) >> Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gangsta Party', slug: 'gangsta-party', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> Op Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gary Coleman', slug: 'gary-coleman', operationalNotation: 'Toe > Op Out (DEX) >> (no plant while) Op Front Whirl (DEX)(XDEX)(BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Genesis', slug: 'genesis', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Front Whirl (DEX)(XDEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Genuphobia', slug: 'genuphobia', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> (no plant while) Op In (DEX)(BOD) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gilan', slug: 'gilan', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Glaucoma', slug: 'glaucoma', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Godzilla', slug: 'godzilla', operationalNotation: 'Clip > Same Out (DEX) >> Same Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Golden Shower', slug: 'golden-shower', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Goliath', slug: 'goliath', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Grifter', slug: 'grifter', operationalNotation: 'Clip >> Op Out (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Guillotine', slug: 'guillotine', operationalNotation: 'Toe > Same Out (DEX) >> Duck (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Gyro Barfly', slug: 'gyro-barfly' },
    { displayName: 'Gyro Blender', slug: 'gyro-blender' },
    { displayName: 'Gyro Butterfly', slug: 'gyro-butterfly' },
    { displayName: 'Gyro Clipper', slug: 'gyro-clipper' },
    { displayName: 'Gyro DLO', slug: 'gyro-dlo' },
    { displayName: 'Gyro Illusion', slug: 'gyro-illusion' },
    { displayName: 'Gyro Mirage', slug: 'gyro-mirage' },
    { displayName: 'Gyro Osis', slug: 'gyro-osis' },
    { displayName: 'Gyro Whirl', slug: 'gyro-whirl' },
    { displayName: 'Heart', slug: 'heart' },
    { displayName: 'Hurl', slug: 'hurl', operationalNotation: 'Clip > Same Out (DEX) >> Same Front Whirl (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Icarus', slug: 'icarus', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Icon', slug: 'icon', operationalNotation: 'Clip >> (front) Spin (BOD) >> Same Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ill Frenzy', slug: 'ill-frenzy', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op Out (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Inspinning Butterfly', slug: 'inspinning-butterfly' },
    { displayName: 'Inspinning Clipper', slug: 'inspinning-clipper' },
    { displayName: 'Inspinning Osis', slug: 'inspinning-osis' },
    { displayName: 'Irish Cream', slug: 'irish-cream', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Irish Spring', slug: 'irish-spring', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Jacknife', slug: 'jacknife', operationalNotation: 'Clip > Op In (DEX) >> Dive (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Janiwalker', slug: 'janiwalker', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Joan', slug: 'joan', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Johny Quest', slug: 'johny-quest', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Johny Vodka', slug: 'johny-vodka', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Op In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Juggernaut', slug: 'juggernaut', operationalNotation: 'Toe > Same Out (DEX) >> (no plant while) Op Out (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Juno Reactor', slug: 'juno-reactor', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kill Frenzy', slug: 'kill-frenzy', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kiss Of The Scorpion', slug: 'kiss-of-the-scorpion', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kiwi', slug: 'kiwi', operationalNotation: 'Toe > Op Out (DEX) >> Same Out (DEX)(XDEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Kyttyrä', slug: 'kyttyrä' },
    { displayName: 'Lawnmoir', slug: 'lawnmoir', operationalNotation: 'Clip > (back) Spin (BOD) > Front Swirl (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Leaning Jowler', slug: 'leaning-jowler', operationalNotation: 'Clip > Op In (DEX) >> (front) Spin (BOD) >> Same In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Legbreaker', slug: 'legbreaker', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Legfreezer', slug: 'legfreezer', operationalNotation: 'Frigidosis > Op Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Leviathan', slug: 'leviathan', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Liquifier', slug: 'liquifier', operationalNotation: 'Clip > (back) Spin (BOD) > (no plant while) Front Swirl (DEX)(BOD) >> Op Front Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Little Apple', slug: 'little-apple', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Locomotion', slug: 'locomotion', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX) > Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Lotus', slug: 'lotus', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op In (DEX)(PDX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Macon Bacon', slug: 'macon-bacon', operationalNotation: 'Clip > Op In (DEX) >> (front) Spin (BOD) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Maelstrom', slug: 'maelstrom', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> Op Front Whirl (DEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Majello', slug: 'majello', operationalNotation: 'Toe > Same In (DEX) >> Same Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Margaritaville', slug: 'margaritaville', operationalNotation: 'Clip > (back) Spin (BOD) > Same In (DEX) >> Op Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Massacre', slug: 'massacre', operationalNotation: 'Clip >> Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(BOD)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Maverick', slug: 'maverick', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Merlin', slug: 'merlin', operationalNotation: 'Toe >> Op In (DEX) > (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Moby Dick', slug: 'moby-dick', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same In (DEX) > Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Mofly', slug: 'mofly', operationalNotation: 'Clip >> Op In (DEX) > (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Moirius', slug: 'moirius', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX)(BOD) > Op Back Whirl (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Morpheus', slug: 'morpheus', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> Op In (DEX)(PDX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Motion', slug: 'motion', operationalNotation: 'Toe >> Same Out (DEX) >> Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Motion Sickness', slug: 'motion-sickness', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op Out (DEX) > Same Out (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Muerto', slug: 'muerto', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'MXZYPTLK', slug: 'mxzyptlk' },
    { displayName: 'Nallegam', slug: 'nallegam', operationalNotation: 'Toe > Same Out (DEX) >> Same In (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nebula', slug: 'nebula', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Op In (DEX)(XDEX)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nemesis Swirl', slug: 'nemesis-swirl' },
    { displayName: 'Neutron Smasher', slug: 'neutron-smasher', operationalNotation: 'Toe > Op Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nobius', slug: 'nobius', operationalNotation: 'Clip > (back) Spin (BOD) > Same In (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Nuclear Illusion', slug: 'nuclear-illusion' },
    { displayName: 'Nuclear Legover', slug: 'nuclear-legover' },
    { displayName: 'Nuclear Pickup', slug: 'nuclear-pickup' },
    { displayName: 'Nullwalk', slug: 'nullwalk', operationalNotation: 'Clip > Op In (DEX) > Same Out (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ocean', slug: 'ocean', operationalNotation: 'Toe >> Op Out (DEX) > Same Out (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Odula', slug: 'odula', operationalNotation: 'Clip > Op In (DEX) >> Dive (BOD) >> Op Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Oh Wheely', slug: 'oh-wheely', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> (no plant while) Op In (DEX)(XDEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Omelette Du Fromage', slug: 'omelette-du-fromage', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op Out (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Original Barroque', slug: 'original-barroque', operationalNotation: 'Clip >> Op In (DEX) > Same In (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Orpheus', slug: 'orpheus', operationalNotation: 'Toe >> Same Out (DEX) > Same Out (DEX)(XDEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Osmosis', slug: 'osmosis', operationalNotation: 'Toe > Op In (DEX) >> (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Overlord', slug: 'overlord', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Same Front Whirl (DEX)(PDX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pandemonium', slug: 'pandemonium', operationalNotation: 'Toe > Same In (DEX) >> (no plant while) Op Out (DEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pandora`s Box', slug: 'pandora`s-box', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same In (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Paradox Symposium Whirling Rake', slug: 'paradox-symposium-whirling-rake' },
    { displayName: 'Paradox Whirling Rake', slug: 'paradox-whirling-rake' },
    { displayName: 'Parallax', slug: 'parallax', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Paratoxic', slug: 'paratoxic', operationalNotation: 'Clip >> Same In (DEX) > (no plant while) Op Front Whirl (DEX)(XDEX)(BOD)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Park Avenue', slug: 'park-avenue', operationalNotation: 'Toe > Same Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pdx Dada Curve', slug: 'pdx-dada-curve' },
    { displayName: 'Pdx DLO', slug: 'pdx-dlo' },
    { displayName: 'Pdx Illusion', slug: 'pdx-illusion' },
    { displayName: 'Pdx Whirling Swirl', slug: 'pdx-whirling-swirl' },
    { displayName: 'Phase', slug: 'phase', operationalNotation: 'Toe > Same Out (DEX) > Op Back Swirl (DEX) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Philibuster', slug: 'philibuster', operationalNotation: 'Toe > Same Out (DEX) > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Phobia', slug: 'phobia', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pixie Ducking Legover', slug: 'pixie-ducking-legover' },
    { displayName: 'Pixie Ducking Mirage', slug: 'pixie-ducking-mirage' },
    { displayName: 'Pixie Ducking Pickup', slug: 'pixie-ducking-pickup' },
    { displayName: 'Pixie Eggbeater', slug: 'pixie-eggbeater' },
    { displayName: 'Pixie Legover', slug: 'pixie-legover' },
    { displayName: 'Pixie Osis', slug: 'pixie-osis', operationalNotation: 'Toe > Same In (DEX) >> (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Pixie Pickup', slug: 'pixie-pickup' },
    { displayName: 'Pixie Quantum Butterfly', slug: 'pixie-quantum-butterfly' },
    { displayName: 'Pixie Symposium Illusion', slug: 'pixie-symposium-illusion' },
    { displayName: 'Pixie Symposium Mirage', slug: 'pixie-symposium-mirage' },
    { displayName: 'Pixie Torque', slug: 'pixie-torque' },
    { displayName: 'Pixie Whirl', slug: 'pixie-whirl' },
    { displayName: 'POD', slug: 'pod', operationalNotation: 'Toe > Same In (DEX) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Porque', slug: 'porque', operationalNotation: 'Toe > Same In (DEX) >> Op In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Predator', slug: 'predator', operationalNotation: 'Toe > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'PS Illusion', slug: 'ps-illusion' },
    { displayName: 'PS Mirage', slug: 'ps-mirage' },
    { displayName: 'Pteradon', slug: 'pteradon', operationalNotation: 'Toe >> Op Out (DEX) >> Same Out (DEX) >> Op Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Puck', slug: 'puck', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Quagmire', slug: 'quagmire', operationalNotation: 'Toe > Op In (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Quantanamera', slug: 'quantanamera', operationalNotation: 'Toe > Op In (DEX) >> Duck (BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Quantum Butterfly (same side)', slug: 'quantum-butterfly' },
    { displayName: 'Quantum Illusion', slug: 'quantum-illusion' },
    { displayName: 'Quantum Legover', slug: 'quantum-legover' },
    { displayName: 'Quantum Mirage', slug: 'quantum-mirage' },
    { displayName: 'Quantum Osis', slug: 'quantum-osis' },
    { displayName: 'Quantum Pickup (same side)', slug: 'quantum-pickup' },
    { displayName: 'Quark', slug: 'quark', operationalNotation: 'Toe > Op In (DEX) >> Op In (DEX)(XDEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Rage', slug: 'rage', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> (no plant while) Op In (DEX)(XDEX)(BOD)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Rail Warrior', slug: 'rail-warrior', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Duck (BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Raildown', slug: 'raildown', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Railplant', slug: 'railplant', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Railwalk', slug: 'railwalk', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op Out (DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Rasmus', slug: 'rasmus', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Reactor', slug: 'reactor', operationalNotation: 'Toe > Op Out (DEX) >> Op Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Red Ribbon', slug: 'red-ribbon', operationalNotation: 'Clip >> Dive (BOD) >> Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Redwetter', slug: 'redwetter', operationalNotation: 'Clip > Op In (DEX) > Op Out (DEX)(PDX) >> Op Out (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Reverse Swirling Osis', slug: 'reverse-swirling-osis' },
    { displayName: 'Reverse Whirling Rake', slug: 'reverse-whirling-rake' },
    { displayName: 'Revstein', slug: 'revstein', operationalNotation: 'Clip >> Same Front Swirl (DEX) >> Same Fornt Swirl (DEX)(XDEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Ricochet', slug: 'ricochet', operationalNotation: 'Toe >> Op Out (DEX) >> Same Out (DEX) > Op Flapper (XBD)(UNS)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ripcurl', slug: 'ripcurl', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ripped Warrior', slug: 'ripped-warrior', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Riptide', slug: 'riptide', operationalNotation: 'Clip > Op In (DEX) >> Op Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Ropaduleo', slug: 'ropaduleo', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Royall Assassin', slug: 'royall-assassin', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> (no plant while) Op In (DEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'S&M Smasher', slug: 'sandm-smasher', operationalNotation: 'Toe > Op Out (DEX) >> Op In (DEX)(XDEX) > Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Sabotage', slug: 'sabotage', operationalNotation: 'Toe >> Op In (DEX) > Same In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Saildown', slug: 'saildown', operationalNotation: 'Toe > Same In (DEX) > Op Out (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Sasquatch', slug: 'sasquatch', operationalNotation: 'Clip > Op In (DEX) >> (no plant while) Op Front Whirl (DEX)(BOD)(PDX) > Op XBD Rake (XBD)(DEL)(DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Scorpion\'s Tail', slug: 'scorpions-tail', operationalNotation: 'Clip >> (back) Spin (BOD) >> Op Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Scorpions Toe Nail', slug: 'scorpions-toe-nail' },
    { displayName: 'Shaft', slug: 'shaft', operationalNotation: 'Clip >> (no plant while) Op Out (DEX)(BOD) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Shmoe', slug: 'shmoe', operationalNotation: 'Clip > Op In (DEX) >> Same Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Singularity', slug: 'singularity', operationalNotation: 'Clip >> (no plant while) Op Front Whirl (DEX)(BOD) >> Op Flapper (XBD)(UNS)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Slap', slug: 'slap', operationalNotation: 'Toe > Op In (DEX) >> Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Slapdown', slug: 'slapdown', operationalNotation: 'Toe > Op In (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Slapstick', slug: 'slapstick', operationalNotation: 'Toe > Same In (DEX) >> (back) Spin (BOD) >> Same Front Whirl (DEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Smashwalk', slug: 'smashwalk', operationalNotation: 'Toe > Op Out (DEX) >> Op In (DEX)(XDEX) > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Smile', slug: 'smile', operationalNotation: 'Clip > Same Back Swirl (DEX) > Op In (DEX) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Snapdragon', slug: 'snapdragon', operationalNotation: 'Clip >> Same Front Swirl (DEX) >> Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Snowflake', slug: 'snowflake', operationalNotation: 'Clip >> Same In (DEX)(PDX) > Same XBD Rake (XBD)(DEL)DEX)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Spanish Fly', slug: 'spanish-fly', operationalNotation: 'Clip >> Duck (BOD) >> Same Out (DEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Spikehammer', slug: 'spikehammer', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) > Op In (DEX)(PDX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Spinning Butterfly Swirl', slug: 'spinning-butterfly-swirl' },
    { displayName: 'Spinning Ducking Butterfly', slug: 'spinning-ducking-butterfly' },
    { displayName: 'Spinning Ducking Clipper', slug: 'spinning-ducking-clipper' },
    { displayName: 'Spinning Ducking Osis', slug: 'spinning-ducking-osis' },
    { displayName: 'Spinning Ducking Pdx Mirage', slug: 'spinning-ducking-pdx-mirage' },
    { displayName: 'Spinning Pdx DLO', slug: 'spinning-pdx-dlo' },
    { displayName: 'Spinning Pdx Illusion', slug: 'spinning-pdx-illusion' },
    { displayName: 'Spinning Pdx Mirage', slug: 'spinning-pdx-mirage' },
    { displayName: 'Spinning Pdx Whirl', slug: 'spinning-pdx-whirl' },
    { displayName: 'Spitfire', slug: 'spitfire', operationalNotation: 'Clip >> (same) Back Swirl (DEX) >> Same Dragon (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'low' },
    { displayName: 'Spyro Gyro', slug: 'spyro-gyro', operationalNotation: 'Clip >> (back) Spin (BOD) >> Same Out (DEX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Stampede', slug: 'stampede', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same In (DEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Stepping Blender (same side)', slug: 'stepping-blender' },
    { displayName: 'Stepping Clipper (same side)', slug: 'stepping-clipper' },
    { displayName: 'Stepping Ducking Butterfly (same side)', slug: 'stepping-ducking-butterfly' },
    { displayName: 'Stepping Ducking DLO', slug: 'stepping-ducking-dlo' },
    { displayName: 'Stepping Ducking Far Double Pickup', slug: 'stepping-ducking-far-double-pickup' },
    { displayName: 'Stepping Ducking PS Whirl', slug: 'stepping-ducking-ps-whirl', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Stepping Eggbeater', slug: 'stepping-eggbeater', operationalNotation: 'CLIP > OP IN [DEX] (plant) > SAME OUT [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping far Clipper', slug: 'stepping-far-clipper' },
    { displayName: 'Stepping Illusion (same side)', slug: 'stepping-illusion' },
    { displayName: 'Stepping Legover (same side)', slug: 'stepping-legover' },
    { displayName: 'Stepping Mirage (same side)', slug: 'stepping-mirage' },
    { displayName: 'Stepping Pdx Torque', slug: 'stepping-pdx-torque' },
    { displayName: 'Stepping Pickup', slug: 'stepping-pickup' },
    { displayName: 'Sumo Thong', slug: 'sumo-thong', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Sunilwalker', slug: 'sunilwalker', operationalNotation: 'Clip > Op In (DEX) > Same In (DEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Super Ego', slug: 'super-ego', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op Front Whirl (DEX)(XDEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Superdeeduperfly', slug: 'superdeeduperfly', operationalNotation: 'Clip >> (back) Spin (BOD) > Duck (BOD) >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Superduperfly', slug: 'superduperfly', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Op Out (DEX)(BOD) > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Supernova', slug: 'supernova', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Same In (DEX)(BOD) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Surging Ducking Paradox Torque', slug: 'surging-ducking-paradox-torque' },
    { displayName: 'Swifter', slug: 'swifter', operationalNotation: 'Clip >> Same In (DEX)(PDX) > Same Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Swirlwind', slug: 'swirlwind', operationalNotation: 'Clip >> (back) Spin (BOD) >> (no plant while) Op Front Whirl (DEX)(BOD)(PDX) > Op Back Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Swivel', slug: 'swivel', operationalNotation: 'Clip >> (no plant while) Same Front Swirl (DEX)(BOD) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Syberian Express', slug: 'syberian-express', operationalNotation: 'Clip > Op In (DEX) >> Duck (BOD) >> Op Out (DEX) > Same Out (DEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Symp Illusion', slug: 'symp-illusion' },
    { displayName: 'Symp Mirage', slug: 'symp-mirage', operationalNotation: 'SET > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Symp Whirl', slug: 'symp-whirl' },
    { displayName: 'Symple Butterfly', slug: 'symple-butterfly' },
    { displayName: 'Symple Reverse Swirl (far)', slug: 'symple-reverse-swirl' },
    { displayName: 'Symple Swirl (far)', slug: 'symple-swirl' },
    { displayName: 'Symposium Down Double Down', slug: 'symposium-down-double-down' },
    { displayName: 'Symposium Eggbeater', slug: 'symposium-eggbeater' },
    { displayName: 'Tap Dance', slug: 'tap-dance', operationalNotation: 'Toe > Same In (DEX) >> Same Out (DEX) > Same In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tapwater', slug: 'tapwater', operationalNotation: 'Toe > Op Out (DEX) >> Op Front Swirl (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Terminator', slug: 'terminator', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> Op In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Timberwulff', slug: 'timberwulff', operationalNotation: 'Clip > Op In (DEX) >> (front) Spin (BOD) >> Same In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tobius', slug: 'tobius', operationalNotation: 'Toe >> (back) Spin (BOD) >> Op In (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tofu', slug: 'tofu', operationalNotation: 'Toe > Op In (DEX) >> Op Front Whirl (DEX)(XDEX) > (back) Spin (BOD) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Torch-r Rack', slug: 'torch-r-rack', operationalNotation: 'Clip > Op In (DEX) >> (no plant while) Op Out (DEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tornado', slug: 'tornado', operationalNotation: 'Clip > Same Out (DEX)(PDX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Torquescrew', slug: 'torquescrew', operationalNotation: 'Clip >> Op In (DEX) > Op Back Whirl (DEX) > (front) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Torus', slug: 'torus', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tremor', slug: 'tremor', operationalNotation: 'Toe > Op Out (DEX) >> Same In (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Triadon', slug: 'triadon', operationalNotation: 'Toe >> Op Out (DEX) > Same Out (DEX)(XDEX) >> Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Triage', slug: 'triage', operationalNotation: 'Toe >> Op In (DEX) > Same In (DEX)(XDEX) >> Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Trifly', slug: 'trifly', operationalNotation: 'Clip >> Same Out (DEX) >> Same Out (DEX)(XDEX) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Triple ATW in-out', slug: 'triple-atw-in-out' },
    { displayName: 'Triple ATW out-in', slug: 'triple-atw-out-in' },
    { displayName: 'Trixie', slug: 'trixie', operationalNotation: 'Toe > Same In (DEX) >> Same In (DEX) >> Same In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Trochus', slug: 'trochus', operationalNotation: 'Toe > Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tunguska', slug: 'tunguska', operationalNotation: 'Toe > Op Out (DEX) >> Duck (BOD) >> Op In (DEX)(XDEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Tutifruti', slug: 'tutifruti', operationalNotation: 'Toe > (rooted) Same In (DEX)(BOD) > Op In (DEX) >> Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Twirl', slug: 'twirl', operationalNotation: 'Clip >> Same Front Swirl (DEX) > (back) Spin (BOD) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Vertigo', slug: 'vertigo', operationalNotation: 'Clip >> Duck (BOD) >> Same In (DEX)(PDX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Voodoo', slug: 'voodoo', operationalNotation: 'Clip >> Same In (DEX)(PDX) > (no plant while) Op In (DEX)(XDEX)(BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Wahnsinn', slug: 'wahnsinn', operationalNotation: 'Toe > Same In (DEX) >> Duck (BOD) >> (front) Spin (BOD) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Warp', slug: 'warp', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) > Op Out (DEX)(XDEX) >> Op In (DEX)(XDEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Weaving Butterfly', slug: 'weaving-butterfly' },
    { displayName: 'Weaving Clipper', slug: 'weaving-clipper' },
    { displayName: 'Weaving Legover', slug: 'weaving-legover' },
    { displayName: 'Weaving Osis', slug: 'weaving-osis' },
    { displayName: 'Weaving Pickup', slug: 'weaving-pickup' },
    { displayName: 'Weaving Whirl', slug: 'weaving-whirl' },
    { displayName: 'Wentletrappe', slug: 'wentletrappe', operationalNotation: 'Toe > Same Out (DEX) >> (back) Spin (BOD) >> Op In (DEX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whale Tail', slug: 'whale-tail', operationalNotation: 'Clip > (back) Spin (BOD) > Same In (DEX) >> Op Out (DEX) > Op Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'What!?', slug: 'what!?' },
    { displayName: 'Whirling far Butterfly', slug: 'whirling-far-butterfly' },
    { displayName: 'Whirling pdx Mirage', slug: 'whirling-pdx-mirage' },
    { displayName: 'Whirling Rake', slug: 'whirling-rake' },
    { displayName: 'Whirlwalk', slug: 'whirlwalk', operationalNotation: 'Clip > Front Whirl (DEX) >> Op Front Whirl (DEX)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whirlygig', slug: 'whirlygig', operationalNotation: 'Clip > Op In (DEX) >> (no plant while) Op Front Whirl (DEX)(BOD)(PDX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whirr', slug: 'whirr', operationalNotation: 'Clip >> Op Front Whirl (DEX) >> Same Front Whirl (DEX)(XDEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Whisk', slug: 'whisk', operationalNotation: 'Clip >> (no plant while) Same Out (DEX)(BOD)(PDX) > Op Out (DEX) > Same Toe (DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Wookie', slug: 'wookie', operationalNotation: 'Toe > Same In (DEX) > (no plant while) Op In (DEX)(BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Yoda', slug: 'yoda', operationalNotation: 'Toe > Same In (DEX) >> Op In (DEX) > Plant > Op Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Your Mom', slug: 'your-mom', operationalNotation: 'Toe > Op Out (DEX) >> (no plant while) Op Out (DEX)(XDEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Your Sister', slug: 'your-sister', operationalNotation: 'Toe > (no plant while) Op Out (DEX)(BOD) >> (no plant while) Same Out (DEX)(XDEX)(BOD) > Same Out (DEX) > Op Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Zig Zag', slug: 'zig-zag', operationalNotation: 'Clip > Same Back Swirl (DEX) >> Same Front Swirl (DEX) > Same Clip (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'high' },
    { displayName: 'Zipwalk', slug: 'zipwalk', operationalNotation: 'XBD Toe > Op In (DEX) >> Op Out (DEX) > Op XBD Toe (XBD)(DEL)', formulaProvenance: 'FootbagMoves', formulaConfidence: 'low' },
    { displayName: 'Zulu Le Loup', slug: 'zulu-le-loup', operationalNotation: 'Clip >> Dive (BOD) >> Op Out (DEX) > Op Clip (XBD)(DEL)[/quote]', formulaProvenance: 'FootbagMoves', formulaConfidence: 'medium' },
    { displayName: 'Zulu Legover', slug: 'zulu-legover' },
    { displayName: 'Zulu Osis', slug: 'zulu-osis' },
    { displayName: 'Zulu Pickup', slug: 'zulu-pickup' },
    { displayName: 'Zulu Whirl', slug: 'zulu-whirl' },
  ] },
  { sourceLabel: 'footbag.org', names: [
    { displayName: 'Atomic Eclipse', slug: 'atomic-eclipse', operationalNotation: 'TOE > OP OUT [DEX] > (JUMP) [BOD] > OP INSIDE [DEL] > OP OUT [DEX] > (LAND)', formulaProvenance: 'footbag.org' },
    { displayName: 'Backside Symposium Smear', slug: 'backside-symposium-smear', operationalNotation: 'TOE > SAME IN [DEX] > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Backside Symposium Toe Blizzard', slug: 'backside-symposium-toe-blizzard', operationalNotation: 'TOE > OP IN [DEX] > (no plant while) OP OUT [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Backside Symposium Toe Blur', slug: 'backside-symposium-toe-blur', operationalNotation: 'TOE > OP IN [DEX] > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Barfly Swirl', slug: 'barfly-swirl', operationalNotation: 'CLIP > SAME OUT [DEX] > SAME OUT [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Blistering Whirl', slug: 'blistering-whirl', operationalNotation: 'CLIP > OP IN [DEX] > (back) SPIN [BOD] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Blurry Symposium Whirl', slug: 'blurry-symposium-whirl', operationalNotation: 'CLIP > OP IN [DEX] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Blurry Whirling Swirl', slug: 'blurry-whirling-swirl', operationalNotation: 'CLIP > OP IN [DEX] > OP IN [PDX] [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Bubba', slug: 'bubba', operationalNotation: 'CLIP > OP OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Butterfly Kick', slug: 'butterfly-kick', operationalNotation: 'SET > JUMP [BOD] > SAME or OP OUT [DEX] > OP CLIP [XBD]', formulaProvenance: 'footbag.org' },
    { displayName: 'Da Da Curve', slug: 'da-da-curve', operationalNotation: 'CLIP > OP IN [DEX] > (NO PLANT WHILE) OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double Blender', slug: 'double-blender', operationalNotation: 'SET > OP IN [DEX] > OP IN [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double Pickup', slug: 'double-pickup', operationalNotation: 'CLIP > OP IN [DEX] > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double Switch-Over', slug: 'double-switch-over', operationalNotation: 'SET > OP OUT [DEX] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double-Over Down', slug: 'double-over-down', operationalNotation: 'TOE > SAME OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Double-Over Down Swirl', slug: 'double-over-down-swirl', operationalNotation: 'TOE > SAME OUT [DEX] > SAME OUT [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Down Double-Down', slug: 'down-double-down', operationalNotation: 'CLIP > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Dragon', slug: 'dragon' },
    { displayName: 'Ducking Barfly', slug: 'ducking-barfly', operationalNotation: 'CLIP > DUCK [BOD] > SAME OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Butterfly', slug: 'fairy-butterfly', operationalNotation: 'TOE > SAME OUT [DEX] > OP OUT [DEX] > OP CLIP [XBD] [DEL].', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Clipper', slug: 'fairy-clipper', operationalNotation: 'TOE > SAME OUT [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Drifter', slug: 'fairy-drifter', operationalNotation: 'TOE > SAME OUT [DEX] > OP IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Leg Over', slug: 'fairy-leg-over', operationalNotation: 'TOE > SAME OUT [DEX] > OP OUT [DEX] > SAME TOE [DEL].', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Merkon', slug: 'fairy-merkon', operationalNotation: 'TOE > SAME OUT [DEX] > (back) SPIN [BOD] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Same Side Mirage', slug: 'fairy-same-side-mirage', operationalNotation: 'TOE > SAME OUT [DEX] (plant) > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Same Side Whirl', slug: 'fairy-same-side-whirl', operationalNotation: 'TOE > SAME OUT [DEX] (plant) > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Fairy Spyro Mirage', slug: 'fairy-spyro-mirage', operationalNotation: 'TOE > SAME OUT [DEX] > (back) SPIN [BOD] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Frigidosis', slug: 'frigidosis' },
    { displayName: 'Hop Over Swirl', slug: 'hop-over-swirl', operationalNotation: 'INSIDE > (JUMP) [BOD] > OP SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Paradox Illusion', slug: 'inspinning-paradox-illusion', operationalNotation: 'CLIP > (front) SPIN [BOD] > SAME OUT [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Paradox Mirage', slug: 'inspinning-paradox-mirage', operationalNotation: 'CLIP > (front) SPIN [BOD] > SAME IN [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Same Side Butterfly', slug: 'inspinning-same-side-butterfly', operationalNotation: 'CLIP > (front) SPIN [BOD] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Same Side Illusion', slug: 'inspinning-same-side-illusion', operationalNotation: 'CLIP > (front) SPIN [BOD] > OP OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Inspinning Same Side Mirage', slug: 'inspinning-same-side-mirage', operationalNotation: 'CLIP > (front) SPIN [BOD] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Leg-Over Flapper Stall', slug: 'leg-over-flapper-stall', operationalNotation: 'TOE > OP OUT [DEX] > OP SOLE [XBD] [UNS] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Miraging Eclipse', slug: 'miraging-eclipse', operationalNotation: 'SET > OP IN [DEX] > (JUMP) [BOD] > OP INSIDE [DEL] > OP OUT [DEX] > (LAND)', formulaProvenance: 'footbag.org' },
    { displayName: 'Miraging Pincher', slug: 'miraging-pincher', operationalNotation: 'CLIP > OP IN [DEX] > OP PINCHER [UNS] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Nuclear Whirl', slug: 'nuclear-whirl', operationalNotation: 'CLIP > SAME OUT [PDX] [DEX] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pandora', slug: 'pandora', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradon Swirl', slug: 'paradon-swirl', operationalNotation: 'TOE > OP OUT [DEX] > SAME OUT [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Barrage', slug: 'paradox-barrage', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Blizzard', slug: 'paradox-blizzard', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP OUT [DEX] > OP TOE [DEL].', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Blur', slug: 'paradox-blur', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Blurry Whirl', slug: 'paradox-blurry-whirl', operationalNotation: 'CLIP > SAME IN [DEX] [BOD] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Da Da Curve', slug: 'paradox-da-da-curve', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > (NO PLANT WHILE) OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Double Leg Over', slug: 'paradox-double-leg-over', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox High Plains Drifter', slug: 'paradox-high-plains-drifter', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > SAME IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Illusion', slug: 'paradox-illusion', operationalNotation: 'CLIP > SAME OUT [PDX[DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Ripwalk', slug: 'paradox-ripwalk', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] (plant) > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Symposium Mirage', slug: 'paradox-symposium-mirage', operationalNotation: 'CLIP (plant) > (no plant while) SAME IN [PDX] [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paradox Whirling Swirl', slug: 'paradox-whirling-swirl', operationalNotation: 'CLIP > SAME IN [PDX] [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Paralax', slug: 'paralax', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Double Over Down', slug: 'pixie-double-over-down', operationalNotation: 'TOE > SAME IN [DEX] (plant) > SAME OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Eclipse', slug: 'pixie-eclipse', operationalNotation: 'TOE > SAME IN [DEX] (JUMP) [BOD] > SAME INSIDE [DEL] > OP OUT [DEX] > (LAND)', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Leg Over', slug: 'pixie-leg-over', operationalNotation: 'TOE > SAME IN [DEX] > OP IN/OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Paradon', slug: 'pixie-paradon', operationalNotation: 'TOE > SAME IN [DEX] > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Same Side Illusion', slug: 'pixie-same-side-illusion', operationalNotation: 'TOE > SAME IN [DEX] (plant) > SAME OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pixie Swirl', slug: 'pixie-swirl', operationalNotation: 'TOE > SAME IN [DEX] > SAME/OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Barfly', slug: 'pogo-barfly', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Butterfly', slug: 'pogo-butterfly', operationalNotation: 'CLIP > (NO PLANT WHILE) OP IN [DEX] [BOD] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Barrage', slug: 'pogo-paradox-barrage', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Blender', slug: 'pogo-paradox-blender', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Da Da Curve', slug: 'pogo-paradox-da-da-curve', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (no plant while) OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Drifter', slug: 'pogo-paradox-drifter', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Eggbeater', slug: 'pogo-paradox-eggbeater', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP OUT [PDX] [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Mirage', slug: 'pogo-paradox-mirage', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [DEX] [BOD] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Torque', slug: 'pogo-paradox-torque', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (back) SPIN [BOD] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Whirl', slug: 'pogo-paradox-whirl', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Paradox Whirling Swirl', slug: 'pogo-paradox-whirling-swirl', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Pickup', slug: 'pogo-pickup', operationalNotation: 'CLIP > (NO PLANT WHILE) OP IN [DEX] > OP IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Pogo Voodoo', slug: 'pogo-voodoo', operationalNotation: 'CLIP > (no plant while) OP IN [DEX] > OP IN [PDX] [DEX] > (no plant while) OP IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Probe', slug: 'probe' },
    { displayName: 'Quantum Drifter', slug: 'quantum-drifter', operationalNotation: 'TOE > OP IN [DEX] > OP IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Quantum Whirl', slug: 'quantum-whirl', operationalNotation: 'TOE > OP IN [DEX] > OP IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Reverse Magellan', slug: 'reverse-magellan', operationalNotation: 'TOE > SAME OUT [DEX] (plant) > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Butterfly', slug: 'shooting-butterfly', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Mirage', slug: 'shooting-mirage', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Star', slug: 'shooting-star', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP OUT [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Shooting Torque', slug: 'shooting-torque', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [PDX] [DEX] > OP IN [DEX] > (back) SPIN [BOD] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spike Hammer', slug: 'spike-hammer', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > OP IN [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Butterfly Kick', slug: 'spinning-butterfly-kick', operationalNotation: 'CLIP > (back) SPIN [BOD] > JUMP [BOD] > OP OUT [DEX] > OP CLIP [XBD]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Blender', slug: 'spinning-paradox-blender', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP IN [PDX] [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Illusion', slug: 'spinning-paradox-illusion', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP OUT [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Mirage', slug: 'spinning-paradox-mirage', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP IN [PDX] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Paradox Whirl', slug: 'spinning-paradox-whirl', operationalNotation: 'CLIP > (back) SPIN [BOD] > OP IN [PDX] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spinning Symposium Down Double Down', slug: 'spinning-symposium-down-double-down', operationalNotation: 'CLIP > (back) SPIN [BOD] > (no plant while) > OP OUT [BOD] [DEX] > SAME OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spyro Illusion', slug: 'spyro-illusion', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spyro Mirage', slug: 'spyro-mirage', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME IN [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Spyro Whirl', slug: 'spyro-whirl', operationalNotation: 'CLIP > (back) SPIN [BOD] > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Ducking Mirage', slug: 'stepping-ducking-mirage', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > SAME IN [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Ducking Paradox Blender', slug: 'stepping-ducking-paradox-blender', operationalNotation: 'CLIP > OP IN [DEX] > DUCK [BOD] > OP IN [DEX] > (back) SPIN [BOD] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Opposite Reaper', slug: 'stepping-opposite-reaper', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [DEX] > SAME OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Opposite Side Reverse Whirl', slug: 'stepping-opposite-side-reverse-whirl', operationalNotation: 'CLIP > OP IN [DEX] > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping P.S. Whirling x-body Rake', slug: 'stepping-ps-whirling-x-body-rake', operationalNotation: 'CLIP > OP IN [DEX] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP X-BODY RAKE [XBD] [DEL] [DEX]', formulaProvenance: 'footbag.org' },
    { displayName: 'Stepping Whirling Swirl', slug: 'stepping-whirling-swirl', operationalNotation: 'CLIP > OP IN [DEX] (plant) > SAME IN [DEX] > OP BACK SWIRL [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Blizzard', slug: 'symposium-blizzard', operationalNotation: 'CLIP > OP IN [DEX] > (NO PLANT WHILE) OP OUT [BOD] [DEX] [BOD] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Blur', slug: 'symposium-blur', operationalNotation: 'CLIP > OP IN [DEX] > (NO PLANT WHILE) OP IN/OUT [DEX] [BOD] [BOD] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Double Leg Over', slug: 'symposium-double-leg-over', operationalNotation: 'SET > (no plant while) OP IN [DEX] > OP OUT [DEX] > SAME TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Pixie', slug: 'symposium-pixie', operationalNotation: 'TOE (plant) > (no plant while) SAME IN [BOD] [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Reverse Whirl', slug: 'symposium-reverse-whirl', operationalNotation: 'SET > (no plant while) OP OUT [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Tomahawk', slug: 'symposium-tomahawk', operationalNotation: 'CLIP > DUCK [BOD] > (no plant while) OP IN [PDX] [BOD] [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Torque', slug: 'symposium-torque', operationalNotation: 'SET > (NO PLANT WHILE) OP IN [DEX] [BOD] > (BACK) SPIN [BOD] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Symposium Whirling Swirl', slug: 'symposium-whirling-swirl', operationalNotation: 'CLIP > (NO PLANT WHILE) OP IN [DEX] [BOD] > OP IN SWIRL [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Tapping Illusion', slug: 'tapping-illusion', operationalNotation: 'TOE > OP OUT [DEX] (plant) > SAME OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Terraging Opposite Clipper', slug: 'terraging-opposite-clipper', operationalNotation: 'TOE > SAME IN [DEX] > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Terraging Same Clipper', slug: 'terraging-same-clipper', operationalNotation: 'TOE > SAME IN [DEX] > SAME IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Blizzard', slug: 'toe-blizzard', operationalNotation: 'TOE > OP IN [DEX] > OP OUT [DEX] > OP TOE [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Clipper', slug: 'toe-clipper' },
    { displayName: 'Toe Double Drifter', slug: 'toe-double-drifter', operationalNotation: 'TOE > OP IN [DEX] > SAME IN [DEX] > SAME CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Ripwalk', slug: 'toe-ripwalk', operationalNotation: 'TOE > OP IN [DEX] (plant) > OP OUT [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Toe Whirr', slug: 'toe-whirr', operationalNotation: 'TOE > OP IN [DEX] > SAME IN [DEX] > OP CLIP [XBD] [DEL]', formulaProvenance: 'footbag.org' },
    { displayName: 'Triple Spin', slug: 'triple-spin', operationalNotation: '[BOD] [BOD] [BOD]', formulaProvenance: 'footbag.org' },
  ] },
  { sourceLabel: 'PassBack', names: [
    { displayName: 'Alpine Blurry Whirl', slug: 'alpine-blurry-whirl' },
    { displayName: 'Alpine Magellan', slug: 'alpine-magellan' },
    { displayName: 'Alpine Paste', slug: 'alpine-paste' },
    { displayName: 'Alpine Pigbeater', slug: 'alpine-pigbeater' },
    { displayName: 'Alpine PLO', slug: 'alpine-plo' },
    { displayName: 'Alpine Smog', slug: 'alpine-smog' },
    { displayName: 'Alpine Smudge', slug: 'alpine-smudge' },
    { displayName: 'Blazing Butterfly', slug: 'blazing-butterfly' },
    { displayName: 'Blink', slug: 'blink' },
    { displayName: 'BS Magellan', slug: 'bs-magellan' },
    { displayName: 'BS Paste', slug: 'bs-paste' },
    { displayName: 'DDD', slug: 'ddd' },
    { displayName: 'Diving Clipper', slug: 'diving-clipper' },
    { displayName: 'Diving Mirage', slug: 'diving-mirage' },
    { displayName: 'Diving Smudge', slug: 'diving-smudge' },
    { displayName: 'Double Dyno', slug: 'double-dyno' },
    { displayName: 'Double Fairy', slug: 'double-fairy' },
    { displayName: 'Double Orbit', slug: 'double-orbit' },
    { displayName: 'Double Spinning Butterfly', slug: 'double-spinning-butterfly' },
    { displayName: 'Double Whip', slug: 'double-whip' },
    { displayName: 'DSO', slug: 'dso' },
    { displayName: 'Ducking Pdx Torque', slug: 'ducking-pdx-torque' },
    { displayName: 'Fairy DLO (ss)', slug: 'fairy-dlo' },
    { displayName: 'Frantic Legover', slug: 'frantic-legover' },
    { displayName: 'Gyro Symp Swirl', slug: 'gyro-symp-swirl' },
    { displayName: 'Gyro Toe', slug: 'gyro-toe' },
    { displayName: 'Gyro Whirling Swirl', slug: 'gyro-whirling-swirl' },
    { displayName: 'Infinity', slug: 'infinity' },
    { displayName: 'Infinity Swirl', slug: 'infinity-swirl' },
    { displayName: 'Pixie Double Pickup (ss)', slug: 'pixie-double-pickup' },
    { displayName: 'Pixie DSO', slug: 'pixie-dso' },
    { displayName: 'PLO', slug: 'plo' },
    { displayName: 'Solestice', slug: 'solestice' },
    { displayName: 'Spanishfly', slug: 'spanishfly' },
    { displayName: 'Spinning Symp Swirl', slug: 'spinning-symp-swirl' },
    { displayName: 'Stepping Ducking Osis', slug: 'stepping-ducking-osis' },
    { displayName: 'Symp Eggbeater', slug: 'symp-eggbeater' },
    { displayName: 'Symp Swirl (op)', slug: 'symp-swirl' },
    { displayName: 'Symp Whirling Swirl', slug: 'symp-whirling-swirl' },
    { displayName: 'Tapping Legover', slug: 'tapping-legover' },
    { displayName: 'Tapping Pickup', slug: 'tapping-pickup' },
    { displayName: 'Toe Ducking Legover', slug: 'toe-ducking-legover' },
    { displayName: 'Toe Gyro Mirage', slug: 'toe-gyro-mirage' },
    { displayName: 'Toe Spinning Toe', slug: 'toe-spinning-toe' },
    { displayName: 'Triple Orbit', slug: 'triple-orbit' },
    { displayName: 'Void', slug: 'void' },
    { displayName: 'Weaving Magellan', slug: 'weaving-magellan' },
    { displayName: 'Weaving Pigbeater', slug: 'weaving-pigbeater' },
    { displayName: 'Zulu Clipper', slug: 'zulu-clipper' },
  ] },
];
