#!/usr/bin/env bash
# backfill-replication.sh
#
# Copies the objects already sitting in a replicated source bucket into its
# disaster-recovery bucket, using an S3 Batch Replication job, waits for the job
# to finish, and proves by sampling that the objects arrived.
#
# WHY THIS EXISTS.
#
# Live S3 replication copies only objects written after the replication rule
# exists. A bucket that was loaded before its rule arrived therefore has a
# second-region copy that is missing everything it held at that moment, and
# nothing reports the gap: the rule is enabled, the alarms are quiet, and the
# recovery copy is incomplete. Batch Replication is AWS's mechanism for exactly
# this, and the same job also re-drives objects whose replication FAILED, which
# S3 never retries on its own.
#
# The archive is the one source this serves: its replication role is granted
# the batch permissions in Terraform, and no other bucket's is.
#
# What a run does, in order:
#   1. Reads the source bucket, its DR bucket, and where the job may write its
#      manifest and report, from terraform/<target> outputs.
#   2. Proves the source's enabled replication rule names that DR bucket, and
#      takes the job's role from the rule itself, so the job cannot run under a
#      role the live rule does not use.
#   3. Proves that role trusts S3 Batch Operations, which the Terraform apply
#      that adds the archive's replica grants.
#   4. Proves the run is the directly authenticated footbag-operator IAM user in
#      this project's account. Creating the job hands the replication role to
#      S3, and the dev-and-tester role holds no permission to pass a role.
#   5. Resumes an unfinished backfill job from an earlier run if one exists,
#      rather than starting a second over the same objects.
#   6. Otherwise states the job in full, takes a typed APPLY on production, and
#      creates it: manifest generated by S3 from the replication configuration,
#      limited to objects never replicated or whose replication failed, with
#      the manifest and an all-tasks completion report written under the one
#      prefix the role may write.
#   7. Polls the job to the end. A job that completes with any failed task fails
#      the run, and the report location is printed.
#   8. Samples keys across the source and requires each to report COMPLETED at
#      the source and to exist in the DR bucket.
#
# A job that S3 fails because manifest generation found no key to copy means
# nothing was left to backfill. That is the expected outcome of a re-run, so it
# is reported as such and the run is judged on the sample instead.
#
# What it refuses:
#   - a target or source it was not given; there are no defaults
#   - a source whose stack is off (its Terraform output is null)
#   - a source with no enabled rule, or a rule naming another destination
#   - a replication role that does not trust S3 Batch Operations
#   - creating a job as any identity but footbag-operator in this account
#   - production with no terminal to type APPLY on; there is no flag that
#     answers for the operator
#
# An interrupt never cancels a job: once created it belongs to S3 and runs to
# its end whether or not anyone is watching. The run prints the job id, and
# --status <job-id> picks the watch back up.
#
# The lifecycle rules on both buckets only expire noncurrent versions after
# thirty days and remove no delete markers, so they cannot make the copy diverge
# from the source while the job runs, which is the case AWS warns about.
#
# Usage:
#   bash scripts/backfill-replication.sh --target staging --source archive
#   bash scripts/backfill-replication.sh --target production --source archive --dry-run
#   bash scripts/backfill-replication.sh --target staging --source archive --status <job-id>
#
# Flags:
#   --target <staging|production>   the environment; required, no default
#   --source archive                the replicated bucket to backfill; required
#   --dry-run                       run every read and precondition, print the
#                                   job that would be created, create nothing
#   --status <job-id>               watch an existing job to its end and verify;
#                                   creates nothing
#
# Test seams (CI only; operators never set these), announced on stderr when set:
# BACKFILL_REPLICATION_AWS_BIN and BACKFILL_REPLICATION_TERRAFORM_BIN replace
# the two tools; BACKFILL_REPLICATION_POLL_SECONDS replaces the wait between
# job polls.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$REPO_ROOT"

# confirm_from_tty and require_target. Sourcing this also assigns ASSUME_YES,
# so nothing exported in the operator's shell can answer the prompt.
# shellcheck source=lib/host-env-remote.sh
source "${SCRIPT_DIR}/lib/host-env-remote.sh"

die() { echo "backfill-replication: $*" >&2; exit 1; }

TARGET=""
SOURCE=""
DRY_RUN=0
STATUS_JOB=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)  TARGET="${2:-}"; shift 2 || { echo "backfill-replication: --target requires an argument" >&2; exit 2; } ;;
    --source)  SOURCE="${2:-}"; shift 2 || { echo "backfill-replication: --source requires an argument" >&2; exit 2; } ;;
    --status)  STATUS_JOB="${2:-}"; shift 2 || { echo "backfill-replication: --status requires a job id" >&2; exit 2; } ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) sed -n '2,/^set -eu/{/^set -eu/d;p;}' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "backfill-replication: unknown argument '$1' (try --help)" >&2; exit 2 ;;
  esac
done

require_target "$TARGET" staging production || exit 2
[[ "$SOURCE" == "archive" ]] \
  || { echo "backfill-replication: --source must be 'archive' (got '${SOURCE}'); it is the one source whose replication role carries the batch permissions." >&2; exit 2; }
if [[ -n "$STATUS_JOB" && ! "$STATUS_JOB" =~ ^[A-Za-z0-9_-]{5,36}$ ]]; then
  echo "backfill-replication: --status takes an S3 Batch Operations job id (got '${STATUS_JOB}')." >&2
  exit 2
fi
if [[ -n "$STATUS_JOB" && "$DRY_RUN" -eq 1 ]]; then
  echo "backfill-replication: --status and --dry-run are separate modes; give one." >&2
  exit 2
fi

AWS_BIN="${BACKFILL_REPLICATION_AWS_BIN:-aws}"
TF_BIN="${BACKFILL_REPLICATION_TERRAFORM_BIN:-terraform}"
POLL_SECONDS="${BACKFILL_REPLICATION_POLL_SECONDS:-30}"
for seam in BACKFILL_REPLICATION_AWS_BIN BACKFILL_REPLICATION_TERRAFORM_BIN BACKFILL_REPLICATION_POLL_SECONDS; do
  [[ -n "${!seam:-}" ]] && echo "backfill-replication: TEST SEAM ${seam} is set; this run proves nothing about the estate." >&2
done
[[ "$POLL_SECONDS" =~ ^[0-9]+$ ]] || die "BACKFILL_REPLICATION_POLL_SECONDS must be a whole number of seconds"

if [[ -z "${BACKFILL_REPLICATION_AWS_BIN:-}" ]]; then
  # shellcheck source=lib/aws-profile.sh
  source "${SCRIPT_DIR}/lib/aws-profile.sh"
  aws_profile_ensure || exit 1
fi
# The identity checks ask through the same binary as everything else here.
AWS_IDENTITY_BIN="$AWS_BIN"
# shellcheck source=lib/aws-identity.sh
source "${SCRIPT_DIR}/lib/aws-identity.sh"

# Both stacks keep their source buckets in us-east-1, and a Batch Replication
# job must be created in the source bucket's region.
REGION="us-east-1"
ACCOUNT="$FOOTBAG_AWS_ACCOUNT_ID"
DESCRIPTION="backfill-replication ${SOURCE} ${TARGET}"
SAMPLE_SIZE=20

aws_call() { "$AWS_BIN" "$@" </dev/null; }

# ── 1. What Terraform says the buckets are ─────────────────────────────────

tf_json() {
  "$TF_BIN" -chdir="terraform/${TARGET}" output -json "$1" </dev/null 2>/dev/null
}

src_json="$(tf_json archive_bucket_name)" \
  || die "could not read terraform/${TARGET} output archive_bucket_name"
if [[ "$src_json" == "null" ]]; then
  die "the archive stack is off in ${TARGET} (output archive_bucket_name is null), so there is no archive to backfill. Nothing done."
fi
SRC="$(jq -er 'strings' <<<"$src_json" 2>/dev/null)" \
  || die "terraform/${TARGET} output archive_bucket_name is not a bucket name: ${src_json}"

DEST="$(tf_json archive_dr_bucket_name | jq -er 'strings' 2>/dev/null)" \
  || die "could not read terraform/${TARGET} output archive_dr_bucket_name; apply the archive replica first"

report_json="$(tf_json archive_batch_replication_report)" \
  || die "could not read terraform/${TARGET} output archive_batch_replication_report; apply the archive replica first"
REPORT_BUCKET="$(jq -er '.bucket | strings' <<<"$report_json" 2>/dev/null)" \
  || die "output archive_batch_replication_report names no bucket: ${report_json}"
REPORT_PREFIX="$(jq -er '.prefix | strings' <<<"$report_json" 2>/dev/null)" \
  || die "output archive_batch_replication_report names no prefix: ${report_json}"

echo "==> ${SRC} -> ${DEST} (${TARGET})"

# ── 2. The live rule, and the role it runs under ───────────────────────────

replication="$(aws_call s3api get-bucket-replication --bucket "$SRC" --output json 2>/dev/null)" \
  || die "${SRC} has no replication configuration; apply the archive replica first. Nothing done."
ROLE_ARN="$(jq -er '.ReplicationConfiguration.Role | strings' <<<"$replication" 2>/dev/null)" \
  || die "${SRC}'s replication configuration names no role. Nothing done."
rule_dest="$(jq -r '[.ReplicationConfiguration.Rules[] | select(.Status == "Enabled") | .Destination.Bucket] | first // ""' <<<"$replication")"
if [[ "$rule_dest" != "arn:aws:s3:::${DEST}" ]]; then
  die "${SRC}'s enabled replication rule replicates to '${rule_dest:-nothing}', not ${DEST}. A batch job would copy to whatever the rule names, so this refuses. Nothing done."
fi
echo "    rule replicates to ${DEST} as ${ROLE_ARN}"

# ── 3. The role must trust S3 Batch Operations ─────────────────────────────

role_name="${ROLE_ARN##*/}"
trust="$(aws_call iam get-role --role-name "$role_name" --query Role.AssumeRolePolicyDocument --output json 2>/dev/null)" \
  || die "could not read the trust policy of ${role_name}. Nothing done."
if ! jq -e '[.Statement[] | select(.Effect == "Allow") | .Principal.Service] | flatten | index("batchoperations.s3.amazonaws.com")' <<<"$trust" >/dev/null 2>&1; then
  die "${role_name} does not trust batchoperations.s3.amazonaws.com, so S3 could not run the job as it. Apply terraform/${TARGET} first. Nothing done."
fi

# ── Verification, shared by every mode that reaches an end ─────────────────

verify_sample() {
  local listing keys=() total step i key status failed=0 checked=0
  listing="$(aws_call s3api list-objects-v2 --bucket "$SRC" --max-items 1000 \
    --query 'Contents[].Key' --output json 2>/dev/null)" \
    || die "could not list ${SRC} to sample it"
  mapfile -t keys < <(jq -r '(. // [])[]' <<<"$listing")
  total="${#keys[@]}"
  if (( total == 0 )); then
    echo "==> ${SRC} holds no objects, so there was nothing to backfill and nothing to sample."
    return 0
  fi
  step=$(( total > SAMPLE_SIZE ? total / SAMPLE_SIZE : 1 ))
  echo "==> sampling ${SRC} (every ${step} of the first ${total} keys)"
  for (( i = 0; i < total && checked < SAMPLE_SIZE; i += step )); do
    key="${keys[i]}"
    checked=$((checked + 1))
    status="$(aws_call s3api head-object --bucket "$SRC" --key "$key" \
      --query ReplicationStatus --output text 2>/dev/null)" || status=""
    if [[ "$status" != "COMPLETED" ]]; then
      echo "  FAIL: ${key} in ${SRC} reports replication status '${status:-none}', not COMPLETED" >&2
      failed=$((failed + 1))
      continue
    fi
    if ! aws_call s3api head-object --bucket "$DEST" --key "$key" >/dev/null 2>&1; then
      echo "  FAIL: ${key} is missing from ${DEST}" >&2
      failed=$((failed + 1))
    fi
  done
  if (( failed > 0 )); then
    die "${failed} of ${checked} sampled key(s) are not in ${DEST}. The completion report is under s3://${REPORT_BUCKET}/${REPORT_PREFIX}/."
  fi
  echo "== backfill proven on ${TARGET}: ${checked} sampled key(s) from ${SRC} are in ${DEST} =="
}

# watch_job <job-id>: poll to a terminal status, then judge it.
watch_job() {
  local job="$1" row status total ok bad reasons
  echo "==> watching job ${job} (interrupting stops the watch, never the job; resume with --status ${job})"
  while :; do
    row="$(aws_call s3control describe-job --region "$REGION" --account-id "$ACCOUNT" --job-id "$job" \
      --query 'Job.[Status,ProgressSummary.TotalNumberOfTasks,ProgressSummary.NumberOfTasksSucceeded,ProgressSummary.NumberOfTasksFailed]' \
      --output text 2>/dev/null)" || die "could not read job ${job}"
    read -r status total ok bad <<<"$row"
    echo "    ${status}: ${ok:-0} of ${total:-?} task(s) succeeded, ${bad:-0} failed"
    case "$status" in
      Complete|Failed|Cancelled) break ;;
    esac
    sleep "$POLL_SECONDS"
  done

  case "$status" in
    Complete)
      if [[ "${bad:-0}" != "0" && "${bad:-0}" != "None" ]]; then
        die "job ${job} completed with ${bad} failed task(s). The completion report under s3://${REPORT_BUCKET}/${REPORT_PREFIX}/ names each object and its failure reason."
      fi
      ;;
    Failed)
      reasons="$(aws_call s3control describe-job --region "$REGION" --account-id "$ACCOUNT" --job-id "$job" \
        --query 'Job.FailureReasons[].FailureReason' --output text 2>/dev/null)" || reasons=""
      if [[ "$reasons" == *"no keys matching the filter criteria"* ]]; then
        # Expected exit for a source with nothing left unreplicated; the sample
        # below is the verdict, not the job's status.
        echo "    S3 found no object left to replicate: nothing was missing from ${DEST}."
      else
        die "job ${job} failed: ${reasons:-no reason given}"
      fi
      ;;
    Cancelled)
      die "job ${job} was cancelled before it finished; re-run to start a new one"
      ;;
  esac
}

# ── --status: watch an existing job, create nothing ────────────────────────

if [[ -n "$STATUS_JOB" ]]; then
  watch_job "$STATUS_JOB"
  verify_sample
  exit 0
fi

# ── 4. Who is asking ──────────────────────────────────────────────────────

aws_identity_resolve "" || die "no AWS identity resolved. Nothing done."
if [[ "$AWS_IDENTITY_ARN" != "arn:aws:iam::${ACCOUNT}:user/footbag-operator" ]]; then
  die "this run is authenticated as ${AWS_IDENTITY_ARN}, not the footbag-operator IAM user in account ${ACCOUNT}. Creating the job passes the replication role to S3, which only that user may do. Nothing done."
fi
echo "    acting as ${AWS_IDENTITY_ARN}"

# ── 5. An unfinished job from an earlier run ───────────────────────────────

unfinished="$(aws_call s3control list-jobs --region "$REGION" --account-id "$ACCOUNT" \
  --job-statuses Active Cancelling Completing Failing New Paused Pausing Preparing Ready Suspended \
  --output json 2>/dev/null)" || die "could not list this account's batch jobs. Nothing done."
existing="$(jq -r --arg d "$DESCRIPTION" '[.Jobs[]? | select(.Description == $d) | .JobId] | first // ""' <<<"$unfinished")"
if [[ -n "$existing" ]]; then
  echo "==> an earlier run's job ${existing} is still running; watching it instead of starting another"
  if (( DRY_RUN )); then
    echo "Dry run: nothing created."
    exit 0
  fi
  watch_job "$existing"
  verify_sample
  exit 0
fi

# ── 6. State the job, confirm, create ──────────────────────────────────────

operation='{"S3ReplicateObject":{}}'
report="$(jq -cn --arg b "arn:aws:s3:::${REPORT_BUCKET}" --arg p "${REPORT_PREFIX}/reports" \
  '{Bucket: $b, Prefix: $p, Format: "Report_CSV_20180820", Enabled: true, ReportScope: "AllTasks"}')"
generator="$(jq -cn --arg a "$ACCOUNT" --arg s "arn:aws:s3:::${SRC}" \
  --arg b "arn:aws:s3:::${REPORT_BUCKET}" --arg p "${REPORT_PREFIX}/manifests" \
  '{S3JobManifestGenerator: {
      ExpectedBucketOwner: $a,
      SourceBucket: $s,
      EnableManifestOutput: true,
      ManifestOutputLocation: {
        ExpectedManifestBucketOwner: $a,
        Bucket: $b,
        ManifestPrefix: $p,
        ManifestFormat: "S3InventoryReport_CSV_20211130"
      },
      Filter: {EligibleForReplication: true, ObjectReplicationStatuses: ["NONE", "FAILED"]}
    }}')"

echo ""
echo "This creates one S3 Batch Replication job in ${TARGET}:"
echo "  copies   every object in ${SRC} never replicated, or whose replication"
echo "           failed, to ${DEST}"
echo "  as       ${ROLE_ARN}"
echo "  writes   its manifest and completion report under"
echo "           s3://${REPORT_BUCKET}/${REPORT_PREFIX}/"
echo "  then     waits for the job and samples ${SAMPLE_SIZE} keys in ${DEST}"
echo ""

if (( DRY_RUN )); then
  echo "Dry run: every precondition holds; nothing created."
  exit 0
fi

if [[ "$TARGET" == "production" ]]; then
  confirm_from_tty "Type 'APPLY' to continue: " "APPLY" || die "not confirmed. Nothing done."
fi

token="backfill-${SOURCE}-${TARGET}-$(date -u +%Y%m%dT%H%M%SZ)"
JOB_ID="$(aws_call s3control create-job --region "$REGION" --account-id "$ACCOUNT" \
  --operation "$operation" --report "$report" --manifest-generator "$generator" \
  --priority 10 --role-arn "$ROLE_ARN" --no-confirmation-required \
  --description "$DESCRIPTION" --client-request-token "$token" \
  --query JobId --output text)" || die "S3 refused to create the job. Nothing was created."
[[ -n "$JOB_ID" && "$JOB_ID" != "None" ]] || die "S3 returned no job id; check the console before re-running"

# From here the job is S3's. An interrupt reports it and leaves it running.
trap 'echo "" >&2; echo "backfill-replication: interrupted; job ${JOB_ID} keeps running. Resume with --status ${JOB_ID}." >&2; exit 130' INT TERM
echo "==> created job ${JOB_ID}"

# ── 7 and 8. Wait, then prove ──────────────────────────────────────────────

watch_job "$JOB_ID"
verify_sample
