#!/usr/bin/env bash
# rotate-origin-verify-secret.sh
#
# Rotates the shared secret CloudFront sends on every origin request and nginx
# checks, and proves the site still answers through CloudFront afterwards.
#
# The secret is generated by the random_id.origin_verify_secret Terraform
# resource and mirrored into the host env file by every deploy, so rotating it is
# three acts in a fixed order: replace the resource, deploy so the host picks up
# the new value, and check the site through CloudFront. Between the first two,
# CloudFront sends the new value while nginx still expects the old one and every
# request is refused, so the order and the gap both matter. It used to be a
# hand-typed `terraform apply -replace` with no saved plan, no confirmation and no
# shred, followed by a deploy someone had to remember. This is the whole of it.
#
# Rotation is for cause, never on a clock: a suspected exposure of a state file,
# a saved plan or the host env file.
#
# Steps (referenced by --from-step, so a failure part-way is resumable without
# rotating a second time):
#   1  prove the site answers through CloudFront now, then replace the secret
#      through scripts/terraform-apply.sh (saved plan, typed APPLY on production,
#      shredded plan), then prove the stored value changed and has the right shape
#   2  deploy code only through deploy_to_aws.sh, which mirrors the new value into
#      the host env file
#   3  prove the site answers through CloudFront again
#
# What it refuses:
#   - a target it was not given; there is no default
#   - rotating while the site already fails through CloudFront, because the run
#     could then not tell its own breakage from one it walked into
#   - deploying when the stored secret did not change, or does not have the
#     64-character lowercase hex shape the host and nginx expect
#
# The secret is never printed, logged or put in an argument list: it is compared
# by digest only.
#
# Usage. Staging's deploy reads the host sudo password from stdin, so a staging
# run takes the same redirect a staging deploy does; production's deploy asks for
# it at the terminal and takes no redirect.
#
#   < ~/AWS/AWS_OPERATOR.txt bash scripts/rotate-origin-verify-secret.sh --target staging
#   bash scripts/rotate-origin-verify-secret.sh --target production
#   bash scripts/rotate-origin-verify-secret.sh --target production --from-step 2
#
# Test seams (CI only; operators never set these), each announced on stderr when
# set: ROTATE_TF_APPLY and ROTATE_DEPLOY replace the two scripts it runs;
# ROTATE_AWS_BIN, ROTATE_TERRAFORM_BIN and ROTATE_CURL_BIN replace the tools;
# ROTATE_PROBE_TRIES shortens the post-deploy wait.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$REPO_ROOT"

TARGET=""
FROM_STEP=1

die() { echo "rotate-origin-verify-secret: $*" >&2; exit 1; }

usage() {
  sed -n '2,/^set -eu/{/^set -eu/d;p;}' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)    TARGET="${2:-}"; shift 2 || { echo "rotate-origin-verify-secret: --target requires an argument" >&2; exit 2; } ;;
    --from-step) FROM_STEP="${2:-}"; shift 2 || { echo "rotate-origin-verify-secret: --from-step requires a step number" >&2; exit 2; } ;;
    -h|--help)   usage 0 ;;
    *) echo "rotate-origin-verify-secret: unknown argument '$1' (try --help)" >&2; exit 2 ;;
  esac
done

[[ "$TARGET" == "staging" || "$TARGET" == "production" ]] \
  || die "--target must be staging or production (got '${TARGET}')"
[[ "$FROM_STEP" =~ ^[123]$ ]] || die "--from-step must be 1, 2 or 3 (got '${FROM_STEP}')"

TF_APPLY="${ROTATE_TF_APPLY:-${SCRIPT_DIR}/terraform-apply.sh}"
DEPLOY="${ROTATE_DEPLOY:-${REPO_ROOT}/deploy_to_aws.sh}"
AWS_BIN="${ROTATE_AWS_BIN:-aws}"
TF_BIN="${ROTATE_TERRAFORM_BIN:-terraform}"
CURL_BIN="${ROTATE_CURL_BIN:-curl}"
PROBE_TRIES="${ROTATE_PROBE_TRIES:-30}"
for seam in ROTATE_TF_APPLY ROTATE_DEPLOY ROTATE_AWS_BIN ROTATE_TERRAFORM_BIN ROTATE_CURL_BIN ROTATE_PROBE_TRIES; do
  [[ -n "${!seam:-}" ]] && echo "rotate-origin-verify-secret: TEST SEAM ${seam} is set; this run proves nothing about the estate." >&2
done

PARAM="/footbag/${TARGET}/secrets/origin_verify_secret"

if [[ -z "${ROTATE_AWS_BIN:-}" ]]; then
  # shellcheck source=lib/aws-profile.sh
  source "${SCRIPT_DIR}/lib/aws-profile.sh"
  aws_profile_ensure || exit 1
fi

# The digest of the stored secret, never the secret: printf is a builtin, so the
# value reaches sha256sum through a pipe and no argument list ever carries it.
# The shape check runs here too, because this is the only place the value is in
# hand.
secret_digest() {
  local value
  value="$("$AWS_BIN" ssm get-parameter --with-decryption --name "$PARAM" \
    --query Parameter.Value --output text </dev/null 2>/dev/null)" || return 1
  if [[ ! "$value" =~ ^[0-9a-f]{64}$ ]]; then
    echo "BADSHAPE"
    return 0
  fi
  printf '%s' "$value" | sha256sum | cut -d' ' -f1
}

CF_DOMAIN="$("$TF_BIN" -chdir="terraform/${TARGET}" output -raw cloudfront_domain </dev/null 2>/dev/null)" \
  || die "could not read the cloudfront_domain output of terraform/${TARGET}"
[[ -n "$CF_DOMAIN" ]] || die "terraform/${TARGET} has no cloudfront_domain output"
PROBE_URL="https://${CF_DOMAIN}/health/ready"

# 200 through CloudFront means CloudFront's header matched what nginx expects
# and the application is ready; a mismatch is a 444, which curl reports as an
# empty reply.
answers_through_cloudfront() {
  local code
  code="$("$CURL_BIN" -s -o /dev/null -w '%{http_code}' --max-time 10 "$PROBE_URL" </dev/null 2>/dev/null)" || code=""
  [[ "$code" == "200" ]]
}

if (( FROM_STEP <= 1 )); then
  echo "==> step 1: replace the secret"
  answers_through_cloudfront \
    || die "the site does not answer through CloudFront (${PROBE_URL}) before anything is changed; find out why first, or this run cannot tell its own breakage from that one"
  before="$(secret_digest)" || die "could not read ${PARAM}"

  # stdin is closed for the apply: a staging run carries the host password on
  # stdin for the deploy in step 2, and nothing in the apply may consume it.
  bash "$TF_APPLY" --target "$TARGET" --replace random_id.origin_verify_secret </dev/null \
    || die "the replacement did not apply. Nothing was deployed; fix the cause and re-run from step 1."

  after="$(secret_digest)" || die "could not read ${PARAM} after the apply; re-run from step 1 once it is readable"
  [[ "$after" != "BADSHAPE" ]] \
    || die "${PARAM} is not a 64-character lowercase hex value after the apply. Not deploying it."
  [[ "$after" != "$before" ]] \
    || die "${PARAM} did not change. Not deploying; check the apply above replaced random_id.origin_verify_secret."
  echo "    the stored secret changed and has the expected shape"
  echo "    CloudFront now sends the new value; the site refuses requests until step 2 deploys it"
fi

if (( FROM_STEP <= 2 )); then
  echo "==> step 2: deploy, so the host mirrors the new value"
  bash "$DEPLOY" --target "$TARGET" -k \
    || die "the deploy failed. The site refuses requests through CloudFront until it succeeds: resume with --from-step 2."
fi

echo "==> step 3: prove the site answers through CloudFront"
ok=0
for (( i = 1; i <= PROBE_TRIES; i++ )); do
  if answers_through_cloudfront; then ok=1; break; fi
  (( i < PROBE_TRIES )) && sleep 4
done
(( ok )) || die "the site still does not answer through CloudFront (${PROBE_URL}). Check the deploy above mirrored the secret, then resume with --from-step 3."

echo ""
echo "== origin-verify secret rotated on ${TARGET}; ${PROBE_URL} answers 200 =="
