/**
 * Maintainer-curated baseline persona catalog.
 *
 * The shared reference set every maintainer and paid tester switches between.
 * Each entry carries a `dimension` (the authorization axis it belongs to), a
 * `purpose` (the code path or gate it exists to exercise), a `testingUsage` (how
 * a tester uses it and what to verify), and `coverageNotes`; the catalog doubles
 * as a coverage matrix that surfaces gaps as the testing surface grows. New test
 * slices add personas here rather than inventing fixture rows.
 *
 * The catalog covers the tier ladder and admin role plus onboarding-wizard
 * state, legacy-claim variants, graded auto-link confidence (high/medium/low),
 * legacy-club-candidate cards (pending/declined/resolved/junk), club
 * affiliations, payment history, Active Player expiry, mailing-list
 * subscription state, and edge-case identities.
 *
 * Classes whose backing feature is not built yet (event organizer, group roles,
 * vote eligibility, the claimed-legacy banned subject) appear with a `blockedBy`
 * marker: they are never seeded and render greyed on /dev/personas, so the
 * catalog shows the full deployed-spread matrix and the test cases that arrive
 * with each future feature. Drop a persona's `blockedBy` when its feature lands.
 */
import type { PersonaSpec } from './personaFactory';

export const CANONICAL_PERSONAS: PersonaSpec[] = [
  {
    // CUTOVER-REMOVE. Non-prod (dev + staging); built by real flows on first
    // Switch (not seeded). See src/testkit/davidJourney.ts and /dev/build-switch.
    slug: 'david_leberknight',
    displayName: 'David Leberknight',
    realName: 'David Leberknight',
    tier: 'tier2',
    isAdmin: true,
    buildOnSwitch: true,
    dimension: 'Tier ladder & admin',
    purpose: 'Maintainer real-flow journey (dev + staging, never prod): built end-to-end on first Switch via the real register / verify / claim / onboard / upload flows.',
    testingUsage: 'Dev + staging. Click Switch to build David through the real flows (or rebuild after Refresh), then act as the maintainer.',
    onboardingComplete: true,
    coverageNotes: [
      'non-prod build-on-switch real-flow journey',
      'HOF legacy claim, club co-leader, avatar, galleries, media',
      'admin via the dev/staging register-allowlist bootstrap',
    ],
  },
  {
    slug: 't0_fresh',
    displayName: 'Tia Zero',
    tier: 'tier0',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 0 floor actor: the just-below case every tier-gated route must deny.',
    testingUsage: 'Switch here to confirm tier-gated routes deny the Tier 0 floor while open routes still work.',
    onboardingComplete: true,
    coverageNotes: ['tier0 baseline', 'onboarding wizard complete', 'no payment history'],
  },
  {
    slug: 't1_paid',
    displayName: 'Won Paid',
    tier: 'tier1',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 1 member: the first paid-benefits gate. A verified member with a deliverable login email, so member notifications it triggers are captured rather than skipped.',
    testingUsage: 'Act as a paid Tier 1 member to confirm the first paid-benefits gate opens while Tier 2 surfaces stay closed. Also use it to trigger member notifications, such as submitting a contact-admin request or joining and leaving a club, and read the captured mail on /dev/outbox.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'succeeded', purchasedTier: 'tier1' }],
    coverageNotes: ['tier1', 'one successful membership purchase', 'tier1 benefits gate'],
  },
  {
    slug: 't2_paid',
    displayName: 'Tu Paid',
    tier: 'tier2',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 2 member: full paid-tier benefits gate. Tier 2 standing also qualifies the member to vouch a Tier 0 member for Active Player.',
    testingUsage: 'Act as a full Tier 2 member to confirm all paid-tier benefits and organizer-eligible surfaces open. Use it to vouch a Tier 0 member for Active Player and read the vouch-confirmation notification on /dev/outbox.',
    onboardingComplete: true,
    payments: [
      { type: 'membership', status: 'succeeded', purchasedTier: 'tier1' },
      { type: 'membership', status: 'succeeded', purchasedTier: 'tier2' },
    ],
    coverageNotes: ['tier2', 'tier1 + tier2 purchase history', 'tier2 benefits gate'],
  },
  {
    slug: 't3_comped',
    displayName: 'Tree Comped',
    tier: 'tier3',
    underlyingTier: 'tier2',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 3 governance tier reached without payment (admin-comped); underlying Tier 2.',
    testingUsage: 'Verify Tier 3 governance surfaces open for a comped director and that Tier 2 is what remains if governance ends.',
    onboardingComplete: true,
    coverageNotes: [
      'tier3 governance tier',
      'admin-comped (no payment)',
      'underlying tier2',
    ],
  },
  {
    slug: 'admin_t2',
    displayName: 'Addie Min',
    tier: 'tier2',
    isAdmin: true,
    dimension: 'Tier ladder & admin',
    purpose: 'Admin role: exercises admin nav and every admin-gated surface (allow half of admin routes). Holds the authority to work the admin work queue, including resolving member contact requests.',
    testingUsage: 'Act as an admin to walk the admin nav and confirm every admin-gated surface opens (the allow half of the admin matrix). Switch here to work the admin work queue, for example resolving a contact request, and read the resulting member notification on /dev/outbox.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'succeeded', purchasedTier: 'tier2' }],
    coverageNotes: ['admin role', 'tier2', 'admin nav + admin-gated surfaces'],
  },

  // ── Account state & privacy (catastrophic auth / privacy surfaces) ────────
  {
    slug: 'unverified',
    displayName: 'Eve Unverified',
    tier: 'tier0',
    dimension: 'Account state & privacy',
    purpose: 'Registered but email not yet verified: login is blocked and member search excludes the account until verification.',
    testingUsage: 'Confirm an unverified account cannot log in and is excluded from member search; Switch is expected to be refused because login is blocked until verification.',
    emailVerified: false,
    coverageNotes: [
      'registered-unverified (email_verified_at NULL)',
      'login blocked until verification',
      'excluded from authenticated member search',
    ],
  },
  {
    slug: 'deceased',
    displayName: 'Mort Memoriam',
    tier: 'tier2',
    dimension: 'Account state & privacy',
    purpose: 'Deceased member: login disabled and search/roster-excluded, while HoF/BAP honors and history stay visible.',
    testingUsage: 'Verify a deceased member is login-disabled and search/roster-excluded while HoF/BAP honors and history still render; Switch is refused because login is disabled.',
    isDeceased: true,
    honors: { hof: true },
    onboardingComplete: true,
    coverageNotes: [
      'deceased (is_deceased=1): login disabled, search-excluded, roster-removed',
      'honors (HoF) and historical contributions preserved on render',
    ],
  },
  {
    slug: 'del_grace_open',
    displayName: 'Grace Open',
    tier: 'tier1',
    dimension: 'Account state & privacy',
    purpose: 'Soft-deleted and still inside the restoration window: logging in offers account restoration.',
    testingUsage: 'Confirm logging in during the open restoration window presents the account-restoration screen.',
    deletionState: 'grace_open',
    onboardingComplete: true,
    coverageNotes: [
      'deletion grace period still open',
      'login presents the restoration screen',
      'boundary partner of del_grace_elapsed',
    ],
  },
  {
    slug: 'del_grace_elapsed',
    displayName: 'Grayson Lapsed',
    tier: 'tier1',
    dimension: 'Account state & privacy',
    purpose: 'Soft-deleted past the restoration window (pre-purge): login is permanently rejected.',
    testingUsage: 'Confirm logging in past the restoration window is permanently rejected with no restore offered.',
    deletionState: 'grace_elapsed',
    onboardingComplete: true,
    coverageNotes: [
      'deletion grace period elapsed (pre-purge)',
      'login permanently rejected, no restoration offered',
      'boundary partner of del_grace_open',
    ],
  },

  // ── Onboarding-wizard state ───────────────────────────────────────────────
  {
    slug: 'onb_unstarted',
    displayName: 'Newt Begin',
    tier: 'tier0',
    dimension: 'Onboarding wizard',
    purpose: 'Fresh signup with no onboarding rows: every wizard task reads as pending.',
    testingUsage: 'Confirm a fresh signup shows every onboarding-wizard task as pending.',
    coverageNotes: ['fresh signup, no onboarding rows (all tasks pending)'],
  },
  {
    slug: 'onb_partial',
    displayName: 'Hal Fway',
    tier: 'tier0',
    dimension: 'Onboarding wizard',
    purpose: 'Mid-wizard: personal details done, legacy claim paused, so the dashboard shows the resume card.',
    testingUsage: 'Confirm a mid-wizard member sees the dashboard resume card for the paused legacy-claim step.',
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'partial wizard',
      'personal_details done, legacy_claim paused mid-flow',
      'dashboard resume card',
    ],
  },
  {
    slug: 'onb_skipped',
    displayName: 'Bea Skip',
    tier: 'tier0',
    dimension: 'Onboarding wizard',
    purpose: 'Wizard with the legacy and club tasks explicitly skipped.',
    testingUsage: 'Confirm the wizard reflects explicitly skipped legacy and club tasks (not the same as pending).',
    onboardingTasks: {
      personal_details: 'completed',
      legacy_claim: 'skipped',
      club_affiliations: 'skipped',
    },
    coverageNotes: ['wizard with explicitly skipped legacy + club tasks'],
  },

  // ── Legacy claim variants ─────────────────────────────────────────────────
  {
    slug: 'legacy_unlinked_email',
    displayName: 'Pat Match',
    tier: 'tier0',
    dimension: 'Legacy claim',
    purpose: 'Unlinked legacy match carrying a legacy_email: the email-equality claim fast path and confirm-token card.',
    testingUsage: 'Walk the email-equality claim fast path and the confirm-token card for an unlinked legacy match that carries a legacy email.',
    legacy: { linked: false, realName: 'Pat Match', legacyEmail: 'pat.match@legacy.test' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'unlinked legacy match with legacy_email',
      'email-equality claim fast path + /claim/confirm token via simulated-email card',
    ],
  },
  {
    slug: 'legacy_unlinked_noemail',
    displayName: 'Jo Cardonly',
    tier: 'tier0',
    dimension: 'Legacy claim',
    purpose: 'Unlinked legacy match with no email: the historical-person card-confirm claim path.',
    testingUsage: 'Walk the historical-person card-confirm claim path for an unlinked match with no legacy email.',
    legacy: { linked: false, realName: 'Jo Cardonly' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'unlinked legacy match, null legacy_email',
      'historical-person card-confirm claim path',
    ],
  },
  {
    slug: 'legacy_linked',
    displayName: 'Sam Claimed',
    tier: 'tier1',
    dimension: 'Legacy claim',
    purpose: 'Completed legacy claim: member.legacy_member_id is set.',
    testingUsage: 'Confirm a completed legacy claim shows the member linked to its legacy account and no further claim is offered.',
    onboardingComplete: true,
    legacy: { linked: true, realName: 'Sam Claimed', legacyEmail: 'sam.claimed@legacy.test' },
    payments: [{ type: 'membership', status: 'succeeded', purchasedTier: 'tier1' }],
    coverageNotes: ['completed legacy claim (member.legacy_member_id set)', 'tier1'],
  },
  {
    slug: 'legacy_admin_flag',
    displayName: 'Cyrus Wasadmin',
    tier: 'tier1',
    dimension: 'Legacy claim',
    purpose: 'Claimed legacy account carrying the legacy admin flag: it must never confer a live admin role, so member.is_admin stays 0.',
    testingUsage: 'Confirm a claimed legacy account carrying the legacy admin flag does NOT gain a live admin role (member.is_admin stays 0).',
    legacy: {
      linked: true,
      realName: 'Cyrus Wasadmin',
      legacyEmail: 'cyrus.wasadmin@legacy.test',
      legacyIsAdmin: true,
    },
    onboardingComplete: true,
    coverageNotes: [
      'claimed legacy row with legacy_is_admin=1',
      'non-inheritance: live member.is_admin remains 0',
    ],
  },

  // ── Graded auto-link confidence (single-candidate path) ───────────────────
  {
    slug: 'autolink_high',
    displayName: 'Kenny Highmatch',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'High-confidence auto-link (exact name): the auto-confirm card.',
    testingUsage: 'Confirm the high-confidence (exact name) auto-link surfaces the one-click auto-confirm card.',
    legacy: { autoLinkConfidence: 'high' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: ['auto-link high confidence (exact name match)', 'auto-link-confirm card'],
  },
  {
    slug: 'autolink_medium',
    displayName: 'Robin Midmatch',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'Medium-confidence auto-link (same-surname name_variants match).',
    testingUsage: 'Confirm a medium-confidence same-surname auto-link is offered for review rather than auto-confirmed.',
    legacy: { autoLinkConfidence: 'medium' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: ['auto-link medium confidence (same-surname name_variants match)'],
  },
  {
    slug: 'autolink_low',
    displayName: 'Lou Lowmatch',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'Low-confidence / no-candidate auto-link: no card surfaces, falls through to manual claim.',
    testingUsage: 'Confirm a low/no-candidate auto-link surfaces no card and falls through to the manual claim path.',
    legacy: { autoLinkConfidence: 'low' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: ['auto-link low confidence (no name candidate)', 'falls through to manual claim'],
  },
  {
    slug: 'legacy_club_cards',
    displayName: 'Cam Cards',
    tier: 'tier0',
    dimension: 'Legacy club cards',
    purpose: 'Legacy-club-candidate cards across pending / declined / resolved / junk-suppressed states.',
    testingUsage: 'Confirm the onboarding wizard renders legacy-club cards across pending, declined, and resolved states and suppresses the junk one.',
    legacy: { linked: true, realName: 'Cam Cards' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'completed', club_affiliations: 'pending' },
    legacyClubCandidates: [
      { clubName: 'Pending Kick Club', classification: 'onboarding_visible', resolutionStatus: 'pending' },
      { clubName: 'Declined Shred Club', classification: 'onboarding_visible', resolutionStatus: 'rejected' },
      { clubName: 'Resolved Footbag Club', resolutionStatus: 'confirmed_current', mapped: true },
      { clubName: 'Junk Noise Club', classification: 'junk' },
    ],
    coverageNotes: [
      'legacy-club-candidate cards: pending / declined / resolved / junk-suppressed',
      'legacy-linked member hosting the affiliations; lands on the club step',
    ],
  },
  {
    slug: 'legacy_multi_candidate',
    displayName: 'Mandy Multiple',
    realName: 'Mandy Multiple',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'Two or more competing historical-person matches: the email anchor finds a provenance person, but the name query returns several same-name people, so the wizard offers a disambiguation choice rather than a single auto-link.',
    testingUsage: 'Confirm a member whose name matches several historical people is sent to the disambiguation choice instead of a one-click auto-link.',
    legacy: { autoLinkConfidence: 'high', competingNameCandidates: 1 },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'email anchor with multiple same-name historical-person candidates',
      'auto-link disambiguation (multiple-candidate review path)',
    ],
  },
  {
    slug: 'legacy_dob_disambiguated',
    displayName: 'Dana Datematch',
    realName: 'Dana Datematch',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'Two same-name historical-person matches, but the member and the legacy account share a date of birth: the tie-breaker narrows the competing set to the provenance person and auto-links instead of asking to disambiguate.',
    testingUsage: 'Confirm a shared member/legacy date of birth resolves an otherwise-tied same-name candidate set to a single auto-link.',
    legacy: { autoLinkConfidence: 'high', competingNameCandidates: 1, birthDate: '1990-04-12' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'email anchor with multiple same-name candidates plus a matching date of birth',
      'auto-link date-of-birth tie-breaker resolves the candidate set',
    ],
  },
  {
    slug: 'legacy_dob_conflict',
    displayName: 'Cody Conflict',
    realName: 'Cody Conflict',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'The member and the legacy account carry different dates of birth. Confirming the surfaced claim still links the account (a date-of-birth discrepancy never blocks) and raises a claim_dob_mismatch_review work-queue item for an admin, so a flagged conflict is visible end to end.',
    testingUsage: 'Log in, confirm the surfaced legacy-account claim, then confirm the conflicting date of birth raised an admin review item on /admin/work-queue without blocking the link.',
    legacy: { autoLinkConfidence: 'high', birthDate: '1985-06-15', legacyBirthDate: '1979-11-02' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'single high-confidence auto-link candidate with a mismatched date of birth',
      'the discrepancy flags an admin review item without blocking the claim',
    ],
  },

  // ── Club affiliations ─────────────────────────────────────────────────────
  {
    slug: 'club_multi',
    displayName: 'Polly Clubs',
    tier: 'tier1',
    dimension: 'Club affiliations',
    purpose: 'Several club affiliations at once: one current+primary, one former.',
    testingUsage: 'Confirm the profile shows multiple club affiliations with the current+primary one distinguished from the former one.',
    onboardingComplete: true,
    clubs: [
      { clubName: 'Harbor Kick Collective', current: true, primary: true },
      { clubName: 'Old Town Shred', current: false },
    ],
    coverageNotes: ['multiple club affiliations', 'one current+primary, one former'],
  },
  {
    slug: 'club_contact',
    displayName: 'Connie Tact',
    tier: 'tier1',
    dimension: 'Club affiliations',
    purpose: 'Current club affiliation flagged as the listed contact.',
    testingUsage: 'Confirm a current affiliation flagged as the listed contact renders as the club contact.',
    onboardingComplete: true,
    clubs: [{ clubName: 'Riverside Footbag', current: true, contact: true }],
    coverageNotes: ['current club affiliation flagged as listed contact'],
  },
  {
    slug: 'club_two_current',
    displayName: 'Dora Dual',
    tier: 'tier1',
    dimension: 'Club affiliations',
    purpose: 'Member already holding two current club affiliations (primary plus secondary): sits at the two-current-club cap, so adding a third current affiliation must be denied.',
    testingUsage: 'Confirm a member already at two current club affiliations is denied a third, exercising the two-current-club cap.',
    negative: true,
    onboardingComplete: true,
    clubs: [
      { clubName: 'North Side Footbag', current: true, primary: true },
      { clubName: 'South Side Footbag', current: true },
    ],
    coverageNotes: [
      'two current club affiliations (at the cap)',
      'one primary, one secondary',
      'two-current-club cap deny path',
    ],
  },

  // ── Club roles (authorization) ────────────────────────────────────────────
  {
    slug: 'club_leader',
    displayName: 'Lee Der',
    tier: 'tier1',
    dimension: 'Club roles (authorization)',
    purpose: 'Confirmed live club co-leader (bootstrap claim promoted to a club_leaders row): the allow case for club-content edits.',
    testingUsage: 'Act as a confirmed club co-leader to confirm it can edit its own club content (the allow case).',
    onboardingComplete: true,
    club: { clubName: 'Downtown Footbag', leader: true, role: 'co-leader' },
    coverageNotes: [
      'live club_leaders co-leader row (plus bootstrap-leader + signal provenance)',
      'allow: edits its own club content',
    ],
  },
  {
    slug: 'club_coleader',
    displayName: 'Coleen Coleader',
    tier: 'tier1',
    dimension: 'Club roles (authorization)',
    purpose: 'Live club co-leader: edits club content as an equal member of the leadership set.',
    testingUsage: 'Act as a co-leader to confirm equal edit rights over the shared club content.',
    onboardingComplete: true,
    club: { clubName: 'Seaside Footbag', role: 'co-leader' },
    coverageNotes: [
      'live club_leaders co-leader row',
      'allow content edit',
    ],
  },
  {
    slug: 'club_leader_b',
    displayName: 'Bart Otherclub',
    tier: 'tier1',
    dimension: 'Club roles (authorization)',
    purpose: 'Adjacent-owner: co-leads a different club, so club-scoped routes must deny it on clubs it does not co-lead (BOLA).',
    testingUsage: 'The adjacent-owner deny case: confirm a co-leader of a different club is rejected on clubs it does not co-lead (BOLA).',
    negative: true,
    onboardingComplete: true,
    club: { clubName: 'Hilltop Footbag', role: 'co-leader' },
    coverageNotes: [
      'live club_leaders co-leader row of a different club',
      'deny half: adjacent-owner BOLA catch',
    ],
  },
  {
    slug: 't0_ap_coleader',
    displayName: 'Ace Coleman',
    tier: 'tier0',
    dimension: 'Club roles (authorization)',
    purpose: 'Tier 0 whose current Active Player grant (not a paid tier) is what qualifies it to hold a live co-leader row.',
    testingUsage: 'Confirm a Tier 0 member whose current Active Player grant supplies Tier 1 benefits can hold and exercise a co-leader role.',
    onboardingComplete: true,
    activePlayer: { expiresAt: '2027-12-31T00:00:00.000Z' },
    club: { clubName: 'Lakeside Footbag', role: 'co-leader' },
    coverageNotes: [
      'tier0 with a current Active Player grant and no paid tier',
      'Active Player supplies the tier1-benefits that qualify a co-leader',
      'live club_leaders co-leader row',
    ],
  },
  {
    slug: 't0_bootstrap_leader',
    displayName: 'Booker Strapp',
    tier: 'tier0',
    dimension: 'Club roles (authorization)',
    purpose: 'Tier 0 bootstrap-leader claim awaiting promotion: a club_bootstrap_leaders row plus signal, with no live club_leaders row.',
    testingUsage: 'Confirm a Tier 0 bootstrap-leader claim awaiting promotion has no live co-leader edit rights yet.',
    onboardingComplete: true,
    club: { clubName: 'Ridgeway Footbag', leader: true },
    coverageNotes: [
      'tier0 bootstrap-leader claim (club_bootstrap_leaders row + signal)',
      'no live club_leaders row yet (claim not promoted)',
    ],
  },
  {
    slug: 'bootstrap_leader_onboarding',
    displayName: 'Brock Pending',
    tier: 'tier0',
    dimension: 'Club roles (authorization)',
    purpose: 'Tier 0 bootstrap-leader claim awaiting promotion held by a member whose onboarding is not finished: exercises a pending leadership claim alongside an incomplete-onboarding member.',
    testingUsage: 'Confirm a pending bootstrap-leader claim and an unfinished onboarding wizard coexist, with no live co-leader edit rights yet.',
    onboardingTasks: { personal_details: 'completed' },
    club: { clubName: 'Meadowbrook Footbag', leader: true },
    coverageNotes: [
      'tier0 bootstrap-leader claim (club_bootstrap_leaders row + signal)',
      'onboarding wizard not complete (required tasks pending)',
      'no live club_leaders row yet (claim not promoted)',
    ],
  },
  {
    slug: 'club_leader_second_attempt',
    displayName: 'Cleo Onlyone',
    tier: 'tier1',
    dimension: 'Club roles (authorization)',
    purpose: 'Co-leads one club through a live leadership row and is also a current affiliate of a second leaderless club: attempting to lead the second must be denied by the one-club-leadership rule.',
    testingUsage: 'Confirm a member who already co-leads one club is denied leadership of a second leaderless club it affiliates with, exercising the one-club-leadership rule.',
    negative: true,
    onboardingComplete: true,
    club: { clubName: 'Mainline Footbag', role: 'co-leader' },
    clubs: [{ clubName: 'Branchline Footbag', current: true }],
    coverageNotes: [
      'live club_leaders co-leader row on one club',
      'current affiliation on a second leaderless club',
      'one-club-leadership deny path',
    ],
  },

  // ── Payment history ───────────────────────────────────────────────────────
  {
    slug: 'pay_failed',
    displayName: 'Fay Lure',
    tier: 'tier0',
    dimension: 'Payments',
    purpose: 'Failed membership purchase: no tier granted, retry-from-failure surface.',
    testingUsage: 'Confirm a failed membership purchase grants no tier and offers a retry-from-failure surface.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'failed', purchasedTier: 'tier1' }],
    coverageNotes: ['failed membership purchase, no tier grant', 'retry-from-failure surface'],
  },
  {
    slug: 'pay_pending',
    displayName: 'Penny Ding',
    tier: 'tier0',
    dimension: 'Payments',
    purpose: 'Pending checkout: no tier granted yet.',
    testingUsage: 'Confirm a pending checkout grants no tier yet.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'pending', purchasedTier: 'tier2' }],
    coverageNotes: ['pending checkout, no tier grant yet'],
  },
  {
    slug: 'pay_refunded',
    displayName: 'Reff Und',
    tier: 'tier0',
    dimension: 'Payments',
    purpose: 'Refunded membership purchase.',
    testingUsage: 'Confirm a refunded membership purchase is reflected in payment history and confers no tier.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'refunded', purchasedTier: 'tier1' }],
    coverageNotes: ['refunded membership purchase'],
  },
  {
    slug: 'pay_donation',
    displayName: 'Donna Gift',
    tier: 'tier1',
    dimension: 'Payments',
    purpose: 'Membership plus a standalone donation in payment history.',
    testingUsage: 'Confirm a standalone donation appears in payment history alongside the tier-conferring membership.',
    onboardingComplete: true,
    payments: [
      { type: 'membership', status: 'succeeded', purchasedTier: 'tier1' },
      { type: 'donation', status: 'succeeded', amountCents: 5000, purchasedTier: null },
    ],
    coverageNotes: ['membership + standalone donation history'],
  },

  // ── Active Player status ──────────────────────────────────────────────────
  {
    slug: 'ap_active',
    displayName: 'Ace Tive',
    tier: 'tier0',
    dimension: 'Active Player',
    purpose: 'Current (non-expired) Active Player grant.',
    testingUsage: 'Confirm a current Active Player grant unlocks the Tier 1 benefits it confers on a Tier 0 member.',
    onboardingComplete: true,
    activePlayer: { expiresAt: '2027-12-31T00:00:00.000Z' },
    coverageNotes: ['current (non-expired) Active Player grant'],
  },
  {
    slug: 'ap_expired',
    displayName: 'Xavier Pyre',
    tier: 'tier0',
    dimension: 'Active Player',
    purpose: 'Recently-expired Active Player grant: the expiry-boundary partner of ap_active.',
    testingUsage: 'Confirm a recently-expired Active Player shows the expiry surface and has lost the conferred Tier 1 benefits.',
    onboardingComplete: true,
    activePlayer: { expiresAt: '2024-06-01T00:00:00.000Z', reasonCode: 'official_event_attendance' },
    coverageNotes: ['recently-expired Active Player', 'M_Active_Player_Expiry surface'],
  },

  // ── Mailing-list subscription state ───────────────────────────────────────
  {
    slug: 'ml_subscribed',
    displayName: 'Sue Scribe',
    tier: 'tier1',
    dimension: 'Mailing list',
    purpose: 'Subscribed mailing-list membership.',
    testingUsage: 'Confirm a subscribed member is included in list mail and shows the subscribed state.',
    onboardingComplete: true,
    mailingList: { status: 'subscribed' },
    coverageNotes: ['subscribed mailing-list membership'],
  },
  {
    slug: 'ml_unsubscribed',
    displayName: 'Una Sub',
    tier: 'tier1',
    dimension: 'Mailing list',
    purpose: 'Unsubscribed mailing-list membership.',
    testingUsage: 'Confirm an unsubscribed member is excluded from list mail and shows the unsubscribed state.',
    onboardingComplete: true,
    mailingList: { status: 'unsubscribed' },
    coverageNotes: ['unsubscribed mailing-list membership'],
  },

  // ── Honors & standing ─────────────────────────────────────────────────────
  {
    slug: 'honors_hof',
    displayName: 'Halle Famer',
    tier: 'tier2',
    dimension: 'Honors & standing',
    purpose: 'Hall-of-Fame honor: the lifetime badge renders on the live profile and the honor confers Tier 2.',
    testingUsage: 'Confirm the HoF lifetime badge renders on the live profile and the honor confers Tier 2.',
    honors: { hof: true },
    onboardingComplete: true,
    coverageNotes: ['HoF honor (is_hof=1)', 'lifetime badge render', 'honor-conferred tier2'],
  },
  {
    slug: 'honors_bap',
    displayName: 'Bappy Adder',
    tier: 'tier2',
    dimension: 'Honors & standing',
    purpose: 'Big-Add-Posse honor: the lifetime badge renders on the live profile and the honor confers Tier 2.',
    testingUsage: 'Confirm the BAP lifetime badge renders on the live profile and the honor confers Tier 2.',
    honors: { bap: true },
    onboardingComplete: true,
    coverageNotes: ['BAP honor (is_bap=1)', 'lifetime badge render', 'honor-conferred tier2'],
  },
  {
    slug: 'honors_board',
    displayName: 'Bo Director',
    tier: 'tier3',
    underlyingTier: 'tier2',
    dimension: 'Honors & standing',
    purpose: 'IFPA Board governance flag: sets the temporary Tier 3 governance status over an underlying tier.',
    testingUsage: 'Confirm the IFPA Board flag sets the temporary Tier 3 governance status over the underlying Tier 2.',
    honors: { board: true },
    onboardingComplete: true,
    coverageNotes: ['IFPA Board flag (is_board=1)', 'temporary Tier 3 governance over underlying tier2'],
  },

  // ── Edge-case identities ──────────────────────────────────────────────────
  {
    slug: 'edge_surname_a',
    displayName: 'Chris Tan',
    realName: 'Chris Tan',
    tier: 'tier1',
    dimension: 'Identity edge cases',
    purpose: 'Surname collision (Tan) with edge_surname_b.',
    testingUsage: 'Confirm search and disambiguation handle a surname collision (one of the two Tans).',
    onboardingComplete: true,
    coverageNotes: ['surname collision (Tan) with edge_surname_b'],
  },
  {
    slug: 'edge_surname_b',
    displayName: 'Pat Tan',
    realName: 'Pat Tan',
    tier: 'tier1',
    dimension: 'Identity edge cases',
    purpose: 'Surname collision (Tan) with edge_surname_a.',
    testingUsage: 'Confirm search and disambiguation handle the other side of the Tan surname collision.',
    onboardingComplete: true,
    coverageNotes: ['surname collision (Tan) with edge_surname_a'],
  },
  {
    slug: 'edge_dup_display_a',
    displayName: 'Jordan Lee',
    realName: 'Jordan Lee',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'Duplicate display name with edge_dup_display_b.',
    testingUsage: 'Confirm duplicate display names stay distinguishable (one of the two Jordan Lees).',
    onboardingComplete: true,
    coverageNotes: ['duplicate display name with edge_dup_display_b'],
  },
  {
    slug: 'edge_dup_display_b',
    displayName: 'Jordan Lee',
    realName: 'Jordan Lee',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'Duplicate display name with edge_dup_display_a.',
    testingUsage: 'Confirm the other duplicate display name renders and resolves distinctly.',
    onboardingComplete: true,
    coverageNotes: ['duplicate display name with edge_dup_display_a'],
  },
  {
    slug: 'edge_unicode',
    displayName: 'Renée Müller',
    realName: 'Renée Müller',
    tier: 'tier1',
    dimension: 'Identity edge cases',
    purpose: 'Unicode / diacritic display and real name.',
    testingUsage: 'Confirm a unicode/diacritic name renders and searches correctly.',
    onboardingComplete: true,
    coverageNotes: ['unicode / diacritic display + real name'],
  },
  {
    // RTL override (U+202E) + pop directional formatting (U+202C) around a span.
    slug: 'edge_rtl',
    displayName: 'Sara ‮reparK‬',
    realName: 'Sara Krapper',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'RTL-override control characters in the display name.',
    testingUsage: 'Confirm RTL-override control characters in a display name render safely without corrupting surrounding layout.',
    onboardingComplete: true,
    coverageNotes: ['RTL-override control characters in display name'],
  },
  {
    // Leading Cyrillic 'А' (U+0410) homoglyph of Latin 'A'.
    slug: 'edge_homoglyph',
    displayName: 'Аlex Kerr',
    realName: 'Alex Kerr',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'Cyrillic homoglyph in the display name.',
    testingUsage: 'Confirm a Cyrillic homoglyph in a display name is handled safely in search and display.',
    onboardingComplete: true,
    coverageNotes: ['Cyrillic homoglyph in display name'],
  },

  // ── Event roles (authorization) — BLOCKED: organizer edit routes not built ──
  {
    slug: 'eo_organizer',
    displayName: 'Olive Organizer',
    tier: 'tier2',
    dimension: 'Event roles (authorization)',
    purpose: 'Event creator / primary organizer: the allow case for organizer-gated event edits.',
    testingUsage: 'When organizer routes ship, act as the event organizer to confirm it can edit the event, manage co-organizers, and view participants.',
    blockedBy: 'event organizer edit routes not built',
    userStory: 'Event organizers edit their own event, manage its co-organizers, and view its participants.',
    coverageNotes: ['event organizer (creator)', 'allow: edits own event'],
  },
  {
    slug: 'eo_corganizer',
    displayName: 'Cory Coorg',
    tier: 'tier1',
    dimension: 'Event roles (authorization)',
    purpose: 'Event co-organizer on a shared event: equal organizer rights.',
    testingUsage: 'When organizer routes ship, confirm a co-organizer has equal edit rights on the shared event.',
    blockedBy: 'event organizer edit routes not built',
    userStory: 'A co-organizer added to an event shares full edit rights with the creator.',
    coverageNotes: ['event co-organizer', 'allow: edits shared event'],
  },
  {
    slug: 'eo_other_organizer',
    displayName: 'Otto Elsewhere',
    tier: 'tier2',
    dimension: 'Event roles (authorization)',
    purpose: 'Adjacent-owner: organizes a different event, so event-scoped routes must deny it (BOLA).',
    testingUsage: 'When organizer routes ship, the deny case: confirm an organizer of a different event is rejected on events it does not organize.',
    blockedBy: 'event organizer edit routes not built',
    userStory: 'An organizer of one event must not be able to edit a different event they do not run.',
    negative: true,
    coverageNotes: ['organizes a different event', 'deny: adjacent-owner BOLA'],
  },

  // ── Group roles (authorization) — BLOCKED: group schema and routes not built ─
  {
    slug: 'go_owner',
    displayName: 'Gwen Owner',
    tier: 'tier1',
    dimension: 'Group roles (authorization)',
    purpose: 'Group creator / owner: the allow case for group management.',
    testingUsage: 'When groups ship, confirm the owner can edit the group, manage members and co-owners, and moderate the email queue.',
    blockedBy: 'group schema and routes not built',
    userStory: 'A member who creates a group edits it, manages its members and co-owners, and moderates its email queue.',
    coverageNotes: ['group owner', 'allow: manages own group'],
  },
  {
    slug: 'go_coowner',
    displayName: 'Coyle Coowner',
    tier: 'tier1',
    dimension: 'Group roles (authorization)',
    purpose: 'Group co-owner: equal management rights.',
    testingUsage: 'When groups ship, confirm a co-owner has equal management rights on the group.',
    blockedBy: 'group schema and routes not built',
    userStory: 'A co-owner added to a group shares full management rights with the creator.',
    coverageNotes: ['group co-owner', 'allow: manages group'],
  },
  {
    slug: 'go_member',
    displayName: 'Mei Member',
    tier: 'tier1',
    dimension: 'Group roles (authorization)',
    purpose: 'Group member: member-scoped actions only (participate, leave, upload to allowed surfaces).',
    testingUsage: 'When groups ship, confirm a plain member can do member-scoped group actions but not owner-only management.',
    blockedBy: 'group schema and routes not built',
    userStory: 'A group member can take part and upload to allowed surfaces but cannot manage the group.',
    coverageNotes: ['group member', 'allow: member actions; deny: owner actions'],
  },
  {
    slug: 'go_nonmember',
    displayName: 'Noah Outside',
    tier: 'tier1',
    dimension: 'Group roles (authorization)',
    purpose: 'Non-member: must be denied member-only group actions.',
    testingUsage: 'When groups ship, the deny case: confirm a non-member is rejected from member-only group actions.',
    blockedBy: 'group schema and routes not built',
    userStory: 'Someone who is not in a group must not be able to take member-only actions in it.',
    negative: true,
    coverageNotes: ['non-member', 'deny: member-only actions'],
  },
  {
    slug: 'go_other_owner',
    displayName: 'Ona Othergroup',
    tier: 'tier1',
    dimension: 'Group roles (authorization)',
    purpose: 'Adjacent-owner: owns a different group, so group-scoped routes must deny it (BOLA).',
    testingUsage: 'When groups ship, the deny case: confirm an owner of a different group is rejected on groups it does not own.',
    blockedBy: 'group schema and routes not built',
    userStory: 'An owner of one group must not be able to manage a different group.',
    negative: true,
    coverageNotes: ['owns a different group', 'deny: adjacent-owner BOLA'],
  },

  // ── Vote eligibility — BLOCKED: voting routes and eligibility snapshot not built ─
  {
    slug: 'vote_inclusion_list',
    displayName: 'Ines List',
    tier: 'tier0',
    dimension: 'Vote eligibility',
    purpose: "Member on a vote's explicit inclusion list: the allow case.",
    testingUsage: 'When voting ships, confirm a member on the explicit inclusion list can view and cast the vote.',
    blockedBy: 'voting routes and eligibility snapshot not built',
    userStory: "A member named on a vote's inclusion list can view and cast that vote.",
    coverageNotes: ['on explicit inclusion list', 'allow: eligible to vote'],
  },
  {
    slug: 'vote_tier_qualified',
    displayName: 'Tess Qualified',
    tier: 'tier2',
    dimension: 'Vote eligibility',
    purpose: 'Member who qualifies by a tier/flag eligibility rule rather than an inclusion list.',
    testingUsage: 'When voting ships, confirm a member whose tier or flags satisfy the eligibility rule can vote.',
    blockedBy: 'voting routes and eligibility snapshot not built',
    userStory: "A member whose tier or standing meets a vote's eligibility rule can cast it.",
    coverageNotes: ['qualifies by tier/flag rule', 'allow: eligible to vote'],
  },
  {
    slug: 'vote_t0_no_ap',
    displayName: 'Tad Floor',
    tier: 'tier0',
    dimension: 'Vote eligibility',
    purpose: 'Tier 0 without Active Player on a Tier-1-restricted vote: the deny case.',
    testingUsage: 'When voting ships, the deny case: confirm a Tier 0 member with no Active Player is rejected from a Tier-1-restricted vote.',
    blockedBy: 'voting routes and eligibility snapshot not built',
    userStory: 'A member below the required tier (and without an Active Player grant) is shut out of a tier-restricted vote.',
    negative: true,
    coverageNotes: ['tier0, no Active Player', 'deny: tier-restricted vote'],
  },
  {
    slug: 'vote_unqualified',
    displayName: 'Una Ineligible',
    tier: 'tier1',
    dimension: 'Vote eligibility',
    purpose: 'Member meeting no tier, flag, or inclusion rule: the deny case.',
    testingUsage: 'When voting ships, the deny case: confirm a member who meets no eligibility rule cannot vote.',
    blockedBy: 'voting routes and eligibility snapshot not built',
    userStory: 'A member who meets no inclusion, tier, or flag rule cannot cast the vote.',
    negative: true,
    coverageNotes: ['meets no eligibility rule', 'deny: ineligible'],
  },

  // ── Claimed-legacy banned — BLOCKED: legacy_members.banned column not added ──
  {
    slug: 'legacy_banned_claimed',
    displayName: 'Ben Wasbanned',
    tier: 'tier0',
    dimension: 'Legacy claim',
    purpose: 'Claimed legacy record carrying the legacy banned flag: it is audit metadata only and must not impose live disciplinary state.',
    testingUsage: 'When the legacy banned column exists, confirm claiming a banned legacy record succeeds and the legacy ban does not gate or discipline the live account.',
    blockedBy: 'legacy_members.banned column not added',
    userStory: 'Someone whose old footbag.org record was banned can still claim it; the old ban is history, not a live restriction on the new account.',
    coverageNotes: ['claimed legacy row with banned=1', 'legacy ban is audit-only, not a live gate'],
  },
];
