/**
 * Maintainer-curated baseline persona catalog.
 *
 * The shared reference set every maintainer and paid tester switches between.
 * Each entry carries a `dimension` (the authorization axis it belongs to), a
 * `purpose` (the code path or gate it exists to exercise), and `coverageNotes`;
 * the catalog doubles as a coverage matrix that surfaces gaps as the testing
 * surface grows. New test slices add personas here rather than inventing fixture
 * rows.
 *
 * The catalog covers the tier ladder and admin role plus onboarding-wizard
 * state, legacy-claim variants, graded auto-link confidence (high/medium/low),
 * legacy-club-candidate cards (pending/declined/resolved/junk), club
 * affiliations, payment history, Active Player expiry, mailing-list
 * subscription state, and edge-case identities.
 */
import type { PersonaSpec } from './personaFactory';

export const CANONICAL_PERSONAS: PersonaSpec[] = [
  {
    slug: 't0_fresh',
    displayName: 'Tia Zero',
    tier: 'tier0',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 0 floor actor: the just-below case every tier-gated route must deny.',
    onboardingComplete: true,
    coverageNotes: ['tier0 baseline', 'onboarding wizard complete', 'no payment history'],
  },
  {
    slug: 't1_paid',
    displayName: 'Won Paid',
    tier: 'tier1',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 1 member: the first paid-benefits gate.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'succeeded', purchasedTier: 'tier1' }],
    coverageNotes: ['tier1', 'one successful membership purchase', 'tier1 benefits gate'],
  },
  {
    slug: 't2_paid',
    displayName: 'Tu Paid',
    tier: 'tier2',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 2 member: full paid-tier benefits gate.',
    onboardingComplete: true,
    payments: [
      { type: 'membership', status: 'succeeded', purchasedTier: 'tier1' },
      { type: 'membership', status: 'succeeded', purchasedTier: 'tier2' },
    ],
    coverageNotes: ['tier2', 'tier1 + tier2 purchase history', 'tier2 benefits gate'],
  },
  {
    slug: 't3_comped',
    displayName: 'Tree Comped',
    tier: 'tier3',
    underlyingTier: 'tier2',
    dimension: 'Tier ladder & admin',
    purpose: 'Tier 3 governance tier reached without payment (admin-comped); underlying Tier 2.',
    onboardingComplete: true,
    coverageNotes: [
      'tier3 governance tier',
      'admin-comped (no payment)',
      'underlying tier2',
    ],
  },
  {
    slug: 'admin_t2',
    displayName: 'Addie Min',
    tier: 'tier2',
    isAdmin: true,
    dimension: 'Tier ladder & admin',
    purpose: 'Admin role: exercises admin nav and every admin-gated surface (allow half of admin routes).',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'succeeded', purchasedTier: 'tier2' }],
    coverageNotes: ['admin role', 'tier2', 'admin nav + admin-gated surfaces'],
  },

  // ── Account state & privacy (catastrophic auth / privacy surfaces) ────────
  {
    slug: 'unverified',
    displayName: 'Eve Unverified',
    tier: 'tier0',
    dimension: 'Account state & privacy',
    purpose: 'Registered but email not yet verified: login is blocked and member search excludes the account until verification.',
    emailVerified: false,
    coverageNotes: [
      'registered-unverified (email_verified_at NULL)',
      'login blocked until verification',
      'excluded from authenticated member search',
    ],
  },
  {
    slug: 'deceased',
    displayName: 'Mort Memoriam',
    tier: 'tier2',
    dimension: 'Account state & privacy',
    purpose: 'Deceased member: login disabled and search/roster-excluded, while HoF/BAP honors and history stay visible.',
    isDeceased: true,
    honors: { hof: true },
    onboardingComplete: true,
    coverageNotes: [
      'deceased (is_deceased=1): login disabled, search-excluded, roster-removed',
      'honors (HoF) and historical contributions preserved on render',
    ],
  },
  {
    slug: 'del_grace_open',
    displayName: 'Grace Open',
    tier: 'tier1',
    dimension: 'Account state & privacy',
    purpose: 'Soft-deleted and still inside the restoration window: logging in offers account restoration.',
    deletionState: 'grace_open',
    onboardingComplete: true,
    coverageNotes: [
      'deletion grace period still open',
      'login presents the restoration screen',
      'boundary partner of del_grace_elapsed',
    ],
  },
  {
    slug: 'del_grace_elapsed',
    displayName: 'Grayson Lapsed',
    tier: 'tier1',
    dimension: 'Account state & privacy',
    purpose: 'Soft-deleted past the restoration window (pre-purge): login is permanently rejected.',
    deletionState: 'grace_elapsed',
    onboardingComplete: true,
    coverageNotes: [
      'deletion grace period elapsed (pre-purge)',
      'login permanently rejected, no restoration offered',
      'boundary partner of del_grace_open',
    ],
  },

  // ── Onboarding-wizard state ───────────────────────────────────────────────
  {
    slug: 'onb_unstarted',
    displayName: 'Newt Begin',
    tier: 'tier0',
    dimension: 'Onboarding wizard',
    purpose: 'Fresh signup with no onboarding rows: every wizard task reads as pending.',
    coverageNotes: ['fresh signup, no onboarding rows (all tasks pending)'],
  },
  {
    slug: 'onb_partial',
    displayName: 'Hal Fway',
    tier: 'tier0',
    dimension: 'Onboarding wizard',
    purpose: 'Mid-wizard: personal details done, legacy claim paused, so the dashboard shows the resume card.',
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'partial wizard',
      'personal_details done, legacy_claim paused mid-flow',
      'dashboard resume card',
    ],
  },
  {
    slug: 'onb_skipped',
    displayName: 'Bea Skip',
    tier: 'tier0',
    dimension: 'Onboarding wizard',
    purpose: 'Wizard with the legacy and club tasks explicitly skipped.',
    onboardingTasks: {
      personal_details: 'completed',
      legacy_claim: 'skipped',
      club_affiliations: 'skipped',
    },
    coverageNotes: ['wizard with explicitly skipped legacy + club tasks'],
  },

  // ── Legacy claim variants ─────────────────────────────────────────────────
  {
    slug: 'legacy_unlinked_email',
    displayName: 'Pat Match',
    tier: 'tier0',
    dimension: 'Legacy claim',
    purpose: 'Unlinked legacy match carrying a legacy_email: the email-equality claim fast path and confirm-token card.',
    legacy: { linked: false, realName: 'Pat Match', legacyEmail: 'pat.match@legacy.test' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: [
      'unlinked legacy match with legacy_email',
      'email-equality claim fast path + /claim/confirm token via simulated-email card',
    ],
  },
  {
    slug: 'legacy_unlinked_noemail',
    displayName: 'Jo Cardonly',
    tier: 'tier0',
    dimension: 'Legacy claim',
    purpose: 'Unlinked legacy match with no email: the historical-person card-confirm claim path.',
    legacy: { linked: false, realName: 'Jo Cardonly' },
    coverageNotes: [
      'unlinked legacy match, null legacy_email',
      'historical-person card-confirm claim path',
    ],
  },
  {
    slug: 'legacy_linked',
    displayName: 'Sam Claimed',
    tier: 'tier1',
    dimension: 'Legacy claim',
    purpose: 'Completed legacy claim: member.legacy_member_id is set.',
    onboardingComplete: true,
    legacy: { linked: true, realName: 'Sam Claimed', legacyEmail: 'sam.claimed@legacy.test' },
    payments: [{ type: 'membership', status: 'succeeded', purchasedTier: 'tier1' }],
    coverageNotes: ['completed legacy claim (member.legacy_member_id set)', 'tier1'],
  },
  {
    slug: 'legacy_admin_flag',
    displayName: 'Cyrus Wasadmin',
    tier: 'tier1',
    dimension: 'Legacy claim',
    purpose: 'Claimed legacy account carrying the legacy admin flag: it must never confer a live admin role, so member.is_admin stays 0.',
    legacy: {
      linked: true,
      realName: 'Cyrus Wasadmin',
      legacyEmail: 'cyrus.wasadmin@legacy.test',
      legacyIsAdmin: true,
    },
    onboardingComplete: true,
    coverageNotes: [
      'claimed legacy row with legacy_is_admin=1',
      'non-inheritance: live member.is_admin remains 0',
    ],
  },

  // ── Graded auto-link confidence (single-candidate path) ───────────────────
  {
    slug: 'autolink_high',
    displayName: 'Kenny Highmatch',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'High-confidence auto-link (exact name): the auto-confirm card.',
    legacy: { autoLinkConfidence: 'high' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: ['auto-link high confidence (exact name match)', 'auto-link-confirm card'],
  },
  {
    slug: 'autolink_medium',
    displayName: 'Robin Midmatch',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'Medium-confidence auto-link (same-surname name_variants match).',
    legacy: { autoLinkConfidence: 'medium' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: ['auto-link medium confidence (same-surname name_variants match)'],
  },
  {
    slug: 'autolink_low',
    displayName: 'Lou Lowmatch',
    tier: 'tier0',
    dimension: 'Auto-link confidence',
    purpose: 'Low-confidence / no-candidate auto-link: no card surfaces, falls through to manual claim.',
    legacy: { autoLinkConfidence: 'low' },
    onboardingTasks: { personal_details: 'completed', legacy_claim: 'in_progress_paused' },
    coverageNotes: ['auto-link low confidence (no name candidate)', 'falls through to manual claim'],
  },
  {
    slug: 'legacy_club_cards',
    displayName: 'Cam Cards',
    tier: 'tier0',
    dimension: 'Legacy club cards',
    purpose: 'Legacy-club-candidate cards across pending / declined / resolved / junk-suppressed states.',
    legacy: { linked: false, realName: 'Cam Cards' },
    legacyClubCandidates: [
      { clubName: 'Pending Kick Club', classification: 'onboarding_visible', resolutionStatus: 'pending' },
      { clubName: 'Declined Shred Club', classification: 'onboarding_visible', resolutionStatus: 'rejected' },
      { clubName: 'Resolved Footbag Club', resolutionStatus: 'confirmed_current', mapped: true },
      { clubName: 'Junk Noise Club', classification: 'junk' },
    ],
    coverageNotes: [
      'legacy-club-candidate cards: pending / declined / resolved / junk-suppressed',
      'unlinked legacy identity hosting the affiliations',
    ],
  },

  // ── Club affiliations ─────────────────────────────────────────────────────
  {
    slug: 'club_multi',
    displayName: 'Polly Clubs',
    tier: 'tier1',
    dimension: 'Club affiliations',
    purpose: 'Several club affiliations at once: one current+primary, one former.',
    onboardingComplete: true,
    clubs: [
      { clubName: 'Harbor Kick Collective', current: true, primary: true },
      { clubName: 'Old Town Shred', current: false },
    ],
    coverageNotes: ['multiple club affiliations', 'one current+primary, one former'],
  },
  {
    slug: 'club_contact',
    displayName: 'Connie Tact',
    tier: 'tier1',
    dimension: 'Club affiliations',
    purpose: 'Current club affiliation flagged as the listed contact.',
    onboardingComplete: true,
    clubs: [{ clubName: 'Riverside Footbag', current: true, contact: true }],
    coverageNotes: ['current club affiliation flagged as listed contact'],
  },

  // ── Club roles (authorization) ────────────────────────────────────────────
  {
    slug: 'club_leader',
    displayName: 'Lee Der',
    tier: 'tier1',
    dimension: 'Club roles (authorization)',
    purpose: 'Confirmed live club co-leader (bootstrap claim promoted to a club_leaders row): the allow case for club-content edits.',
    onboardingComplete: true,
    club: { clubName: 'Downtown Footbag', leader: true, role: 'co-leader' },
    coverageNotes: [
      'live club_leaders co-leader row (plus bootstrap-leader + signal provenance)',
      'allow: edits its own club content',
    ],
  },
  {
    slug: 'club_coleader',
    displayName: 'Coleen Coleader',
    tier: 'tier1',
    dimension: 'Club roles (authorization)',
    purpose: 'Live club co-leader: edits club content as an equal member of the leadership set.',
    onboardingComplete: true,
    club: { clubName: 'Seaside Footbag', role: 'co-leader' },
    coverageNotes: [
      'live club_leaders co-leader row',
      'allow content edit',
    ],
  },
  {
    slug: 'club_leader_b',
    displayName: 'Bart Otherclub',
    tier: 'tier1',
    dimension: 'Club roles (authorization)',
    purpose: 'Adjacent-owner: co-leads a different club, so club-scoped routes must deny it on clubs it does not co-lead (BOLA).',
    negative: true,
    onboardingComplete: true,
    club: { clubName: 'Hilltop Footbag', role: 'co-leader' },
    coverageNotes: [
      'live club_leaders co-leader row of a different club',
      'deny half: adjacent-owner BOLA catch',
    ],
  },
  {
    slug: 't0_ap_coleader',
    displayName: 'Ace Coleman',
    tier: 'tier0',
    dimension: 'Club roles (authorization)',
    purpose: 'Tier 0 whose current Active Player grant (not a paid tier) is what qualifies it to hold a live co-leader row.',
    onboardingComplete: true,
    activePlayer: { expiresAt: '2027-12-31T00:00:00.000Z' },
    club: { clubName: 'Lakeside Footbag', role: 'co-leader' },
    coverageNotes: [
      'tier0 with a current Active Player grant and no paid tier',
      'Active Player supplies the tier1-benefits that qualify a co-leader',
      'live club_leaders co-leader row',
    ],
  },
  {
    slug: 't0_bootstrap_leader',
    displayName: 'Booker Strapp',
    tier: 'tier0',
    dimension: 'Club roles (authorization)',
    purpose: 'Tier 0 bootstrap-leader claim awaiting promotion: a club_bootstrap_leaders row plus signal, with no live club_leaders row.',
    onboardingComplete: true,
    club: { clubName: 'Ridgeway Footbag', leader: true },
    coverageNotes: [
      'tier0 bootstrap-leader claim (club_bootstrap_leaders row + signal)',
      'no live club_leaders row yet (claim not promoted)',
    ],
  },

  // ── Payment history ───────────────────────────────────────────────────────
  {
    slug: 'pay_failed',
    displayName: 'Fay Lure',
    tier: 'tier0',
    dimension: 'Payments',
    purpose: 'Failed membership purchase: no tier granted, retry-from-failure surface.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'failed', purchasedTier: 'tier1' }],
    coverageNotes: ['failed membership purchase, no tier grant', 'retry-from-failure surface'],
  },
  {
    slug: 'pay_pending',
    displayName: 'Penny Ding',
    tier: 'tier0',
    dimension: 'Payments',
    purpose: 'Pending checkout: no tier granted yet.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'pending', purchasedTier: 'tier2' }],
    coverageNotes: ['pending checkout, no tier grant yet'],
  },
  {
    slug: 'pay_refunded',
    displayName: 'Reff Und',
    tier: 'tier0',
    dimension: 'Payments',
    purpose: 'Refunded membership purchase.',
    onboardingComplete: true,
    payments: [{ type: 'membership', status: 'refunded', purchasedTier: 'tier1' }],
    coverageNotes: ['refunded membership purchase'],
  },
  {
    slug: 'pay_donation',
    displayName: 'Donna Gift',
    tier: 'tier1',
    dimension: 'Payments',
    purpose: 'Membership plus a standalone donation in payment history.',
    onboardingComplete: true,
    payments: [
      { type: 'membership', status: 'succeeded', purchasedTier: 'tier1' },
      { type: 'donation', status: 'succeeded', amountCents: 5000, purchasedTier: null },
    ],
    coverageNotes: ['membership + standalone donation history'],
  },

  // ── Active Player status ──────────────────────────────────────────────────
  {
    slug: 'ap_active',
    displayName: 'Ace Tive',
    tier: 'tier0',
    dimension: 'Active Player',
    purpose: 'Current (non-expired) Active Player grant.',
    onboardingComplete: true,
    activePlayer: { expiresAt: '2027-12-31T00:00:00.000Z' },
    coverageNotes: ['current (non-expired) Active Player grant'],
  },
  {
    slug: 'ap_expired',
    displayName: 'Xavier Pyre',
    tier: 'tier0',
    dimension: 'Active Player',
    purpose: 'Recently-expired Active Player grant: the expiry-boundary partner of ap_active.',
    onboardingComplete: true,
    activePlayer: { expiresAt: '2024-06-01T00:00:00.000Z', reasonCode: 'official_event_attendance' },
    coverageNotes: ['recently-expired Active Player', 'M_Active_Player_Expiry surface'],
  },

  // ── Mailing-list subscription state ───────────────────────────────────────
  {
    slug: 'ml_subscribed',
    displayName: 'Sue Scribe',
    tier: 'tier1',
    dimension: 'Mailing list',
    purpose: 'Subscribed mailing-list membership.',
    onboardingComplete: true,
    mailingList: { status: 'subscribed' },
    coverageNotes: ['subscribed mailing-list membership'],
  },
  {
    slug: 'ml_unsubscribed',
    displayName: 'Una Sub',
    tier: 'tier1',
    dimension: 'Mailing list',
    purpose: 'Unsubscribed mailing-list membership.',
    onboardingComplete: true,
    mailingList: { status: 'unsubscribed' },
    coverageNotes: ['unsubscribed mailing-list membership'],
  },

  // ── Honors & standing ─────────────────────────────────────────────────────
  {
    slug: 'honors_hof',
    displayName: 'Halle Famer',
    tier: 'tier2',
    dimension: 'Honors & standing',
    purpose: 'Hall-of-Fame honor: the lifetime badge renders on the live profile and the honor confers Tier 2.',
    honors: { hof: true },
    onboardingComplete: true,
    coverageNotes: ['HoF honor (is_hof=1)', 'lifetime badge render', 'honor-conferred tier2'],
  },
  {
    slug: 'honors_bap',
    displayName: 'Bappy Adder',
    tier: 'tier2',
    dimension: 'Honors & standing',
    purpose: 'Big-Add-Posse honor: the lifetime badge renders on the live profile and the honor confers Tier 2.',
    honors: { bap: true },
    onboardingComplete: true,
    coverageNotes: ['BAP honor (is_bap=1)', 'lifetime badge render', 'honor-conferred tier2'],
  },
  {
    slug: 'honors_board',
    displayName: 'Bo Director',
    tier: 'tier3',
    underlyingTier: 'tier2',
    dimension: 'Honors & standing',
    purpose: 'IFPA Board governance flag: sets the temporary Tier 3 governance status over an underlying tier.',
    honors: { board: true },
    onboardingComplete: true,
    coverageNotes: ['IFPA Board flag (is_board=1)', 'temporary Tier 3 governance over underlying tier2'],
  },

  // ── Edge-case identities ──────────────────────────────────────────────────
  {
    slug: 'edge_surname_a',
    displayName: 'Chris Tan',
    realName: 'Chris Tan',
    tier: 'tier1',
    dimension: 'Identity edge cases',
    purpose: 'Surname collision (Tan) with edge_surname_b.',
    onboardingComplete: true,
    coverageNotes: ['surname collision (Tan) with edge_surname_b'],
  },
  {
    slug: 'edge_surname_b',
    displayName: 'Pat Tan',
    realName: 'Pat Tan',
    tier: 'tier1',
    dimension: 'Identity edge cases',
    purpose: 'Surname collision (Tan) with edge_surname_a.',
    onboardingComplete: true,
    coverageNotes: ['surname collision (Tan) with edge_surname_a'],
  },
  {
    slug: 'edge_dup_display_a',
    displayName: 'Jordan Lee',
    realName: 'Jordan Lee',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'Duplicate display name with edge_dup_display_b.',
    onboardingComplete: true,
    coverageNotes: ['duplicate display name with edge_dup_display_b'],
  },
  {
    slug: 'edge_dup_display_b',
    displayName: 'Jordan Lee',
    realName: 'Jordan Lee',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'Duplicate display name with edge_dup_display_a.',
    onboardingComplete: true,
    coverageNotes: ['duplicate display name with edge_dup_display_a'],
  },
  {
    slug: 'edge_unicode',
    displayName: 'Renée Müller',
    realName: 'Renée Müller',
    tier: 'tier1',
    dimension: 'Identity edge cases',
    purpose: 'Unicode / diacritic display and real name.',
    onboardingComplete: true,
    coverageNotes: ['unicode / diacritic display + real name'],
  },
  {
    // RTL override (U+202E) + pop directional formatting (U+202C) around a span.
    slug: 'edge_rtl',
    displayName: 'Sara ‮reparK‬',
    realName: 'Sara Krapper',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'RTL-override control characters in the display name.',
    onboardingComplete: true,
    coverageNotes: ['RTL-override control characters in display name'],
  },
  {
    // Leading Cyrillic 'А' (U+0410) homoglyph of Latin 'A'.
    slug: 'edge_homoglyph',
    displayName: 'Аlex Kerr',
    realName: 'Alex Kerr',
    tier: 'tier0',
    dimension: 'Identity edge cases',
    purpose: 'Cyrillic homoglyph in the display name.',
    onboardingComplete: true,
    coverageNotes: ['Cyrillic homoglyph in display name'],
  },
];
