/**
 * The arithmetic behind the staging load check.
 *
 * These four functions decide what number the origin-latency alarm threshold is
 * argued from, so an off-by-one in the percentile rank or a cookie the jar
 * parser silently drops would produce a plausible-looking baseline that is
 * wrong. Both have a specific trap worth pinning: nearest-rank percentiles are
 * commonly written with a floor rather than a ceiling, which reports the sample
 * below the one asked for; and curl marks an HttpOnly line in its jar with a
 * leading `#HttpOnly_`, so the ordinary "skip comment lines" reading throws away
 * the session cookie and every signed-in request then measures the signed-out
 * page.
 */
import { describe, it, expect } from 'vitest';

import {
  percentile,
  summarize,
  isError,
  parseCookieJar,
  buildScenario,
  expandScenario,
  type RequestSample,
} from '../../scripts/loadCheck';

function sample(path: string, status: number, ms: number): RequestSample {
  return { path, status, ms };
}

describe('percentile', () => {
  const sorted = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100];

  it('takes the nearest rank at or above the requested share', () => {
    expect(percentile(sorted, 50)).toBe(50);
    expect(percentile(sorted, 90)).toBe(90);
    expect(percentile(sorted, 95)).toBe(100);
    expect(percentile(sorted, 100)).toBe(100);
  });

  it('never reads below the first sample', () => {
    expect(percentile(sorted, 1)).toBe(10);
    expect(percentile([42], 50)).toBe(42);
  });

  it('reports zero for an empty sample rather than a number that is not one', () => {
    expect(percentile([], 90)).toBe(0);
  });
});

describe('isError', () => {
  it('counts a request that produced no response', () => {
    expect(isError(sample('/', 0, 12))).toBe(true);
  });

  it('counts a server error', () => {
    expect(isError(sample('/', 500, 12))).toBe(true);
    expect(isError(sample('/', 503, 12))).toBe(true);
  });

  it('does not count a client error, which is the server working', () => {
    expect(isError(sample('/', 404, 12))).toBe(false);
    expect(isError(sample('/', 302, 12))).toBe(false);
    expect(isError(sample('/', 200, 12))).toBe(false);
  });
});

describe('summarize', () => {
  const samples: RequestSample[] = [
    sample('/', 200, 100),
    sample('/', 200, 200),
    sample('/', 500, 300),
    sample('/events', 200, 400),
  ];

  it('reports the error rate over every request, not only the failing path', () => {
    const summary = summarize(samples, 10);
    expect(summary.requests).toBe(4);
    expect(summary.errors).toBe(1);
    expect(summary.errorRate).toBeCloseTo(0.25);
  });

  it('reports throughput per second and per minute from the elapsed time', () => {
    const summary = summarize(samples, 10);
    expect(summary.requestsPerSecond).toBeCloseTo(0.4);
    expect(summary.requestsPerMinute).toBeCloseTo(24);
  });

  it('breaks the distribution down per path, sorted so two runs compare', () => {
    const summary = summarize(samples, 10);
    expect(summary.perPath.map((row) => row.path)).toEqual(['/', '/events']);
    expect(summary.perPath[0].count).toBe(3);
    expect(summary.perPath[0].errors).toBe(1);
    expect(summary.perPath[1].count).toBe(1);
  });

  it('survives a run that recorded nothing', () => {
    const summary = summarize([], 0);
    expect(summary.requests).toBe(0);
    expect(summary.errorRate).toBe(0);
    expect(summary.requestsPerSecond).toBe(0);
    expect(summary.p90).toBe(0);
    expect(summary.max).toBe(0);
  });
});

describe('parseCookieJar', () => {
  const jar = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by libcurl!',
    '',
    '#HttpOnly_d1234abcdef8.cloudfront.net\tFALSE\t/\tTRUE\t0\t__Host-footbag_session\tabc.def.ghi',
  ].join('\n');

  it('keeps an HttpOnly cookie, whose line curl writes behind a comment marker', () => {
    expect(parseCookieJar(jar)).toBe('__Host-footbag_session=abc.def.ghi');
  });

  it('drops the real comment lines and blank lines', () => {
    expect(parseCookieJar('# just a comment\n\n')).toBe('');
  });

  it('joins several cookies the way a request header carries them', () => {
    const two = [
      '#HttpOnly_host\tFALSE\t/\tTRUE\t0\t__Host-footbag_session\tone',
      'host\tFALSE\t/\tTRUE\t0\tfootbag_csrf\ttwo',
    ].join('\n');
    expect(parseCookieJar(two)).toBe('__Host-footbag_session=one; footbag_csrf=two');
  });

  it('ignores a malformed row rather than emitting a nameless pair', () => {
    expect(parseCookieJar('host\tFALSE\t/\n')).toBe('');
  });
});

describe('the scenario', () => {
  it('carries the session on the member page and on nothing else', () => {
    const entries = buildScenario('/members/t1_paid');
    const authenticated = entries.filter((entry) => entry.authenticated);
    expect(authenticated.map((entry) => entry.path)).toEqual(['/members/t1_paid']);
  });

  it('puts the sign-in page in the mix without a session, since a signed-in visitor is redirected away from it', () => {
    const entries = buildScenario('/members/t1_paid');
    const login = entries.find((entry) => entry.path === '/login');
    expect(login?.authenticated).toBe(false);
  });

  it('expands weights into a sequence proportional to them', () => {
    const expanded = expandScenario([
      { path: '/a', weight: 3, authenticated: false },
      { path: '/b', weight: 1, authenticated: false },
    ]);
    expect(expanded).toHaveLength(4);
    expect(expanded.filter((entry) => entry.path === '/a')).toHaveLength(3);
  });
});
